-- Comprehensive FAQ Data for Medical Billing Specialties
-- Optimized for SEO, E-E-A-T, Answer Search, and AI Search Engines

-- ============================================
-- CARDIOLOGY FAQs
-- ============================================

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('cardiology', 'billing-basics', 'What makes cardiology billing more complex than other specialties?',
'Cardiology billing is uniquely complex due to several factors: (1) High-value procedures with expensive device implantations requiring separate billing, (2) Multiple procedure modifiers for interventional procedures performed during the same session, (3) Complex global period management for surgical interventions, (4) Prior authorization requirements for diagnostic tests and procedures, (5) Technical and professional component billing for in-office diagnostics like echocardiograms and stress tests, and (6) Intricate bundling rules for cardiac catheterization procedures. Additionally, cardiology practices often perform procedures in multiple settings (office, hospital, ASC), each with different billing requirements and fee schedules.',
'Cardiology billing complexity stems from high-value procedures, device billing, complex modifiers, global periods, prior authorizations, and multiple procedure settings with different requirements.',
10,
ARRAY['cardiology billing complexity', 'cardiac procedure billing', 'interventional cardiology', 'device implantation billing']),

('cardiology', 'coding', 'How do you code for cardiac catheterization procedures?',
'Cardiac catheterization coding requires detailed understanding of CPT codes 93451-93533. Key considerations include: (1) Left heart catheterization (93452-93453) vs right heart catheterization (93451), (2) Coronary angiography codes (93454-93461) based on native vessels, grafts, or both, (3) Add-on codes for additional vessels or interventions, (4) Modifier usage for bilateral procedures or distinct procedural services, (5) Documentation of catheter placement approach (femoral, radial, brachial), (6) Imaging components (supervision and interpretation), and (7) Professional vs technical component billing. Proper coding requires clear documentation of all vessels studied, interventions performed, and medical necessity justification. Bundling edits must be carefully reviewed to avoid denials.',
'Cardiac catheterization coding uses CPT 93451-93533 based on left/right heart access, vessels studied, and interventions performed, requiring detailed documentation and modifier application.',
20,
ARRAY['cardiac catheterization coding', 'CPT 93451', 'coronary angiography codes', 'heart cath billing']),

('cardiology', 'coding', 'What CPT codes are used for pacemaker and ICD implantation?',
'Pacemaker and ICD implantation codes are categorized by device type and complexity: **Pacemakers:** (1) Single chamber (33206-33208), (2) Dual chamber (33207-33208), (3) Biventricular/CRT-P (33224-33226). **ICDs:** (1) Single chamber ICD (33240-33241), (2) Dual chamber ICD (33249), (3) Biventricular ICD/CRT-D (33249 with leadless system). **Additional codes:** (1) Lead placement/repositioning (33210-33211, 33215-33216), (2) Generator replacement (33227-33229 for pacemakers, 33262-33264 for ICDs), (3) Electrode removal (33234-33235), (4) Device interrogation and programming (93279-93299). Documentation must include device manufacturer, model number, battery status, lead placement locations, fluoroscopy use, and medical necessity. Separate billing is required for the device hardware using HCPCS codes.',
'Pacemaker codes: 33206-33208 (single), 33207-33208 (dual), 33224-33226 (biventricular). ICD codes: 33240-33241 (single), 33249 (dual/CRT-D). Include device HCPCS codes for hardware billing.',
30,
ARRAY['pacemaker coding', 'ICD implantation codes', 'CPT 33206', 'cardiac device billing', 'CRT-D coding']),

('cardiology', 'insurance', 'What prior authorizations are typically required for cardiac procedures?',
'Most cardiac procedures require prior authorization, varying by payer: **Diagnostic Testing:** Stress tests (nuclear, echo, pharmacological), cardiac CT/MRI, Holter monitors beyond 24 hours, event recorders. **Interventional Procedures:** Cardiac catheterization, angioplasty/stent placement, atherectomy, valvuloplasty. **Device Implantation:** Pacemakers, ICDs, CRT devices, implantable loop recorders. **Structural Heart:** TAVR, MitraClip, left atrial appendage closure. **Documentation Requirements:** Clinical indications, previous conservative treatment attempts, relevant diagnostic test results, ACC/AHA guideline compliance, urgency justification. Timeframes vary: Medicare typically 1-5 days, commercial payers 3-10 business days. Emergency procedures may qualify for retrospective authorization. Maintain detailed authorization tracking to avoid denials.',
'Cardiac procedures requiring prior auth include stress tests, catheterizations, device implants, and structural heart procedures. Documentation must show medical necessity, guideline compliance, and previous conservative management.',
40,
ARRAY['cardiac prior authorization', 'pacemaker authorization', 'stress test authorization', 'catheterization approval']),

('cardiology', 'compliance', 'What are the global period rules for cardiac surgery?',
'Cardiac surgical procedures have 90-day global periods (major surgery) with specific billing rules: **Included in Global Package:** (1) Pre-operative visits (day before through day of surgery), (2) Intraoperative services by the surgeon, (3) Post-operative care for 90 days, (4) Complications not requiring return to OR, (5) Post-operative pain management by surgeon. **Separately Billable (with modifiers):** Modifier 24: Unrelated E/M during global period for different diagnosis. Modifier 25: Significant, separately identifiable E/M same day as minor procedure. Modifier 58: Staged/related procedure during global period (resets global period). Modifier 78: Return to OR for complication (global period does not reset). Modifier 79: Unrelated procedure during global period (new global period). **Common Cardiac Surgeries with 90-day Globals:** CABG (33510-33536), valve replacements (33405-33478), septal defect repairs (33641-33647).',
'Cardiac surgeries have 90-day global periods covering pre-op, surgery, and post-op care. Use modifiers 24, 25, 58, 78, or 79 for services outside global package.',
50,
ARRAY['cardiac surgery global period', 'modifier 78', 'CABG global period', '90-day global period']),

('cardiology', 'denials', 'Why are cardiac catheterization claims frequently denied?',
'Cardiac catheterization denials occur due to: **Medical Necessity Issues:** (1) Insufficient documentation of symptoms justifying procedure, (2) Missing non-invasive testing results, (3) Lack of ACC/AHA guideline compliance documentation. **Coding Errors:** (1) Incorrect bundling with coronary angiography, (2) Missing or incorrect modifiers (26, TC, 59, XU), (3) Wrong add-on code usage, (4) Improper bilateral modifier application. **Authorization Problems:** (1) Expired or missing prior authorization, (2) Procedure performed at non-authorized facility, (3) Different procedure than authorized. **Documentation Deficiencies:** (1) Incomplete procedure note, (2) Missing vessel documentation, (3) Absent medical necessity statement, (4) No contrast documentation. **Prevention:** Obtain robust pre-authorization, ensure comprehensive documentation, use correct CPT/modifier combinations, verify facility authorization, document all vessels studied.',
'Catheterization denials result from insufficient medical necessity documentation, incorrect bundling/modifiers, missing authorizations, or incomplete procedure documentation. Prevention requires robust pre-auth and detailed documentation.',
60,
ARRAY['catheterization denials', 'cardiac cath claim denial', 'medical necessity denial', 'bundling denial']),

('cardiology', 'billing-basics', 'How do you bill for echocardiograms and stress tests?',
'**Echocardiogram Billing:** Code selection based on type and completeness: (1) Transthoracic echo complete (93306) or limited (93308), (2) Transesophageal echo (93312-93318), (3) Stress echo (93350-93352), (4) Doppler studies (93320-93325 as add-ons), (5) 3D echocardiography (93319 add-on). Bill professional (modifier 26), technical (modifier TC), or global (no modifier) based on setting. **Stress Test Billing:** (1) Cardiovascular stress test with ECG monitoring (93015-93018), (2) Nuclear stress test myocardial perfusion (78451-78454), (3) Pharmacological stress (adenosine, dobutamine) when exercise contraindicated, (4) Stress echo (93350), (5) Supervision/interpretation separate from technical component. Document indication, protocol used, patient response, termination criteria, and interpretation findings for medical necessity.',
'Echocardiograms: Use 93306 (complete TTE), 93308 (limited), 93312-93318 (TEE) with 26/TC modifiers. Stress tests: 93015-93018 (exercise ECG), 78451-78454 (nuclear perfusion). Document indication and interpretation.',
70,
ARRAY['echocardiogram billing', 'stress test coding', 'CPT 93306', 'nuclear stress test', 'echo modifier']),

('cardiology', 'insurance', 'What documentation supports medical necessity for cardiac procedures?',
'Comprehensive medical necessity documentation requires: **Clinical Presentation:** (1) Detailed symptom description (chest pain character, radiation, duration, triggers), (2) NYHA or CCS functional classification, (3) Impact on daily activities and quality of life, (4) Risk stratification scores when applicable. **Diagnostic Workup:** (1) Results of non-invasive testing (EKG, echo, stress test, cardiac CT), (2) Laboratory values (troponin, BNP, lipid panel), (3) Previous cardiac history and interventions. **Guideline Compliance:** (1) ACC/AHA guideline reference and class/level of evidence, (2) Appropriate use criteria (AUC) scores for imaging, (3) SCAI risk classification for interventions. **Treatment Rationale:** (1) Why procedure is necessary now, (2) Previous conservative management attempts and results, (3) Risks of delaying intervention, (4) Expected outcomes and benefits. **Urgency Assessment:** Emergent, urgent, or elective classification with justification.',
'Medical necessity documentation requires detailed symptoms, non-invasive test results, ACC/AHA guideline references, previous treatment history, appropriate use criteria scores, and clear treatment rationale.',
80,
ARRAY['cardiac medical necessity', 'procedure justification', 'ACC AHA guidelines', 'appropriate use criteria']);

-- ============================================
-- DERMATOLOGY FAQs
-- ============================================

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('dermatology', 'billing-basics', 'How do you distinguish between medical and cosmetic dermatology billing?',
'The distinction between medical and cosmetic dermatology is critical for proper billing and patient financial responsibility: **Medical Dermatology (Insurance Covered):** (1) Diagnostic services for skin conditions, lesions, or diseases, (2) Treatment of medically necessary conditions (acne, psoriasis, eczema), (3) Skin cancer screening and treatment, (4) Lesion biopsy and removal for diagnostic purposes, (5) Treatment of symptomatic or functional impairment. **Cosmetic Dermatology (Patient Pay):** (1) Services solely for appearance enhancement, (2) Wrinkle reduction without functional impairment, (3) Scar revision for cosmetic purposes only, (4) Hair removal, (5) Skin rejuvenation treatments. **Documentation Requirements:** Medical necessity must be clearly documented with symptoms, functional limitations, failed conservative treatments, and medical rationale. Use diagnosis codes that support medical necessity (L-codes for skin conditions) not cosmetic codes (Z-codes for cosmetic reasons). Obtain proper ABN (Advance Beneficiary Notice) when services may not be covered.',
'Medical dermatology (covered): diagnostic services, disease treatment, medically necessary lesion removal. Cosmetic (patient-pay): appearance enhancement, wrinkle reduction, elective procedures. Document medical necessity with symptoms and functional impairment.',
10,
ARRAY['medical vs cosmetic dermatology', 'cosmetic billing', 'dermatology insurance coverage', 'medical necessity dermatology']),

('dermatology', 'coding', 'What are the CPT codes for skin lesion removal and destruction?',
'Skin lesion procedures use specific codes based on method and size: **Excision (11400-11646):** Full-thickness removal with closure, coded by location and size: Face/ears/neck/hands/feet (11440-11446), scalp/trunk/arms/legs (11400-11406), measured in centimeters including margins. **Shave Removal (11300-11313):** Tangential removal without full-thickness excision, by location: Trunk/arms/legs (11300-11303), scalp/neck/hands/feet/genitals (11305-11308), face/ears/eyelids/nose/lips/mucous membranes (11310-11313). **Destruction (17000-17286):** Benign lesions (17000 first, 17003 each additional 2-14, 17004 for 15+), Premalignant lesions (17000-17004), Malignant lesions (17260-17286 based on size). **Documentation:** Measure and document size in cm, specify location, document pathology diagnosis, note technique and closure type, photograph when appropriate.',
'Excision codes: 11400-11646 by location/size with margins. Shave removal: 11300-11313 by location. Destruction: 17000-17004 (benign/premalignant), 17260-17286 (malignant by size). Measure lesions including margins.',
20,
ARRAY['lesion removal codes', 'CPT 11400', 'shave removal billing', 'lesion destruction codes', 'excision coding']),

('dermatology', 'coding', 'How do you code for multiple lesion removals in one visit?',
'Multiple lesion billing requires careful coding and modifier application: **Excisions (11400-11646):** Report each lesion separately with different sizes/locations, use modifier 59 or XS for distinct lesions, add diameters for adjacent lesions excised together. **Shave Removals (11300-11313):** Bill each lesion separately with appropriate modifiers for multiple procedures. **Destructions:** 17000 for first lesion, 17003 for 2-14 additional lesions (one unit per lesion), 17004 for 15+ lesions (flat fee). **Biopsies:** Report each biopsy separately (11102 for first, 11103 for each additional). **Key Rules:** (1) Same-site grouping by body area, (2) Modifier 59 for separate lesions preventing bundling, (3) Proper documentation of each lesion location, size, and pathology, (4) Medical necessity for each removal, (5) Photograph documentation recommended. **Avoid:** Billing same code multiple times without modifiers, combining lesions inappropriately, insufficient location documentation.',
'Bill each lesion separately with appropriate code and modifiers. Use 17000 + 17003 for destructions (2-14 lesions), modifier 59/XS for distinct excisions/removals, document each lesion location and size individually.',
30,
ARRAY['multiple lesion billing', 'modifier 59 dermatology', '17000 17003 codes', 'multiple excisions']),

('dermatology', 'insurance', 'What prior authorizations are needed for dermatology procedures?',
'Prior authorization requirements vary by payer but commonly include: **Biologic Medications:** (1) Dupixent, Skyrizi, Taltz, Cosentyx for psoriasis/eczema, (2) Requires documented severity scores (PASI, DLQI), (3) Failed conventional therapy documentation, (4) Photographs of affected areas. **Mohs Surgery:** Many payers require pre-authorization for Mohs micrographic surgery, particularly for certain body locations or tumor types. **Advanced Treatments:** (1) Excimer laser (308nm) for psoriasis/vitiligo, (2) Phototherapy beyond certain frequency, (3) High-cost topical medications. **Cosmetic vs Medical Determination:** Procedures that may be cosmetic require clear medical necessity documentation to avoid denial. **Authorization Tips:** Submit clinical documentation early (2-3 weeks before), include photographs with measuring ruler, document failed treatments with dates and outcomes, reference medical necessity criteria, obtain peer-to-peer review if initially denied.',
'Biologics for psoriasis/eczema require prior auth with severity scores and failed treatment documentation. Mohs surgery and advanced treatments may need authorization. Submit clinical photos and medical necessity documentation 2-3 weeks early.',
40,
ARRAY['dermatology prior authorization', 'biologic authorization', 'Mohs surgery authorization', 'Dupixent approval']),

('dermatology', 'compliance', 'What are the compliance risks in dermatology billing?',
'Key compliance risks include: **Cosmetic vs Medical Misclassification:** Billing cosmetic procedures as medical to obtain insurance payment constitutes fraud. Clear documentation of medical necessity is essential. **Lesion Measurement Accuracy:** Overstating lesion size to justify higher-level codes, not including margins in measurements, or documenting removed tissue instead of lesion size. **Pathology Coordination Issues:** Billing for services not performed, charging for pathology provided by reference lab, missing medical necessity for biopsy. **Incident-To Billing:** Improperly billing PA/NP services under physician when supervision requirements not met. **Documentation Deficiencies:** Insufficient documentation of medical necessity, missing lesion descriptions, absent treatment justification. **Split/Shared Visits:** Improper documentation of physician participation in split/shared E/M services. **Prevention:** Implement pre-service documentation review, use photographic documentation with measurement, maintain pathology coordination records, conduct regular compliance audits, train staff on medical necessity requirements.',
'Risks include cosmetic/medical misclassification, lesion measurement inaccuracies, pathology coordination issues, incident-to billing errors, and documentation deficiencies. Prevent with pre-service review, photography, and regular audits.',
50,
ARRAY['dermatology compliance', 'billing fraud dermatology', 'lesion measurement compliance', 'incident-to billing']),

('dermatology', 'denials', 'Why are dermatology skin biopsy claims denied?',
'Common biopsy denial reasons: **Medical Necessity:** (1) Insufficient documentation of lesion characteristics justifying biopsy, (2) No documented change in lesion appearance, (3) Missing clinical suspicion of malignancy, (4) Routine screening without specific indication. **Coding Issues:** (1) Incorrect biopsy code selection (11102 vs 11104), (2) Improper add-on code usage (11103 vs 11105), (3) Missing or incorrect modifiers, (4) Bundling with same-day E/M without modifier 25. **Documentation Problems:** (1) Inadequate lesion description (size, color, borders, appearance), (2) No documented differential diagnosis, (3) Missing body location specificity, (4) Absent medical decision-making rationale. **Pathology Issues:** (1) Specimen handling or labeling errors, (2) Missing pathology report coordination, (3) Billing for pathology when included in global service. **Prevention:** Use detailed lesion descriptors, photograph suspicious lesions, document clinical concern, obtain prior auth when required, ensure modifier 25 for same-day E/M.',
'Biopsies denied for insufficient medical necessity documentation, missing lesion characteristics, improper add-on codes (11103/11105), or bundling issues. Document suspicion of malignancy, lesion changes, and clinical rationale with photographs.',
60,
ARRAY['biopsy denial', 'CPT 11102 denial', 'lesion biopsy medical necessity', 'dermatology claim denial']),

('dermatology', 'billing-basics', 'How do you bill for Mohs micrographic surgery?',
'Mohs surgery billing is complex and stage-based: **Primary Codes:** CPT 17311-17315 based on location: Head/neck/hands/feet/genitals (17311-17313), Trunk/arms/legs (17314-17315). **Stage Billing:** First stage includes excision and first-level histopathology (17311 or 17314). Each additional stage uses add-on codes: 17312 or 17315 for blocks 1-5, +17313 or +17315 for each additional block beyond 5. **Reconstruction:** Bill separately with appropriate repair codes (12001-13160) or flap/graft codes (14000-15261). Simple repairs may be included. **Documentation Requirements:** (1) Complete operative note with stage details, (2) Number and location of tissue blocks per stage, (3) Frozen section interpretation for each stage, (4) Defect size after final stage, (5) Reconstruction method and complexity, (6) Margin status and tumor clearance. **Tips:** Separate documentation for each stage, track blocks carefully, document medical necessity for Mohs vs standard excision, obtain prior authorization when required.',
'Mohs codes: 17311-17313 (head/neck/hands/feet/genitals), 17314-17315 (trunk/arms/legs) for first stage. Add-on codes 17312/17313 or 17315 for additional stages/blocks. Bill reconstruction separately. Document blocks per stage.',
70,
ARRAY['Mohs surgery billing', 'CPT 17311', 'Mohs micrographic surgery', 'Mohs coding']),

('dermatology', 'technology', 'What modifiers are essential for dermatology billing?',
'Critical dermatology modifiers: **Modifier 25:** Significant, separately identifiable E/M on same day as procedure. Most important dermatology modifier. Required when: diagnosis established during visit leads to same-day procedure, distinct evaluation beyond procedure decision. **Modifier 59/XS:** Distinct procedural service for multiple lesions at different anatomic sites preventing bundling. Use XS (separate structure) for different body sites. **Modifier 79:** Unrelated procedure during global period. For new lesion discovery/treatment during post-op period. **Modifier 78:** Related procedure during global period requiring return to OR/procedure room. **Modifier 76:** Repeat procedure by same physician (rare in dermatology). **Modifier 51:** Multiple procedures (many payers apply automatically, but include when required). **Modifier 22:** Increased procedural services due to complexity (requires documentation). **Location Modifiers:** LT/RT for bilateral/unilateral procedures, anatomic location modifiers. **Best Practice:** Default to modifier 25 for E/M with procedure, use 59/XS for multiple distinct lesions, document medical necessity supporting modifier use.',
'Modifier 25: E/M with procedure (most critical). Modifier 59/XS: distinct lesions at different sites. Modifier 79: unrelated procedure during global period. Modifier 78: related procedure during global. Document necessity for all modifiers.',
80,
ARRAY['dermatology modifiers', 'modifier 25 dermatology', 'modifier 59 lesions', 'modifier XS']);

-- ============================================
-- ORTHOPEDICS FAQs
-- ============================================

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('orthopedics', 'billing-basics', 'What makes orthopedic billing uniquely complex?',
'Orthopedic billing complexity stems from multiple factors: **Global Period Management:** Most orthopedic surgeries carry 90-day global periods requiring careful tracking to avoid denials for bundled services. Services during this period are generally non-billable unless specific modifiers apply. **High-Cost Implants:** Joint replacements, plates, screws, and hardware require separate billing with manufacturer documentation and proper HCPCS codes, representing significant revenue if billed correctly. **Fracture Care Billing:** Bundled packages include initial treatment, casting, and follow-up, but additional billable services exist outside the package. **Multiple Procedure Billing:** Many orthopedic visits involve multiple procedures requiring correct sequencing and modifier application to prevent bundling denials. **Workers Compensation:** Different fee schedules, authorization requirements, and documentation needs than standard insurance. **ASC vs Hospital Billing:** Different reimbursement models and requirements based on surgery location. Proper coding knowledge prevents revenue loss from these complexities.',
'Orthopedic billing is complex due to 90-day global periods, high-cost implant billing, fracture care packages, multiple procedure modifiers, workers comp requirements, and varying reimbursement by surgical setting.',
10,
ARRAY['orthopedic billing complexity', 'orthopedic surgery billing', 'implant billing', 'fracture care billing']),

('orthopedics', 'coding', 'How do you code for total joint replacement procedures?',
'Total joint replacement coding requires precise CPT selection: **Hip Replacement:** Total hip arthroplasty (27130), partial hip replacement (27125), revision hip arthroplasty (27134-27138 based on components revised). **Knee Replacement:** Total knee arthroplasty (27447), partial knee replacement/unicondylar (27446), revision total knee (27486-27487). **Shoulder Replacement:** Total shoulder arthroplasty (23472), reverse total shoulder (23472), partial shoulder (23470), revision shoulder (23473-23474). **Component Coding:** Implant components billed separately using HCPCS Level II codes with manufacturer information, lot numbers, and sizes. **Documentation Requirements:** (1) Medical necessity justification (conservative treatment failure, imaging showing degeneration), (2) Implant specifics (manufacturer, model, size, components), (3) Operative report with approach and components, (4) Anesthesia coordination for surgical time. **Avoid:** Unbundling component placement, incorrect revision codes, missing implant documentation.',
'Hip: 27130 (total), 27125 (partial), 27134-27138 (revision). Knee: 27447 (total), 27446 (partial), 27486-27487 (revision). Shoulder: 23472 (total/reverse), 23473-23474 (revision). Bill implants separately with HCPCS codes.',
20,
ARRAY['joint replacement codes', 'CPT 27447', 'total hip arthroplasty', 'total knee replacement coding', '27130']),

('orthopedics', 'coding', 'What are the CPT codes for fracture treatment?',
'Fracture coding depends on treatment method: **Treatment Types:** (1) Closed treatment - realignment without opening skin (2000x series), (2) Open treatment - surgical incision to treat fracture (2001x series), (3) Percutaneous fixation - fixation without opening fracture site (2002x series). **Common Fracture Codes by Location:** Distal radius (25600-25609), Femur shaft (27500-27507), Tibial shaft (27750-27759), Ankle (27808-27828), Hip (27235-27248), Humerus (23600-24582). **Global Package Includes:** Initial treatment, normal follow-up care, cast/splint application and removal, radiological supervision. **Separately Billable:** Cast supplies (A/L codes), complicated follow-ups outside global (modifier 24), unrelated services during global (modifier 79), return to OR for complications (modifier 78). **Documentation:** Document treatment method clearly, indicate manipulation performed, note if anesthesia used, specify hardware if ORIF, describe reduction quality.',
'Fracture codes: closed (2000x), open (2001x), percutaneous (2002x) treatment. Common codes: distal radius 25600-25609, femur 27500-27507, tibia 27750-27759. Global includes initial treatment, casts, and follow-ups.',
30,
ARRAY['fracture coding', 'ORIF codes', 'closed treatment fracture', 'open reduction internal fixation', 'fracture care']),

('orthopedics', 'insurance', 'How do you bill for orthopedic hardware and implants?',
'Implant billing requires detailed documentation: **CPT Procedure Codes:** Bill the surgical procedure code for implant placement (e.g., 27447 for total knee). **HCPCS Implant Codes:** Separately bill for hardware using HCPCS Level II codes: Joint implants (L-codes), Fracture fixation hardware (C-codes for ASC, specific codes for hospital), Bone graft materials (C1062, C1764). **Required Documentation:** (1) Manufacturer name and contact, (2) Product name and catalog number, (3) Lot numbers and serial numbers, (4) Size specifications, (5) Number of each component used, (6) Invoice documentation showing costs, (7) FDA approval status if applicable. **Billing Tips:** Submit detailed invoices with claim, use manufacturer invoice for pricing support, document medical necessity for premium implants, coordinate with facility for ASC billing. **Common Issues:** Missing lot numbers, incomplete manufacturer details, lack of medical necessity for higher-cost implants. Medicare requires detailed documentation for high-cost implants.',
'Bill procedure code (CPT) + implant hardware (HCPCS L/C codes) separately. Document manufacturer, model, lot numbers, sizes, and invoices. Include all component details for proper reimbursement.',
40,
ARRAY['implant billing orthopedic', 'hardware billing', 'HCPCS implant codes', 'joint implant billing', 'plate and screw billing']),

('orthopedics', 'compliance', 'What are the global period rules for orthopedic surgery?',
'Global surgical packages have strict rules: **90-Day Global Period:** Major surgeries (joint replacements, spinal fusions, major fractures) include: Day before through day of surgery, intraoperative services, complications not requiring return to OR, post-op visits for 90 days, post-op pain management, removal of sutures/staples. **10-Day Global Period:** Minor procedures (arthroscopy, simple fracture care) have similar inclusions for 10 days. **Separately Billable Services (Modifiers Required):** Modifier 24 - Unrelated E/M during global (different diagnosis/body area), Modifier 25 - Significant E/M same day as procedure decision, Modifier 58 - Staged/related procedure during global (starts new global), Modifier 78 - Return to OR for complication (no new global), Modifier 79 - Unrelated procedure during global (new global period starts). **Common Mistakes:** Billing included post-op visits, missing modifiers for billable services, incorrect modifier selection, poor documentation of unrelated services. **Best Practice:** Track global end dates, educate providers on global rules, document new/unrelated conditions thoroughly.',
'Orthopedic surgeries have 90-day (major) or 10-day (minor) global periods including pre-op, surgery, and post-op care. Use modifiers 24/25/58/78/79 for services outside global package.',
50,
ARRAY['orthopedic global period', '90-day global period', 'modifier 78 orthopedic', 'surgical global package', 'modifier 79']),

('orthopedics', 'denials', 'Why are joint replacement claims commonly denied?',
'Joint replacement denials occur for several reasons: **Medical Necessity:** (1) Insufficient documentation of conservative treatment failure, (2) Missing or inadequate imaging showing joint degeneration, (3) Lack of functional limitation documentation, (4) No pain management history. **Authorization Issues:** (1) Expired or missing prior authorization, (2) Authorization for wrong facility or surgeon, (3) Different procedure than authorized. **Coding Errors:** (1) Incorrect joint replacement code selection, (2) Missing or wrong implant HCPCS codes, (3) Improper bundling with other procedures, (4) Wrong modifier usage for bilateral procedures. **Documentation Deficiencies:** (1) Incomplete operative report, (2) Missing implant documentation (lot numbers, manufacturers), (3) Absent medical necessity statement, (4) No pre-operative evaluation notes. **Prevention Strategies:** Obtain robust pre-authorization with complete clinical documentation, ensure operative reports include all required elements, verify implant documentation before claim submission, document detailed medical necessity with imaging and treatment history.',
'Denials result from insufficient conservative treatment documentation, missing authorizations, incorrect codes/modifiers for implants, or incomplete operative reports. Prevent with thorough pre-auth, complete documentation, and implant detail verification.',
60,
ARRAY['joint replacement denial', 'TKA denial', 'total hip replacement denied', 'implant claim denial', 'arthroplasty denial']),

('orthopedics', 'billing-basics', 'How do you bill for arthroscopic procedures?',
'Arthroscopy billing requires understanding of bundling and multiple procedures: **Common Arthroscopy Codes:** Shoulder (29806-29828), Knee (29870-29889), Ankle (29894-29899), Hip (29860-29863), Wrist (29840-29848). **Multiple Procedure Rules:** When multiple arthroscopic procedures performed same operative session: (1) List most extensive procedure first (highest RVU), (2) Apply modifier 51 to additional procedures (or payer may apply automatically), (3) Some procedures are bundled by CCI edits - review NCCI. **Common Combinations:** Knee arthroscopy with meniscectomy and chondroplasty - typically 29881 + 29877-51. Shoulder arthroscopy with rotator cuff repair - typically 29827 (primary procedure). **Modifier Usage:** Modifier 59/XS for separate anatomic sites or compartments, Modifier 50 for bilateral procedures, Modifier 51 for multiple procedures. **Documentation:** Clear operative note describing each procedure, separate justification for each procedure, anatomic location specificity, medical necessity for combination procedures.',
'Common codes: shoulder 29806-29828, knee 29870-29889. List highest RVU procedure first, add modifier 51 to additional procedures. Use modifier 59/XS for separate compartments. Check NCCI for bundling edits.',
70,
ARRAY['arthroscopy billing', 'knee arthroscopy codes', 'CPT 29881', 'shoulder arthroscopy coding', 'modifier 51 arthroscopy']),

('orthopedics', 'insurance', 'What are workers compensation billing differences for orthopedics?',
'Workers compensation has unique requirements: **Fee Schedules:** State-specific fee schedules often differ from Medicare, may include: conversion factors, multipliers, or set fees. Reimbursement typically higher than commercial insurance. **Authorization Requirements:** Most services require authorization: Medical treatment authorization (MTA) or pre-authorization, utilization review for surgery and therapy, independent medical exams (IME). **Documentation Standards:** More extensive than standard insurance: First report of injury, progress notes every visit, permanent and stationary (P&S) reports, work status reports for every visit, functional capacity evaluations. **Billing Differences:** Bill with workers comp claim number not group number, use state-specific forms (HCFA-1500 variations), include employer information and injury details, report work status on every claim. **Denials:** More likely if treatment not causally related to injury, if authorization missing/expired, or if documentation doesn't support work-relatedness. **Appeals:** Go through state workers comp board, different timeline than health insurance appeals.',
'Workers comp uses state-specific fee schedules (often higher rates), requires authorization for most services, needs extensive documentation including injury reports and work status. Bill with claim number and injury details.',
80,
ARRAY['workers compensation orthopedic', 'workers comp billing', 'work injury billing', 'IME orthopedic', 'MTA authorization']);

-- Add more FAQs for other categories as needed
