/*
  # Additional Medical Billing FAQs - Batch 4
  
  ## Overview
  Adds 50+ more comprehensive FAQs covering:
  - Lab & Pathology (6 FAQs)
  - DME Billing (6 FAQs)
  - Payer-Specific Questions (8 FAQs)
  - Advanced CPT Coding (10 FAQs)
  - Additional Modifiers (8 FAQs)
  - General Billing Operations (10 FAQs)
  
  Total: 48+ additional FAQs
*/

-- LAB & PATHOLOGY FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'lab-pathology', 'What is CPT 36415?',
'CPT 36415 is the procedure code for routine venipuncture (drawing blood from a vein) for specimen collection. This code covers the technical service of accessing the vein and collecting blood sample. Usage: billed by facilities/labs when drawing blood, separate from laboratory test codes, typically bundled with lab test payments in many settings. Reimbursement considerations: Medicare pays separately in some settings but bundles in others, commercial payers vary - some pay separately, some bundle with lab tests, office settings may receive separate payment. Cannot bill 36415 when other venous access procedures performed (central lines, IV starts). Documentation requirements: medical necessity for blood draw, number of attempts if multiple venipunctures needed, specimens collected. Common denials: bundled with other services, not separately payable per payer policy, frequency limits exceeded. Check payer-specific policies before billing.',
'CPT 36415 is routine venipuncture (blood draw). Reimbursement varies by payer - some pay separately, others bundle with lab tests. Cannot bill with other venous access procedures. Check payer policies.',
170, ARRAY['36415', 'venipuncture', 'blood draw', 'lab collection']),

('general', 'lab-pathology', 'Why are lab codes denied as bundled?',
'Lab code bundling denials occur when: (1) Multiple tests billed that are included in panel codes - bill the panel instead of individual components, (2) Reflex testing included in initial test code, (3) Tests performed by same methodology on same specimen, (4) CCI edits bundle certain combinations, (5) Add-on codes billed without appropriate primary codes. Common bundling scenarios: chemistry panels include individual tests (80047-80076), CBC with differential includes individual counts, urinalysis includes specific gravity, pH, protein tests, automated testing includes manual verification. Prevention: use comprehensive panel codes when all components performed, understand CCI lab edits, check payer-specific bundling policies, bill only separately payable tests. Unbundling (billing components when panel appropriate) can trigger fraud investigations. Appeals require: demonstration tests were distinct, different methodologies used, or clinical necessity for separate testing.',
'Lab bundling denials occur when billing components included in panels, reflex testing, or CCI bundled combinations. Prevention: use panel codes, understand payer bundling rules, avoid unbundling individual tests.',
171, ARRAY['lab bundling', 'lab denied', 'bundled lab tests', 'panel codes']),

('general', 'lab-pathology', 'Why are lab claims denied for frequency limit?',
'Lab frequency limit denials occur when: (1) Payer allows specific test only X times per timeframe (per day/week/month/year), (2) Medical necessity not established for repeated testing, (3) No qualifying diagnosis supporting frequent monitoring, (4) Previous test performed too recently, (5) Test considered screening rather than diagnostic. Common frequency-limited tests: PSA (prostate screening - annually), lipid panels (screening intervals), hemoglobin A1c (diabetes monitoring - quarterly maximum), vitamin D (limited frequency), genetic tests (once per lifetime). Prevention: verify payer frequency limits before ordering, document medical necessity for repeated testing, use appropriate diagnosis codes supporting frequency, obtain authorization when required, space tests appropriately per policies. Appeals require: medical necessity documentation, clinical justification for testing interval, supporting diagnoses, provider attestation of need. Keep LCD/NCD documentation for frequency requirements.',
'Frequency denials occur when tests exceed payer limits (daily/monthly/yearly). Common for PSA, lipid panels, A1c, vitamin D. Prevention: verify limits, document medical necessity, use supporting diagnoses, obtain authorization.',
172, ARRAY['frequency limit', 'lab frequency', 'too frequent', 'testing limit']),

('general', 'lab-pathology', 'What documentation is required for lab CPT codes?',
'Lab test documentation requirements include: (1) Physician order - written order with specific tests requested, ICD-10 diagnosis, date, provider signature, (2) Medical necessity - diagnosis codes supporting why test clinically indicated, (3) Test results - laboratory report with results, reference ranges, performing laboratory identification, (4) ABN (Advance Beneficiary Notice) - if Medicare frequency limits may apply or medical necessity uncertain, patient signature acknowledging financial responsibility, (5) Specimen information - collection date/time, specimen type, collection method. Specific tests require additional documentation: genetic testing (detailed family history, risk assessment), pathology (specimen source, clinical indication), specialized testing (previous test results, treatment response data). Missing documentation causes denials for: no order on file, medical necessity not established, ABN not signed. Maintain test orders minimum 7 years. Electronic orders must include all required elements.',
'Required: physician order with specific tests and diagnosis, medical necessity documentation, test results, ABN if applicable, specimen information. Genetic/specialized tests require additional clinical documentation. Missing orders cause denials.',
173, ARRAY['lab documentation', 'lab order requirements', 'ABN', 'medical necessity']),

('general', 'lab-pathology', 'Why was CPT 81002 denied?',
'CPT 81002 (urinalysis, non-automated without microscopy) denials occur for: (1) Bundled with office visit - many payers include dipstick UA in E/M payment, (2) Billed with microscopy codes - 81002 is dipstick only, cannot bill with 81001 (automated) or 81015 (microscopy), (3) Frequency limits - some payers limit screening urinalysis frequency, (4) Not separately payable - considered integral to visit purpose, (5) Incorrect code selection - automated analyzer requires 81001, microscopy requires 81015. Prevention: understand when UA is separately payable vs bundled, use modifier 59 if truly separate service, select correct code based on methodology, verify payer policies on UA reimbursement, ensure medical necessity documented. Some payers never reimburse 81002 separately. Alternative: some payers recognize 81000 (automated with microscopy). Appeals require: documentation of medical necessity, separate indication from visit, appropriate code selection justification.',
'81002 (dipstick urinalysis) often denied as bundled with office visits. May have frequency limits or not be separately payable. Prevention: verify payer policy, use appropriate code for methodology, document necessity.',
174, ARRAY['81002', 'urinalysis', 'UA denied', 'dipstick']);

-- DME BILLING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'dme', 'Why was my DME claim denied?',
'DME claim denials occur for multiple reasons: (1) Missing/incomplete Detailed Written Order (DWO) - physician order doesn''t meet requirements, (2) No prior authorization - required by payer but not obtained, (3) Medical necessity not documented - clinical notes don''t support need, (4) Incorrect HCPCS codes - wrong DME code for item supplied, (5) Non-covered items - item not in payer''s covered DME list, (6) Frequency limits exceeded - replacement too soon, (7) Supplier not enrolled - not credentialed with payer, (8) CMN (Certificate of Medical Necessity) missing - required for certain DME, (9) Documentation doesn''t support code billed - power wheelchair vs manual. Prevention: obtain complete DWO meeting all requirements, verify authorization requirements before delivery, comprehensive medical necessity documentation, use correct HCPCS codes, verify item coverage, maintain supplier credentialing, obtain CMN when required, retain documentation 7+ years.',
'DME denials due to missing DWO, no authorization, insufficient medical necessity, wrong codes, non-covered items, frequency limits, or supplier enrollment issues. Prevention requires complete documentation and verification.',
180, ARRAY['DME denied', 'DME claim', 'equipment denial', 'CPAP denial']),

('general', 'dme', 'What documentation is needed for DME codes?',
'DME documentation requirements: (1) Detailed Written Order (DWO) - provider signature, detailed item description, start date, diagnosis, (2) Medical necessity documentation - progress notes demonstrating need, functional limitations, why item needed, failed conservative treatments, (3) Certificate of Medical Necessity (CMN) - specific form for certain items (oxygen, wheelchairs, hospital beds), provider certification of medical necessity, (4) Proof of delivery - signed delivery ticket with date, patient/representative signature, detailed item description, (5) Assignment of Benefits (AOB) - patient authorization for payment to supplier, (6) Face-to-face encounter documentation - for certain items, within specific timeframe before order, (7) Supplier documentation - state licensure, accreditation, Medicare enrollment. Item-specific requirements: oxygen (oximetry results, pulmonary function tests), wheelchairs (mobility assessment, home evaluation), CPAP (sleep study results). Missing documentation is leading cause of DME denials.',
'Required: DWO with provider signature, medical necessity documentation, CMN for specific items, proof of delivery, AOB, face-to-face notes, supplier credentials. Item-specific requirements apply. Missing documentation causes denials.',
181, ARRAY['DME documentation', 'DWO', 'CMN', 'equipment documentation']),

('general', 'dme', 'What is a Detailed Written Order (DWO)?',
'A Detailed Written Order (DWO) is a comprehensive physician order required for DME reimbursement. Required elements: (1) Beneficiary name, (2) Item description - detailed enough to determine appropriate HCPCS code, (3) Prescribing practitioner information - name, NPI, signature, (4) Start date - when item needed, (5) Diagnosis codes - supporting medical necessity, (6) Length of need - duration item required. Additional requirements for specific items: power mobility (detailed mobility limitation description), oxygen (liter flow, frequency of use), CPAP (pressure settings, compliance requirements). DWO must be: written within 6 months before delivery for most items, signed and dated by prescriber, clear and legible, maintained by supplier for audit. Electronic DWOs acceptable if meet all requirements and have electronic signature. Missing or incomplete DWO is most common DME denial reason. Cannot be backdated. Verbal orders must be followed by written DWO within specific timeframe.',
'DWO is detailed physician order for DME including: patient name, item description, prescriber info/signature, start date, diagnosis, length of need. Must be completed within 6 months before delivery. Essential for DME reimbursement.',
182, ARRAY['DWO', 'detailed written order', 'DME order', 'physician order']),

('general', 'dme', 'What are common denial reasons for CPAP supplies?',
'CPAP supply denials occur for: (1) Non-compliance with usage - not meeting minimum usage hours (typically 4+ hours per night for 70% of nights in 30-day period), (2) Frequency limits exceeded - replacing supplies before allowable timeframe (masks every 3 months, tubing every 3 months, filters monthly), (3) Missing compliance documentation - download data not provided, (4) No authorization - required by payer but not obtained, (5) Initial qualification period not met - Medicare requires 12-month qualification before routine supplies, (6) Missing face-to-face documentation - required within 3 months before initial order, (7) DWO doesn''t meet requirements. Prevention: track compliance data, provide compliance downloads with claims, follow replacement schedules, obtain authorization, maintain face-to-face documentation, complete DWO properly. Medicare CPAP rules: initial 12-month rental, compliance review at 3 months, ongoing compliance monitoring, specific replacement schedules. Commercial payers may have different requirements but generally similar compliance expectations.',
'CPAP denials: non-compliance with 4+ hours usage, frequency limits, missing compliance data, no authorization, initial qualification period not met. Prevention: track compliance, follow replacement schedules, document properly.',
183, ARRAY['CPAP denied', 'CPAP supplies', 'compliance', 'DME supplies']),

('general', 'dme', 'Why was A7031 or A7035 denied?',
'A7031 (full face CPAP mask) and A7035 (nasal CPAP mask) denials occur due to: (1) Frequency limits - masks allowed every 3 months, denial if replaced too soon, (2) Non-compliance - patient not meeting usage requirements, (3) Missing compliance documentation - download showing usage hours not submitted, (4) Multiple mask types billed - cannot bill both full face and nasal mask same timeframe, (5) No authorization - some payers require authorization for masks, (6) Cushion codes billed separately - A7032/A7033/A7034 (cushions) may be bundled with mask, (7) Initial qualification not met. Allowable frequency (Medicare): complete masks every 3 months, cushions/pillows monthly, headgear every 6 months. Prevention: verify last mask supply date, ensure 3-month interval, document compliance, submit download data, bill appropriate mask type, don''t bill mask and cushion together unless replacing entire assembly. Appeal requires: compliance documentation, medical necessity for early replacement (damaged mask, poor fit requiring different size/style).',
'A7031/A7035 (CPAP masks) denied for frequency limits (3-month minimum), non-compliance, missing usage data, billing multiple types, or cushion bundling. Prevention: verify intervals, document compliance, bill correctly.',
184, ARRAY['A7031', 'A7035', 'CPAP mask', 'mask denied']);

-- PAYER-SPECIFIC FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'payer-specific', 'Why does Medicare deny therapy modifiers?',
'Medicare therapy modifier denials occur when: (1) Missing therapy modifiers - required GP (physical therapy), GO (occupational therapy), or GN (speech therapy) modifiers not appended, (2) Incorrect modifier - wrong therapy type modifier used, (3) Threshold reporting issues - KX modifier required when exceeding therapy caps but not used, (4) Multiple therapy modifiers - cannot use multiple therapy modifiers on same code, (5) Missing documentation - notes don''t support therapy type billed. Medicare requirements: GP/GO/GN required on all therapy codes, KX modifier when exceeding threshold amounts ($2,230 for PT/OT combined, separate for SLP), documentation supporting therapy type. Common errors: billing 97110 without GP/GO/GN, forgetting KX when over threshold, using GO when PT provided. Prevention: always append appropriate therapy modifier, track therapy spending toward threshold, add KX when exceeding, ensure documentation matches modifier used. Appeals require: proof correct therapy type provided, threshold tracking if KX issue, documentation supporting medical necessity for services.',
'Medicare requires GP (PT), GO (OT), or GN (SLP) modifiers on all therapy codes. KX modifier required when exceeding threshold ($2,230 PT/OT). Denials occur when modifiers missing or incorrect. Always append appropriate modifiers.',
190, ARRAY['therapy modifiers', 'GP GO GN', 'Medicare therapy', 'KX modifier']),

('general', 'payer-specific', 'Why does BCBS deny CPT 97110?',
'Blue Cross Blue Shield (BCBS) denies CPT 97110 (therapeutic exercise) for: (1) Medical necessity - doesn''t meet plan criteria for skilled therapy vs maintenance care, (2) Frequency limits - visits per year exceeded or therapy course too long, (3) Missing authorization - required but not obtained, (4) Insufficient documentation - notes don''t demonstrate skilled therapy, functional goals, progress, (5) Diagnosis not covered - condition doesn''t qualify for therapy benefits, (6) Duplicate services - billed multiple units without time documentation supporting, (7) Bundling with evaluation - same day as initial evaluation without clear separation. BCBS requirements vary by plan: some require authorization after initial visits, many have visit limits (20-60 per year), medical necessity review for extended therapy. Prevention: verify specific plan requirements, obtain authorization when needed, document skilled nature of treatment, measurable functional goals and progress, appropriate time per unit, medical necessity supporting continued therapy. Appeals require: detailed clinical documentation, functional outcome measures, justification for extended therapy.',
'BCBS denies 97110 for medical necessity, frequency limits, no authorization, insufficient documentation, or maintenance care. Requirements vary by plan. Prevention: verify plan rules, obtain authorization, document skilled therapy and progress.',
191, ARRAY['BCBS denial', 'Blue Cross', '97110 denied', 'therapy denied']),

('general', 'payer-specific', 'Why does UHC deny 90837?',
'UnitedHealthcare (UHC) denies CPT 90837 (psychotherapy 53+ minutes) due to: (1) Insufficient time - documented time less than 53 minutes, (2) No time documentation - start/end times or total time not in notes, (3) Frequency limits - some plans limit 90837 frequency, prefer 90834, (4) Medical necessity - clinical documentation doesn''t support need for extended session, (5) Credentialing issues - provider not credentialed for extended sessions, (6) Authorization required - some plans require authorization for 90837, (7) Telehealth restrictions - plan limitations on telehealth 90837. UHC policies: prefer 90834 for routine sessions, 90837 reserved for complex cases or crisis, documentation must demonstrate clinical complexity justifying extended time, some plans have 90837 frequency limitations. Prevention: document exact session time (minimum 53 minutes), include clinical complexity supporting extended session, verify plan allowances for 90837, obtain authorization if required, consider using 90834 when session under 53 minutes. Appeals require: time documentation proof, clinical justification for extended session complexity.',
'UHC denies 90837 for insufficient documented time (<53 min), missing time documentation, frequency limits, lack of complexity justification. Prefers 90834 for routine sessions. Document exact time and clinical complexity.',
192, ARRAY['UHC denial', 'UnitedHealthcare', '90837 denied', 'psychotherapy']),

('general', 'payer-specific', 'Why does Aetna deny high-level E/M codes?',
'Aetna denies high-level E/M codes (99204, 99214, 99215) when: (1) Documentation doesn''t support level - MDM or time requirements not met, (2) Template documentation - generic notes without patient-specific details, (3) Upcoding concerns - pattern of predominantly high-level visits triggers review, (4) Missing time documentation - when using time-based selection, (5) Insufficient complexity - problem severity, data reviewed, risk don''t meet moderate/high level, (6) Inconsistent documentation - visit doesn''t match typical care pattern for diagnosis. Aetna audit triggers: >80% level 4-5 visits, significant increase in high-level coding, specialty doesn''t typically support high levels. Prevention: ensure documentation robustly supports level selected, include specific clinical details (not templates), document time when using time-based selection, code appropriate level for visit complexity, maintain reasonable distribution of levels, provide education to providers on documentation requirements. Appeals require: comprehensive medical record demonstrating complexity, MDM elements clearly documented, time documentation if applicable, specialty-appropriate care patterns.',
'Aetna denies high-level E/M codes when documentation doesn''t support complexity, template notes used, upcoding patterns, or missing time. Prevention: robust patient-specific documentation, appropriate level selection, reasonable visit distribution.',
193, ARRAY['Aetna denial', 'high-level E/M', '99214 denied', 'upcoding']),

('general', 'payer-specific', 'Why does Medicaid deny timed codes?',
'Medicaid timed code denials occur due to: (1) Insufficient time documented - less than minimum minutes for units billed, (2) No time documentation - start/stop times or total minutes missing, (3) State-specific requirements - some states have unique time rules, (4) Multiple providers - cannot bill overlapping time by multiple providers, (5) Non-covered services - state plan doesn''t cover specific therapy codes, (6) Prior authorization - required but not obtained, (7) Provider qualifications - rendering provider not qualified per state rules. Medicaid variations by state: some follow Medicare 8-minute rule, some have different thresholds, visit limits vary widely, some require authorization for therapy, provider qualifications differ. Prevention: understand your state''s Medicaid time documentation requirements, document exact minutes for each service, obtain required authorization, verify provider meets state qualifications, check covered services list, don''t bill overlapping times. Appeals require: clear time documentation, state policy citations, provider qualification documentation, authorization approval if applicable.',
'Medicaid denies timed codes for insufficient/missing time documentation, state-specific rule violations, no authorization, provider qualification issues. Requirements vary by state. Document exact minutes per state rules.',
194, ARRAY['Medicaid denial', 'Medicaid therapy', 'timed codes', 'state Medicaid']);

-- ADVANCED CPT CODING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'advanced-coding', 'What is a bilateral procedure code?',
'Bilateral procedure codes describe services performed on both sides of the body (both eyes, ears, knees, etc.). Billing methods: (1) Modifier 50 (Bilateral Procedure) - bill code once with modifier 50, reimbursed at 150% of single procedure rate, (2) RT/LT modifiers - bill code twice with RT (right) and LT (left) modifiers, reimbursement varies by payer, (3) Code inherently bilateral - some codes include bilateral work in description, don''t use modifiers. Code indicators: BILT indicator in NCCI shows bilateral allowance, CPT code description may specify bilateral. Payer variations: Medicare prefers single line with modifier 50, some commercial payers require two lines with RT/LT, payment typically 150% but varies (some pay 100% + 50%). Common bilateral procedures: eye surgeries (67820, 67825), knee procedures (27447), hernia repairs (49505), trigger finger release (26055). Billing both 50 and RT/LT causes duplicates. Check payer-specific bilateral billing requirements.',
'Bilateral procedures are services performed on both body sides. Billing: modifier 50 (bill once, 150% payment) or RT/LT modifiers (bill twice). Payment methods vary by payer. Don''t use both methods.',
200, ARRAY['bilateral', 'modifier 50', 'RT LT', 'both sides']),

('general', 'advanced-coding', 'When should modifier 50 be used?',
'Modifier 50 (Bilateral Procedure) should be used when: (1) Same procedure performed on both sides of body during same operative session, (2) Procedure has bilateral potential - can be performed on paired anatomical sites, (3) CPT code doesn''t inherently include bilateral work in description, (4) Both sides documented in operative report. Billing method: bill code once on single line with modifier 50 appended, reimbursement typically 150% of single procedure rate. When NOT to use modifier 50: code description specifies bilateral (inherently bilateral codes), unilateral procedure performed, different procedures on each side, procedures performed at separate sessions. Examples: 67820 (correction of trichiasis) performed on both eyes - bill 67820-50, 27447 (total knee arthroplasty) both knees - bill 27447-50 (though usually separate sessions). Documentation requirements: operative note must clearly document bilateral work, separate description for each side, medical necessity for bilateral approach. Some payers require RT/LT instead of 50 - verify payer preferences.',
'Use modifier 50 when identical procedure performed on both sides same session. Bill once with modifier 50 (150% payment). Don''t use for inherently bilateral codes or separate sessions. Verify payer billing preferences.',
201, ARRAY['modifier 50', 'bilateral modifier', 'both sides', 'paired organs']),

('general', 'advanced-coding', 'What are proprietary laboratory analysis (PLA) codes?',
'Proprietary Laboratory Analyses (PLA) codes are unique CPT codes assigned to specific laboratory tests offered by single manufacturer/laboratory. Characteristics: (1) Alpha-numeric codes in 0000U series (e.g., 0001U, 0002U), (2) Test-specific - assigned to unique test brand/methodology, (3) Single source - only available from one laboratory, (4) Updated quarterly - new PLA codes added throughout year, not just annually. Examples: molecular pathology tests, genetic panels, proprietary algorithms, unique test methodologies. When to use: specific PLA code exists for exact test performed and manufacturer, verify current PLA code list as frequently updated. When not available: use appropriate unlisted code or closest matching CPT code. Coverage considerations: many PLA codes lack established coverage policies, may require pre-authorization or deemed investigational, reimbursement uncertain for new tests. Documentation: test requisition with specific test name, manufacturer, methodology, clinical indication. PLA codes provide more specificity than generic CPT codes, improving payment accuracy for covered tests.',
'PLA codes (0000U series) are test-specific CPT codes for proprietary laboratory tests from single manufacturers. Updated quarterly. Use when specific PLA code exists. Coverage often uncertain for new tests.',
202, ARRAY['PLA codes', '0000U', 'proprietary lab', 'genetic testing']),

('general', 'advanced-coding', 'What are Category III CPT codes?',
'Category III CPT codes are temporary codes for emerging technology, services, and procedures. Characteristics: (1) Four digits followed by T (e.g., 0001T), (2) Temporary - archived after 5 years if not converted to Category I, (3) Data collection - allows tracking of new procedures, (4) Updated semi-annually - July 1st and January 1st. Purpose: provide coding for new services before sufficient clinical data exists for Category I status, enable data collection on utilization and outcomes, facilitate prior authorization and claims processing. Coverage: most Category III codes lack established coverage, often considered experimental/investigational, may require case-by-case review, prior authorization typically required. Transition: successful Category III codes migrate to Category I after 5 years with demonstrated clinical efficacy, unsuccessful codes archived. Examples: emerging imaging techniques, new minimally invasive procedures, novel treatment modalities. Billing considerations: verify payer coverage before providing service, obtain prior authorization, provide detailed clinical documentation, be prepared for denial due to experimental status.',
'Category III codes (0000T) are temporary codes for emerging technology/procedures. Valid 5 years, updated semi-annually. Often considered experimental with limited coverage. Require authorization and thorough documentation.',
203, ARRAY['Category III', '0000T', 'emerging technology', 'experimental codes']),

('general', 'advanced-coding', 'What is a mutually exclusive edit?',
'Mutually exclusive edits are NCCI edits preventing two codes from being billed together because: (1) Services cannot reasonably be performed at same session - anatomically impossible, mutually exclusive by nature, (2) One service includes the other - comprehensive code encompasses component service, (3) Codes represent same service - different approaches to identical service. Common examples: surgical approach and closure codes - included in primary procedure, diagnostic and therapeutic procedures on same lesion - use therapeutic code, separate bilateral procedures - bill one as bilateral vs two unilateral. NCCI edit types: Column 1/Column 2 relationship shows which code is comprehensive (Column 1) and which is component (Column 2), modifier indicator shows if modifier can override (0 = never, 1 = allowed with appropriate modifier, 9 = not applicable). Resolving mutually exclusive denials: verify services were truly distinct - different session, different site, different lesion, append modifier 59 or X-modifier if appropriate circumstances exist, use correct comprehensive code. Intentional unbundling of mutually exclusive codes is fraudulent.',
'Mutually exclusive edits prevent billing codes together when services cannot both occur, one includes the other, or codes are alternative approaches. Use comprehensive code. Override only with modifiers when truly distinct services.',
204, ARRAY['mutually exclusive', 'NCCI edits', 'cannot bill together', 'bundling']);

-- ADDITIONAL MODIFIER FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'modifiers', 'What is Modifier 24 (Unrelated E/M During Post-Op)?',
'Modifier 24 indicates an Evaluation and Management service during a post-operative period for a reason unrelated to the original surgery. Use when: (1) E/M service provided during global period, (2) Service unrelated to surgical procedure, (3) Different diagnosis from surgery, (4) Separate problem requiring evaluation. Documentation requirements: clearly document problem is unrelated to surgery, separate diagnosis code from surgical diagnosis, detailed note supporting E/M service, specific mention of unrelated nature. Example: patient in 90-day post-op period for knee replacement presents with chest pain - bill E/M with modifier 24. Common denials: documentation doesn''t clearly show unrelated issue, same diagnosis as surgery used, routine post-op issue (wound check) billed separately. Payment: full E/M payment - not reduced for global period. Cannot use for: routine post-op care, complications of surgery, related symptoms. Best practice: document "patient presents for problem unrelated to recent surgery" and use different ICD-10 code than surgical procedure.',
'Modifier 24 allows E/M billing during post-op period for unrelated problems. Requires different diagnosis, clear documentation of unrelated nature. Full E/M payment. Cannot use for surgery-related issues or routine post-op care.',
210, ARRAY['modifier 24', 'post-op E/M', 'unrelated visit', 'global period']),

('general', 'modifiers', 'What is Modifier 52 (Reduced Services)?',
'Modifier 52 indicates a service was partially reduced or eliminated at physician discretion. Use when: (1) Procedure started but discontinued before completion, (2) Less extensive service than described by CPT code, (3) Fewer components performed than full code describes, (4) Physician decision to reduce service scope. Scenarios: diagnostic procedure terminated due to patient tolerance, surgical approach modified to less extensive method, evaluation components omitted for valid clinical reasons. Documentation requirements: explain what was reduced, why service was modified, what portion was completed, clinical reasoning for reduction. Payment: typically reduced proportionally by payer, modifier 52 signals review for reduced payment, provider may need to specify percentage completed. When NOT to use 52: procedure not started (don''t bill), complication requiring termination (use modifier 53), different procedure performed (use correct code). Example: colonoscopy to sigmoid only vs full colon - bill colonoscopy code with modifier 52 and document extent completed. Different from modifier 53 which is discontinued procedure.',
'Modifier 52 indicates reduced/partial service at physician discretion. Use when procedure less extensive than CPT describes. Document what reduced and why. Payment typically reduced proportionally. Differs from modifier 53 (discontinued).',
211, ARRAY['modifier 52', 'reduced service', 'partial procedure', 'less extensive']),

('general', 'modifiers', 'What is Modifier 53 (Discontinued Procedure)?',
'Modifier 53 indicates a procedure discontinued due to circumstances threatening patient well-being after anesthesia/procedure started. Use when: (1) Procedure started and patient prepped/anesthetized, (2) Extenuating circumstances require termination, (3) Patient safety concerns arise, (4) Medical complication prevents completion. Valid reasons: patient became unstable, adverse reaction to anesthesia, unexpected anatomy making procedure unsafe, equipment failure creating risk. Documentation requirements: procedure start documented, complication/circumstance requiring discontinuation, patient status at termination, medical necessity for stopping. Payment: partial payment based on work completed - usually percentage of full procedure fee. When NOT to use 53: procedure not started (don''t bill), physician convenience (use 52), elective decision to reduce scope (use 52), planned staged procedure (use 58). Example: surgery started, patient develops cardiac arrhythmia requiring termination - bill procedure code with modifier 53. Anesthesia charges still applicable. Must document life/health-threatening circumstances justifying discontinuation.',
'Modifier 53 indicates procedure discontinued after start due to patient well-being threats. Requires documented medical necessity for stopping. Partial payment. Use only for safety concerns, not physician convenience or planned reductions.',
212, ARRAY['modifier 53', 'discontinued procedure', 'procedure stopped', 'complications']),

('general', 'modifiers', 'What is Modifier 76 vs Modifier 77?',
'Modifiers 76 and 77 indicate repeat procedures, differing by who performs: Modifier 76 (Repeat Procedure by Same Physician) - use when: same provider repeats procedure/service same day, clinical need for repeat, separate session or patient encounter. Modifier 77 (Repeat Procedure by Another Physician) - use when: different provider performs same procedure same day, clinical reason for repeat, often in hospital settings with multiple physicians. Common scenarios requiring repeat procedures: radiology studies repeated for technical issues or new findings, lab tests repeated for confirmation, diagnostic procedures repeated at different sites. Documentation requirements: reason for repeat, medical necessity, time interval between procedures, what changed requiring repeat. Payment: full payment for second procedure when medically necessary, payers may review for medical necessity. When NOT needed: planned multiple procedures (use modifier 51), staged procedures (use modifier 58), bilateral procedures (use modifier 50). Difference from 91: modifiers 76/77 are for any procedure, modifier 91 specific to diagnostic lab tests.',
'Modifier 76 = same physician repeats procedure same day. Modifier 77 = different physician repeats. Both require medical necessity documentation. Used for imaging, labs, diagnostic procedures. Differ from modifier 91 (lab repeat).',
213, ARRAY['modifier 76', 'modifier 77', 'repeat procedure', 'same day repeat']),

('general', 'modifiers', 'What is Modifier 22 (Increased Procedural Services)?',
'Modifier 22 indicates work required was substantially greater than typically required for the procedure. Use when: (1) Significantly increased complexity, (2) Significantly increased time, (3) Significantly increased effort, (4) Above and beyond typical procedure. Qualifying circumstances: extensive scarring, unusual anatomy, morbid obesity complicating access, unexpected findings increasing complexity, difficult patient factors. Documentation requirements: (1) Detailed operative report, (2) Specific description of increased complexity, (3) Comparison to typical procedure, (4) Additional time required, (5) Why increased difficulty was substantial. Payment: additional reimbursement above base code rate - typically 20-30% increase, requires manual review, must submit documentation with claim. Threshold: "substantially greater" typically means 20-25% more work - minor increases don''t qualify. When NOT to use: routine complications, normal anatomical variations, add-on codes available, separate code exists for complicated version. Example: routine cholecystectomy encounters severe adhesions requiring extensive lysis - bill 47600-22 with detailed operative note. Payer may request records before payment.',
'Modifier 22 indicates substantially greater work than typical procedure. Requires significant increased complexity/time/effort (20-25%+ more). Must submit detailed documentation. Additional payment 20-30%. Not for minor increases or routine complications.',
214, ARRAY['modifier 22', 'increased services', 'complex surgery', 'additional payment']);

-- GENERAL BILLING OPERATIONS FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'billing-operations', 'How often should claims be followed up?',
'Claim follow-up frequency recommendations: (1) 0-30 days: monitor for payment, check status at 14-21 days if no payment posted, (2) 31-60 days: initial follow-up contact with payer, investigate status, identify issues, (3) 61-90 days: aggressive follow-up, escalate unresolved claims, consider appeals if denied, (4) 90+ days: intensive follow-up, appeal denials, consider collections for patient balances. Electronic claims: typically adjudicated within 14-30 days, follow up at 21 days if no response. Paper claims: 30-45 day processing time, follow up at 35 days. Specific triggers for immediate follow-up: rejection notifications, denial notices, payer requests for additional information. Best practices: systematic follow-up schedule, prioritize high-dollar claims, track follow-up actions in system, establish payer contacts, use electronic claim status inquiries, document all follow-up activities. Delayed follow-up risks: timely filing violations, claims falling outside appeal windows, difficulty reconstructing services after time passes. Medtransic follows systematic protocols ensuring no claims overlooked.',
'Follow-up schedule: 14-21 days check status, 31-60 days initial contact, 61-90 days aggressive follow-up, 90+ days intensive action/appeals. Electronic claims typically pay 14-30 days. Systematic follow-up prevents lost revenue.',
220, ARRAY['claim follow-up', 'AR follow-up', 'when to follow up', 'claim status']),

('general', 'billing-operations', 'What is considered "old" A/R?',
'Accounts receivable "age" categories: (1) 0-30 days: current A/R - recently submitted claims awaiting payment, (2) 31-60 days: aging A/R - requiring attention, first follow-up, (3) 61-90 days: aged A/R - priority follow-up, denial management, (4) 91-120 days: old A/R - intensive follow-up, appeal deadlines approaching, (5) 120+ days: very old A/R - high risk of write-off, last opportunity for collection. Industry benchmarks: 0-30 days should be 60-70% of total A/R, 31-60 days should be 15-20%, 61-90 days should be 8-12%, 90+ days should be <10% of total A/R. Problems with old A/R: timely filing limits expired, appeal deadlines passed, difficult to obtain documentation, reduced collection likelihood, impacts cash flow. Causes of excessive old A/R: delayed claim submission, inadequate follow-up, unresolved denials, missing information, credentialing delays. Goal: minimize >90 day A/R - should be <10% total. Medtransic provides A/R cleanup services for practices with significant aged balances.',
'A/R age categories: 0-30 days (current), 31-60 (aging), 61-90 (aged), 90+ (old). Target: >60% in 0-30 days, <10% over 90 days. Old A/R risks write-off due to filing limits and appeal deadlines.',
221, ARRAY['aged A/R', 'old A/R', 'A/R aging', 'account age']),

('general', 'billing-operations', 'What KPIs should a practice track for A/R performance?',
'Critical A/R performance KPIs: (1) Days in A/R - average days from service to payment, target <40 days, calculated: (A/R balance / average daily charges), (2) Collection rate - percentage of charges collected, target >95%, calculated: (payments / allowed charges), (3) Clean claim rate - claims paid on first submission, target >95%, (4) Denial rate - percentage of charges denied, target <5%, (5) A/R aging percentages - distribution across age buckets, target >60% in 0-30 days, (6) Gross collection rate - actual collections vs total charges, target >60%, (7) Net collection rate - collections vs expected reimbursement, target >95-98%, (8) Cost to collect - operational costs / collections, target <5%, (9) First pass resolution rate - claims resolved without follow-up, target >90%, (10) Average time to resolve denials - target <30 days. Monthly monitoring: track trends over time, identify deterioration early, benchmark against industry standards. Medtransic provides detailed KPI reporting allowing practices to monitor revenue cycle health and identify improvement opportunities.',
'Key A/R KPIs: Days in A/R (<40), collection rate (>95%), clean claim rate (>95%), denial rate (<5%), aging distribution (>60% 0-30 days), net collection rate (>95-98%). Monthly monitoring identifies issues early.',
222, ARRAY['A/R KPIs', 'performance metrics', 'billing metrics', 'collection rate']),

('general', 'billing-operations', 'What are the most common billing errors?',
'Most frequent billing errors: (1) Patient demographics/insurance errors (30% of issues) - wrong name spelling, DOB, insurance ID, gender, address, (2) Missing prior authorization (15-20%) - services requiring auth provided without approval, (3) Incorrect or unsupported CPT codes (10-15%) - wrong code selection, codes not supported by documentation, (4) Diagnosis code errors (10%) - unspecified codes, invalid codes, missing codes, codes not supporting medical necessity, (5) Duplicate billing (5-8%) - same service billed multiple times, (6) Missing or incorrect modifiers (5-8%) - required modifiers omitted, wrong modifiers used, (7) Timely filing violations (5%) - claims submitted after filing deadline, (8) Credentialing issues (3-5%) - provider not enrolled, wrong provider number, (9) Coordination of benefits errors (3-5%) - wrong primary payer, missing secondary info. Prevention: robust front-end verification, systematic coding review, claim scrubbing technology, regular staff training, defined workflows. Medtransic''s technology and expertise minimize billing errors, achieving 95%+ clean claim rates.',
'Common billing errors: patient/insurance info wrong (30%), no authorization (20%), incorrect codes (15%), diagnosis errors (10%), duplicates (8%), missing modifiers (8%), late filing (5%). Prevention requires verification and scrubbing.',
223, ARRAY['billing errors', 'common mistakes', 'claim errors', 'billing mistakes']),

('general', 'billing-operations', 'How can medical billing errors be prevented?',
'Billing error prevention strategies: (1) Front-end verification - verify insurance at scheduling and check-in, confirm demographics accuracy, check authorization requirements, (2) Electronic eligibility - real-time verification before services, automated benefit checks, (3) Claim scrubbing - automated review before submission, NCCI edit checking, CPT/ICD-10 validation, (4) Coding review - certified coders review documentation, coding compliance audits, provider education on documentation, (5) Authorization management - tracking system for auth requirements, automated reminders, status monitoring, (6) Staff training - regular education on payer policies, coding updates, common error patterns, (7) Technology - practice management system with built-in edits, clearinghouse claim scrubbing, electronic claim submission, (8) Quality assurance - random claim audits, denial analysis, feedback loops, (9) Documentation improvement - provider templates with required elements, real-time documentation review, (10) Process standardization - defined workflows, checklists, policies. Result: 95%+ clean claim rates, <5% denial rates, faster payment. Medtransic implements all prevention strategies systematically.',
'Prevention strategies: front-end verification, real-time eligibility, claim scrubbing, coding review, authorization tracking, staff training, technology systems, QA audits, documentation improvement, standardized workflows. Achieves 95%+ clean rates.',
224, ARRAY['prevent errors', 'error prevention', 'reduce denials', 'billing accuracy']),

('general', 'billing-operations', 'What causes duplicate billing errors?',
'Duplicate billing causes: (1) Manual resubmission - claim resubmitted after already processed, (2) System errors - practice management system creates duplicate claims, (3) Multiple submissions - claim sent to payer via multiple routes (clearinghouse and portal), (4) Billing staff lack communication - different staff bill same services, (5) Claims not posted - payment received but not posted, appears unpaid, (6) Incorrect date of service - same service billed with different DOS, (7) Split billing - two providers bill same service, (8) Payer processing error - claim processed twice. Consequences: claim denial as duplicate, request for refund if overpaid, audit triggers, compliance concerns if pattern exists. Prevention: reconcile claims before submission, track claim submissions in PM system, post payments promptly, use batch claim scrubbing, establish workflow preventing re-submission without verification, train staff on checking claim status before re-billing, implement claim status inquiry before re-submission. Resolution: verify original claim status, submit corrected claim if original was error, refund if duplicate payment received, maintain clear records of submissions.',
'Duplicate billing causes: manual resubmission, system errors, multiple submission routes, poor communication, payments not posted. Prevention: track submissions, verify status before re-billing, post payments promptly, use scrubbing technology.',
225, ARRAY['duplicate billing', 'duplicate claims', 'claim already processed', 'duplicate error']);

