/*
  # Comprehensive Medical Billing FAQs - Batch 5
  
  ## Overview
  Adds 35+ comprehensive FAQs covering:
  - Insurance Verification & Eligibility (8 FAQs)
  - Prior Authorization (8 FAQs)
  - Compliance & Audits (6 FAQs)
  - Specialty Billing (5 FAQs)
  - Revenue Cycle Management (8 FAQs)
  
  Total: 35+ additional FAQs for comprehensive coverage
*/

-- INSURANCE VERIFICATION & ELIGIBILITY FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'insurance', 'What is insurance verification and why is it important?',
'Insurance verification is the process of confirming patient insurance coverage, benefits, and eligibility before services are provided. Critical for: (1) Confirming active coverage - ensures patient has valid insurance on service date, (2) Understanding benefits - copays, deductibles, coinsurance, out-of-pocket maximums, (3) Identifying coverage limitations - excluded services, frequency limits, visit caps, (4) Determining authorization requirements - services requiring pre-approval, (5) Confirming in-network status - provider participation, benefit levels. When to verify: at scheduling for new patients and procedures, before first visit, annually for established patients, when patient reports insurance changes, before expensive services/procedures. Information obtained: subscriber information, group/policy numbers, effective dates, coverage status, benefit details, authorization requirements, claims submission address. Methods: online payer portals (real-time), phone calls to payer, electronic eligibility verification (270/271 transactions), practice management system integrations. Benefits: prevents claim denials due to eligibility issues, sets correct patient financial expectations, identifies authorization needs early, reduces bad debt from uninsured services, improves revenue cycle efficiency. Failure to verify causes: denials for no coverage, patient balance surprises, authorization denials, payment delays.',
'Insurance verification confirms patient coverage, benefits, and eligibility before services. Prevents denials, identifies authorization needs, sets patient expectations. Verify at scheduling, annually, and before procedures. Use online portals, phone, or electronic transactions.',
300, ARRAY['insurance verification', 'eligibility check', 'verify coverage', 'insurance benefits']),

('general', 'insurance', 'What is the difference between eligibility and benefits verification?',
'Eligibility verification and benefits verification are related but distinct processes. Eligibility verification: confirms patient has active insurance coverage on specific date, verifies policy is in force and patient is covered member, basic information: coverage status (active/inactive), effective dates, termination dates, subscriber information. Benefits verification: detailed information about what insurance will pay for, specific coverage details: copay amounts, deductible (met/remaining), coinsurance percentages, out-of-pocket maximum, covered services, excluded services, visit limits, authorization requirements. Eligibility is preliminary check (patient has insurance), benefits is detailed investigation (what does insurance cover). Real-world difference: patient may have active insurance (eligible) but specific service may not be covered (benefits issue). When to perform: eligibility check at every visit (quick confirmation), benefits verification before scheduled procedures, expensive services, new patient visits, annually for established patients. Electronic transactions: 270 transaction requests eligibility/benefits, 271 transaction returns information, real-time results through clearinghouse. Best practice: always verify both - eligibility confirms basic coverage, benefits reveals financial responsibility and authorization needs.',
'Eligibility = patient has active insurance coverage. Benefits = detailed coverage information (copays, deductibles, covered services, limits). Eligibility is quick confirmation, benefits is detailed investigation. Verify eligibility every visit, benefits before procedures.',
301, ARRAY['eligibility vs benefits', 'benefits verification', 'insurance eligibility', 'coverage verification']),

('general', 'insurance', 'How do you verify Medicare eligibility?',
'Medicare eligibility verification methods: (1) Medicare.gov portal - free, real-time eligibility verification, requires HCFA User ID or I&A account, shows Part A/B effective dates, Part D enrollment, MSP information. (2) HIPAA Eligibility Transaction (270/271) - electronic verification through clearinghouse, automated integration with practice management systems, real-time or batch processing. (3) Interactive Voice Response (IVR) - call 1-800-MEDICARE, automated phone system, provides basic eligibility. (4) Medicare Administrative Contractor (MAC) - provider customer service line for specific MAC, representative-assisted verification. Information obtained: Medicare Part A effective date (hospital coverage), Part B effective date (outpatient/physician coverage), Medicare ID number (new MBI format), primary vs secondary coverage (MSP - Medicare Secondary Payer). Critical verifications: confirm patient has Part B (physician services), identify any primary insurance (MSP screening), verify enrollment in Medicare Advantage vs Original Medicare, confirm effective dates cover service date. MSP screening required: ask about employer coverage, liability/workers comp, end-stage renal disease, verify primary payer responsibility. Failure to identify MSP causes claim denials and requires refunds when Medicare paid incorrectly.',
'Verify Medicare eligibility via: Medicare.gov portal (free, real-time), 270/271 electronic transactions, 1-800-MEDICARE IVR, or MAC customer service. Confirm Part A/B coverage dates, MBI number, Medicare Secondary Payer status. MSP screening critical.',
302, ARRAY['Medicare verification', 'verify Medicare', 'Medicare eligibility', 'MSP screening']),

('general', 'insurance', 'What is Medicare Secondary Payer (MSP)?',
'Medicare Secondary Payer (MSP) refers to situations where Medicare is not primary payer and another insurance must pay first. Common MSP situations: (1) Working aged - patient 65+ with employer group health plan (20+ employees) through own or spouse employment, (2) Disability - disabled Medicare beneficiary with large group plan (100+ employees), (3) End-Stage Renal Disease (ESRD) - first 30 months of dialysis when patient has group health plan, (4) Liability insurance - accidents/injuries covered by liability, no-fault, or workers compensation insurance, (5) Veterans benefits - VA responsible for service-connected conditions. MSP questionnaire required: ask at each encounter, document responses, update when circumstances change. Billing implications: when MSP applies, bill primary insurance first, then bill Medicare as secondary, Medicare pays after primary pays/denies, failure to bill correctly causes denials, Medicare may conditionally pay then recover from responsible party. MSP violations: billing Medicare when other coverage should pay first, accepting Medicare payment when other payer primary, failing to investigate MSP situations. Penalties: providers must refund Medicare, face potential exclusion, civil monetary penalties up to $2,000 per violation. MSP screening tools: questionnaire in registration process, annual verification for established patients, ICD-10 external cause codes trigger MSP review.',
'MSP (Medicare Secondary Payer) = situations where other insurance pays before Medicare. Common: working aged, disability with group plan, ESRD first 30 months, liability/workers comp. Must screen at each visit, bill primary first. Violations require refunds and face penalties.',
303, ARRAY['MSP', 'Medicare Secondary Payer', 'Medicare coordination', 'primary insurance']);

-- PRIOR AUTHORIZATION FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'authorization', 'What services typically require prior authorization?',
'Services commonly requiring prior authorization: (1) Surgeries/procedures - especially elective, outpatient surgeries, pain management procedures, (2) Diagnostic imaging - MRI, CT, PET scans, nuclear medicine studies, (3) Durable medical equipment (DME) - power wheelchairs, hospital beds, CPAP, oxygen, (4) Specialty medications - biologics, specialty pharmacy drugs, injectable medications, (5) Genetic testing - molecular diagnostics, hereditary cancer panels, carrier screening, (6) Physical/occupational therapy - often after initial visits (10-20 visits), (7) Home health services - skilled nursing, home therapy, (8) Inpatient admissions - elective admissions, observation to inpatient conversions, (9) Pain management - epidural injections, nerve blocks, spinal cord stimulators, (10) Sleep studies - polysomnography, CPAP supplies after initial setup, (11) Bariatric surgery - weight loss procedures, (12) Mental health - intensive outpatient, partial hospitalization, residential treatment. Authorization requirements vary: by insurance company, by specific plan within company, by state and market, commercial vs Medicare Advantage. Determination methods: check payer website authorization lists, call payer provider services, use authorization lookup tools, verify during eligibility/benefits check. Consequences of no authorization: claim denial, provider financial responsibility (cannot balance bill patient), payment delays while obtaining retro-authorization.',
'Common services requiring authorization: surgeries, advanced imaging (MRI/CT/PET), DME, specialty drugs, genetic testing, therapy after initial visits, home health, pain procedures, sleep studies. Requirements vary by payer/plan. Check payer website or call. No authorization = denial.',
310, ARRAY['prior authorization', 'what requires authorization', 'pre-auth requirements', 'authorization needed']),

('general', 'authorization', 'How long does prior authorization take?',
'Prior authorization timeframes vary by urgency and payer: Standard authorization: (1) Most commercial payers - 3-5 business days typical, some up to 14 days allowed, (2) Medicare Advantage - 14 days for standard requests per CMS guidelines, (3) Medicaid - varies by state, typically 3-14 days. Expedited authorization: (1) Urgent situations threatening health - 72 hours for most payers, Medicare Advantage 72 hours required, medical necessity for expedited must be documented, (2) Emergency situations - some payers have 24-hour expedited process. Factors affecting timeline: completeness of initial request (incomplete requests delayed), medical records submission (having records ready speeds process), payer workload (longer during high-volume periods), complexity of case (may require peer-to-peer review). Improving speed: submit electronically when possible, include all required documentation initially, use payer-specific forms, follow up at 48-72 hours if standard request, maintain authorization tracking system. Deemed approved timelines: if payer doesn''t respond within mandated timeframe, request may be deemed approved per state/federal regulations, document all attempts to reach payer, some states require automatic approval after timeframe. Common delays: missing clinical documentation, insufficient medical necessity, need for peer-to-peer discussion, request submitted to wrong department.',
'Authorization timeframes: Standard 3-14 days (varies by payer), Expedited 72 hours (urgent), Emergency 24 hours. Medicare Advantage: 14 days standard, 72 hours urgent. Speed up: submit electronically, include all documentation, use payer forms, follow up at 48-72 hours.',
311, ARRAY['authorization timeline', 'how long authorization', 'pre-auth time', 'authorization processing']),

('general', 'authorization', 'What happens if services are provided without authorization?',
'Providing services without required authorization causes: (1) Claim denial - payer refuses payment entirely, denial code typically CO-197 or CO-50, no appeal possible if authorization truly required. (2) Provider financial responsibility - cannot bill patient for denied amount when authorization was provider responsibility, write-off required, contractual obligation in payer contract. (3) Exceptions when patient may be billed - patient signed valid ABN (Advance Beneficiary Notice) before service, patient was clearly informed of insurance requirements and chose to proceed, patient requested non-covered service, documented patient acknowledgment of financial responsibility. (4) Retroactive authorization attempts - some payers allow retro-authorization in specific circumstances (provider verified benefits and was misinformed, urgent/emergency situation, authorization requirement not published). (5) Appeal options - if authorization was verified as not required but claim denied, submit documentation of prior verification, representative name/date/reference number, payer error may allow payment. Prevention strategies: verify authorization requirements during eligibility check, use authorization management software, maintain authorization checklists by service type, track expiration dates, obtain authorization before scheduling when possible. Common scenarios: insurance verification shows no authorization needed but payer denies (appeal with verification documentation), patient seen urgently without time for authorization (request emergency retro-authorization), authorization obtained but expired before service date (obtain extension or new authorization).',
'Without authorization: claim denied (CO-197), provider cannot bill patient (write-off required), no appeal unless payer error. Exceptions: valid ABN signed, patient informed. May attempt retro-authorization if payer error, urgent situation. Prevention: verify requirements, track authorizations, obtain before scheduling.',
312, ARRAY['no authorization', 'without pre-auth', 'authorization denial', 'services without approval']),

('general', 'authorization', 'How do you track and manage prior authorizations?',
'Authorization tracking best practices: (1) Centralized tracking system - authorization log in spreadsheet or PM system, track authorization number, approved dates, expiration dates, approved CPT codes, approved units/visits, remaining visits. (2) Alert system - set reminders before expiration, flag when visits exhausted, alert scheduling when authorization needed, notification when new authorization required. (3) Documentation - scan authorization letter into patient chart, attach to patient account in PM system, make visible to schedulers and billing staff, note any limitations or special requirements. (4) Verification at scheduling - scheduler checks authorization status before booking, verifies procedure matches approved CPT codes, ensures sufficient remaining visits/units, confirms service date within authorization period. (5) Daily authorization report - list of patients scheduled requiring authorization verification, flag missing authorizations needing urgent attention, identify upcoming expirations. (6) Billing system integration - authorization details linked to claims, prevents claim submission without valid authorization, tracks authorization against visit counts. (7) Renewal process - identify authorizations nearing expiration 30 days in advance, proactive renewal submission before expiration, continue service without gap in coverage. Software solutions: practice management system authorization modules, dedicated authorization tracking software, clearinghouse authorization tools. Key metrics: percentage of services with timely authorization, authorization denial rate, average processing time, on-time renewal rate.',
'Track authorizations with: centralized log (auth number, dates, CPT codes, units), alert system for expirations, scanned letters in chart, verification at scheduling, daily authorization reports, PM system integration, proactive 30-day advance renewal. Prevent gaps and denials.',
313, ARRAY['track authorization', 'authorization management', 'manage pre-auth', 'authorization tracking system']);

-- COMPLIANCE & AUDIT FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'compliance', 'What is medical billing compliance?',
'Medical billing compliance means adhering to federal and state healthcare laws, regulations, and payer requirements when submitting claims and conducting billing operations. Key compliance areas: (1) Coding compliance - accurate CPT, ICD-10, and HCPCS code assignment per official guidelines, supported by documentation, no upcoding or unbundling. (2) Documentation compliance - services provided must be documented, documentation supports codes billed, signed and dated by rendering provider, meets medical necessity requirements. (3) Billing compliance - claims submitted with correct information, no duplicate billing, proper use of modifiers, timely filing met. (4) HIPAA compliance - patient privacy protected, secure transmission of PHI, proper authorizations for disclosures, business associate agreements in place. (5) Fraud and abuse prevention - no kickbacks or improper financial relationships (Stark Law, Anti-Kickback Statute), no billing for services not rendered, no inducements to patients. (6) Payer contract compliance - following contract terms, proper credentialing maintained, notification requirements met. Compliance program elements: written policies and procedures, training and education, internal monitoring and auditing, corrective action processes, reporting mechanisms. Consequences of non-compliance: claim denials, payment recoupment, civil monetary penalties, exclusion from federal programs, criminal charges for fraud.',
'Medical billing compliance = following healthcare laws and regulations when billing. Includes: accurate coding, proper documentation, correct claim submission, HIPAA privacy, fraud prevention. Requires written policies, training, auditing, corrective actions. Non-compliance risks denials, penalties, exclusion.',
320, ARRAY['billing compliance', 'compliance program', 'healthcare compliance', 'medical billing laws']),

('general', 'compliance', 'What is the difference between fraud and abuse in medical billing?',
'Fraud and abuse are both improper billing practices but differ in intent: FRAUD - intentional deception or misrepresentation to obtain payment, knowingly submitting false information, deliberate upcoding or billing for services not provided, intent to deceive is present. Fraud examples: billing for services not rendered, altering documentation to support higher codes, using another provider''s credentials, kickback schemes, waiving copays systematically to induce referrals. Fraud penalties: criminal prosecution possible, civil monetary penalties up to $50,000 per violation plus treble damages, exclusion from federal programs (Medicare/Medicaid), imprisonment up to 10 years for healthcare fraud. ABUSE - practices inconsistent with accepted medical/billing practices but lack fraudulent intent, may result from inadequate knowledge or careless practices, patterns of improper billing without proof of intent. Abuse examples: consistently coding higher than documentation supports without intent to defraud, excessive services not medically necessary, misuse of modifiers, improper balance billing. Abuse penalties: repayment of overpayments, civil monetary penalties (lesser than fraud), corrective action plans, increased audit scrutiny. Key difference: intent - fraud requires knowingly and willfully submitting false claims, abuse may be pattern of errors without fraudulent intent. Both are serious: even unintentional abuse patterns can lead to significant penalties, lack of compliance program doesn''t excuse abuse.',
'Fraud = intentional deception to obtain payment (billing for services not rendered, deliberate upcoding). Penalties: criminal charges, $50K per violation, exclusion, imprisonment. Abuse = improper practices without fraudulent intent (pattern of errors, inadequate knowledge). Penalties: repayment, lesser fines, corrective action. Key difference: intent.',
321, ARRAY['fraud vs abuse', 'medical billing fraud', 'healthcare abuse', 'fraudulent billing']),

('general', 'compliance', 'What should I do if I receive an audit request?',
'Steps when receiving audit request: (1) Don''t ignore it - respond by deadline, request extension if needed, ignoring leads to adverse determination. (2) Identify audit type - pre-payment review (before claim paid), post-payment review (after payment made), medical record request, comprehensive audit. (3) Review request carefully - what records are requested, audit timeframe, deadline for response, submission method. (4) Gather requested records - compile medical records for specified claims, ensure complete documentation, include all supporting documents, organize chronologically. (5) Review records before submission - ensure documentation supports codes billed, identify potential issues, consider whether to seek guidance, don''t alter or add to existing records. (6) Submit timely - meet stated deadline, confirm receipt of submission, keep copies of everything submitted, document submission date/method. (7) Prepare for extrapolation - in RAC audits, sample findings may be extrapolated to similar claims, understand extrapolation methodology, consider statistical review if extrapolated. (8) Consider professional help - coding expert review, legal counsel for significant audits, billing consultant familiar with audit processes. (9) Respond to findings - if overpayment determined, understand appeal rights, submit appeal if documentation supports, develop corrective action plan. What NOT to do: don''t alter medical records, don''t fabricate documentation, don''t ignore findings, don''t assume small sample means small impact (extrapolation risk). Prevention: maintain compliance program, conduct regular internal audits, ensure documentation quality.',
'When audited: respond by deadline (don''t ignore), identify audit type, review request carefully, gather complete records, review before submitting (don''t alter), submit timely with confirmation, prepare for extrapolation, consider expert help, respond to findings/appeal if appropriate. Don''t alter records or ignore.',
322, ARRAY['audit request', 'medical audit', 'RAC audit', 'chart audit', 'how to respond audit']),

('general', 'compliance', 'What is a Recovery Audit Contractor (RAC) audit?',
'Recovery Audit Contractors (RAC) are private companies contracted by CMS to identify and recover Medicare improper payments. RAC authority: review Medicare claims for overpayments and underpayments, conduct post-payment audits, use automated reviews and complex reviews, receive contingency fee (percentage of recoveries). RAC process: (1) Automated review - electronic review without medical records, identifies clear billing errors, (2) Complex review - requests medical records, reviews documentation supporting code selection, medical necessity, place of service. Record request limits: maximum number of records RACs can request per provider per 45 days (varies by provider size), additional documentation requests (ADR) count toward limit. Timeline: 45 days to submit medical records from request date, can request one 15-day extension. Potential outcomes: no change (claim correctly billed), overpayment determination (must repay with interest), underpayment (additional payment issued). Extrapolation: RAC may sample claims and extrapolate findings to larger population, significant financial impact possible, statistical validity can be challenged. Appeal process: 5 levels of Medicare appeals, redetermination (1st level, 43% overturn rate), reconsideration by QIC (2nd level), ALJ hearing (3rd level), Medicare Appeals Council (4th level), Federal Court (5th level). Defense strategies: ensure complete documentation submitted, highlight supporting documentation, consider statistical expert for extrapolation challenges, legal counsel for significant determinations.',
'RAC audits identify Medicare improper payments through automated and complex (medical record) reviews. 45-day response deadline. Can extrapolate sample findings. Outcomes: no change, overpayment (must repay), underpayment. Appeal through 5-level process if determination incorrect. Record request limits apply.',
323, ARRAY['RAC audit', 'Recovery Audit Contractor', 'RAC review', 'Medicare audit']);

-- REVENUE CYCLE MANAGEMENT FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'rcm', 'What is Revenue Cycle Management (RCM)?',
'Revenue Cycle Management (RCM) is the financial process healthcare providers use to manage administrative and clinical functions associated with claims processing, payment, and revenue generation. RCM encompasses entire patient encounter lifecycle: (1) Pre-registration - scheduling, insurance verification, prior authorization, (2) Registration - demographic collection, insurance capture, financial counseling, (3) Charge capture - documenting services provided, coding accurately, capturing all billable services, (4) Claim submission - clean claim creation, timely filing, electronic submission, (5) Payment posting - recording payments, applying to correct accounts, identifying underpayments, (6) Denial management - identifying denials, appealing, correcting, resubmitting, (7) Patient collections - billing patients, payment plans, collection activities, (8) Reporting - monitoring KPIs, identifying trends, continuous improvement. RCM goals: maximize revenue, minimize denied claims, reduce days in A/R, improve collection rates, enhance patient satisfaction. Technology in RCM: practice management systems, electronic health records integration, clearinghouse claim scrubbing, denial management software, patient payment portals, RCM analytics platforms. Effective RCM requires: trained staff, defined processes, technology utilization, continuous monitoring, denial prevention focus. Poor RCM results in: low collection rates, high denial rates, cash flow problems, aged A/R, staff frustration.',
'RCM (Revenue Cycle Management) is the complete financial process from patient registration through final payment. Includes: pre-registration, registration, charge capture, claim submission, payment posting, denial management, patient collections, reporting. Goal: maximize revenue, minimize denials, optimize cash flow.',
330, ARRAY['RCM', 'Revenue Cycle Management', 'revenue cycle', 'RCM process']),

('general', 'rcm', 'What is the biggest challenge in revenue cycle management?',
'The biggest RCM challenge varies by practice but common top challenges: (1) Claim denials - most significant revenue impact, average practice loses 5-10% revenue to denials, root causes: eligibility issues, authorization problems, coding errors, medical necessity, (2) Staff shortage and turnover - experienced billing staff difficult to find, training new staff expensive and time-consuming, knowledge loss when experienced staff leave, ongoing training needed for changing rules, (3) Payer complexity - each payer has different requirements, policies change frequently, portal navigation challenges, varying documentation requirements, (4) Prior authorization burden - time-consuming process, delays in care and payment, administrative burden on staff, authorization denials common, (5) Patient collections - high deductibles make patients responsible for more, difficulty collecting from patients, balance billing restrictions, patient payment plan management, (6) Technology challenges - disparate systems not integrated, manual processes prone to errors, staff resistance to new technology, expensive technology investments, (7) Regulatory compliance - constantly changing regulations, risk of penalties for non-compliance, HIPAA requirements, payer-specific requirements, (8) Aging A/R - difficulty collecting aged balances, timely filing limits prevent resubmission, writing off aged accounts. Solution approaches: denial prevention vs management, automation where possible, staff training investment, outsourcing considerations, technology optimization, focus on front-end processes (prevention).',
'Biggest RCM challenges: claim denials (5-10% revenue loss), staff shortage/turnover, payer complexity, prior authorization burden, patient collections (high deductibles), technology issues, regulatory compliance, aging A/R. Solutions: denial prevention, automation, training, outsourcing, front-end focus.',
331, ARRAY['RCM challenges', 'billing challenges', 'revenue cycle problems', 'billing issues']),

('general', 'rcm', 'Why should a practice outsource medical billing?',
'Reasons to outsource medical billing: (1) Cost savings - eliminate billing staff salaries/benefits (25-30% of practice expense), reduce office space needs, no technology/software investments, predictable monthly costs typically 4-8% of collections, (2) Expertise access - experienced certified coders, specialized payer knowledge, up-to-date on coding/regulatory changes, denial management expertise, (3) Improved collections - professional billing companies average 95-98% collection rates vs 85-90% for in-house, focus on denial prevention, aggressive A/R follow-up, specialized tools and technology, (4) Focus on patient care - physicians focus on medicine not billing, staff focus on patient experience, reduced administrative burden, less billing-related stress, (5) Scalability - easily scale with practice growth, no hiring/training when expanding, handle volume fluctuations, (6) Technology benefits - access to advanced billing software without investment, integrated clearinghouse services, robust reporting and analytics, practice management systems, (7) Reduced denials - professional scrubbing reduces denials, coding expertise prevents errors, authorization management, (8) Compliance assurance - outsourcing partners maintain compliance programs, regular audits, HIPAA compliance infrastructure, reduced audit risk. When outsourcing makes sense: high denial rates currently, staffing challenges, rapid growth, physician wants to focus on clinical work, struggling with cash flow. When to keep in-house: very small practice where control important, unique specialty requiring specific expertise, sufficient resources and expertise internally.',
'Outsource billing for: cost savings (eliminate staff/tech expenses), expertise access, improved collections (95-98% vs 85-90%), focus on patient care, easy scalability, advanced technology, reduced denials, compliance assurance. Typically 4-8% of collections. Makes sense with high denials, staffing issues, growth, cash flow problems.',
332, ARRAY['outsource billing', 'billing company', 'medical billing service', 'why outsource']),

('general', 'rcm', 'What is the clean claim rate and why does it matter?',
'Clean claim rate measures percentage of claims paid on first submission without errors, rejections, or denials. Calculation: (claims paid on first submission / total claims submitted) × 100. Industry benchmark: 95-98% clean claim rate considered good, below 90% indicates significant issues. Why it matters: (1) Cash flow impact - clean claims paid faster (14-30 days vs 60+ for denied claims), reduced days in A/R, predictable revenue stream, (2) Reduced rework costs - staff time for resubmission expensive, follow-up calls consume resources, appeals require extensive documentation, (3) Faster payment - first submission payment is quickest, denials delay payment 30-90+ days, some denials never collect, (4) Better payer relationships - payers favor providers with clean claims, reduced audit scrutiny, smoother processing, (5) Staff efficiency - less time fixing errors, more time on productive activities, reduced staff frustration. Improving clean claim rate: (1) Front-end prevention - thorough insurance verification, authorization management, accurate demographics, (2) Coding accuracy - certified coders, regular audits, ongoing education, coding software, (3) Claim scrubbing - automated edits before submission, clearinghouse scrubbing, NCCI edit checking, (4) Documentation - complete documentation before billing, provider education on requirements, (5) Staff training - regular updates on payer rules, coding changes, common denial patterns. Monitoring: track weekly/monthly, identify denial patterns, root cause analysis, continuous improvement focus.',
'Clean claim rate = claims paid on first submission without errors (target 95-98%). Matters because: faster payment (14-30 days vs 60+), reduced rework costs, better cash flow, improved payer relationships, staff efficiency. Improve via: verification, authorization, accurate coding, claim scrubbing, documentation, training.',
333, ARRAY['clean claim rate', 'first pass rate', 'claim acceptance', 'submission success']);

-- SPECIALTY BILLING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'specialty-billing', 'What makes orthopedic billing complex?',
'Orthopedic billing complexity factors: (1) Global surgical periods - 90-day global for major procedures, 10-day global for minor, understanding what''s included vs separately billable, modifier usage (24, 25, 57, 78, 79), (2) Surgical vs E/M coding - determining when E/M billable with procedure, appropriate modifier application, distinguishing significant separately identifiable services, (3) Fracture care billing - initial fracture care vs subsequent care, cast/splint application coding, global fracture care codes, (4) Joint injection billing - frequency limits by payer, bundling with E/M visits, documentation requirements, imaging guidance add-ons, (5) Implant billing - tracking implants separately, C-codes for ASC, use of HCPCS codes, facility vs physician billing, (6) Bilateral procedures - modifier 50 application, RT/LT modifiers, payer-specific billing rules, (7) Workers compensation - different coding requirements, authorization mandatory, specific forms required, often non-standard fee schedules, (8) DME related to orthopedics - braces, walkers, crutches, DMEPOS requirements, documentation needs. Common orthopedic denial reasons: fracture care bundling issues, missing modifiers on E/M same day as procedure, global period violations, implant coding errors, bilateral billing mistakes. Best practices: understand global period rules thoroughly, proper modifier use, separate documentation for separately billable services, track surgical cases for global period, DME documentation expertise.',
'Orthopedic billing complex due to: global surgical periods (90-day major, 10-day minor), surgical vs E/M coding decisions, fracture care billing rules, joint injection limits, implant tracking, bilateral procedures, workers comp requirements, DME coding. Requires modifier expertise, global period tracking, documentation.',
340, ARRAY['orthopedic billing', 'orthopedics coding', 'surgery billing', 'fracture care billing']),

('general', 'specialty-billing', 'Why is anesthesia billing different from other specialties?',
'Anesthesia billing unique characteristics: (1) Time-based payment - paid based on time units (15-minute increments in most states), start time = when anesthesiologist begins preparing patient, end time = patient transferred to recovery, (2) Base units - each CPT code has assigned base unit value (reflects procedure complexity), ranges from 3-20+ units, published in ASA Relative Value Guide, (3) Modifying units - additional units for patient physical status (P1-P6), qualifying circumstances (age, emergency, hypothermia), (4) Formula - Total units = Base units + Time units + Modifying units, Dollar amount = Total units × Conversion factor, Conversion factor varies by payer/location, (5) Physical status modifiers - P1 (normal healthy) through P6 (brain dead organ donor), affects unit calculation, must document supporting physical status, (6) Qualifying circumstances - 99100 (under 1 or over 70), 99116 (total body hypothermia), 99135 (controlled hypotension), 99140 (emergency), (7) Monitored anesthesia care (MAC) - different coding than general anesthesia, requires appropriate documentation, medical necessity critical, (8) Concurrent/medical direction rules - specific requirements when supervising CRNAs, medical direction up to 4 CRNAs, concurrent care different payment, documentation requirements specific. Common issues: time documentation accuracy, appropriate physical status selection, medical direction vs supervision documentation, MAC medical necessity.',
'Anesthesia billing unique: time-based payment (15-min units), base units per procedure (ASA guide), modifying units (physical status P1-P6, qualifying circumstances), formula = base + time + modifying units × conversion factor. Requires accurate time documentation, physical status justification, medical direction documentation.',
341, ARRAY['anesthesia billing', 'anesthesia coding', 'anesthesia time units', 'base units']),

('general', 'specialty-billing', 'What are the key challenges in behavioral health billing?',
'Behavioral health billing challenges: (1) Time documentation - psychotherapy codes are time-based, must document exact session time (start/end or total), insufficient time documentation causes denials, rounding errors common, (2) Medical necessity - extensive documentation required demonstrating necessity for therapy frequency/intensity, treatment plans with measurable goals, progress notes showing clinical necessity, (3) Diagnosis coding specificity - behavioral health requires specific diagnosis codes, rule-out diagnoses not payable, must use appropriate specifiers, (4) Visit limits - many payers limit therapy visits per year (20-52 visits common), authorization often required after initial visits, medical necessity review for extensions, (5) Provider credentialing - supervision requirements for unlicensed therapists, licensed provider credentials required, associate/intern billing rules, (6) Payer coverage variation - significant differences between commercial payers, Medicare Part B vs Medicare Advantage differences, Medicaid state variations, (7) Mental health parity compliance - payers must cover behavioral health similarly to medical, quantitative and qualitative treatment limitations, appeals when parity violated, (8) Telehealth nuances - behavioral health expanded telehealth permanently, audio-only billing for some services, state licensing considerations, (9) Add-on codes with E/M - psychotherapy add-on codes (90833/90836/90838) used with medical E/M, proper code selection critical, (10) Crisis services - unique coding for crisis situations, different time requirements, documentation intensity. Success factors: precise time documentation, robust clinical documentation, understanding payer-specific policies, credentialing compliance.',
'Behavioral health challenges: time documentation (exact minutes required), medical necessity (detailed documentation), diagnosis specificity, visit limits/authorizations, provider credentialing, payer variations, mental health parity, telehealth rules, add-on codes with E/M, crisis services. Requires precise documentation and policy knowledge.',
342, ARRAY['behavioral health billing', 'mental health billing', 'therapy billing challenges', 'psychology billing']);

