/*
  # EHR/EMR Advanced Workflow FAQs - Batch 9 Part 1
  
  ## Overview
  Adds 5 comprehensive EHR/EMR FAQs covering:
  - EHR template optimization for billing
  - Clinical documentation improvement (CDI)
  - Charge capture automation
  - EHR reporting and analytics  
  - EHR interoperability for claims
  
  SEO-optimized for EHR workflow and implementation.
*/

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'technology', 'How do I optimize EHR templates for better billing accuracy?',
'EHR template optimization directly impacts billing accuracy, compliance, and revenue - strategic design reduces denials by 30-50%: Template design must align with E/M documentation requirements capturing medical decision making (MDM) and time. MDM levels require documenting problem complexity, data reviewed, and risk management. Templates should incorporate CPT code-specific documentation requirements including procedure indications, consent, technique, and time tracking. Build in medical necessity support by linking diagnoses to procedures automatically and ensuring ICD-10 specificity. Streamline charge capture with auto-suggested procedure codes based on documentation content and chief complaint. Templates must enforce billing essentials as mandatory fields including diagnosis codes, referring provider NPI, authorization numbers, and place of service. Customize by specialty: primary care templates for wellness visits and chronic disease management, specialty care for procedure-oriented and consultation workflows, surgical specialties for pre/intra/post-operative documentation, mental health for psychotherapy time tracking. Technical implementation includes smart text macros, pick lists, auto-calculation of MDM scores, and clinical decision support with real-time prompts. Integrate workflow from registration through charge capture with seamless data flow. Ensure compliance through attestation requirements, complete audit trails, and annual template content reviews. Avoid pitfalls like over-templating with boilerplate text, auto-population without provider review, checkbox overload, and insufficient code specificity. Optimization process involves baseline assessment of current usage, redesign priorities for high-volume templates, iterative implementation with pilot users, and ongoing training. Success metrics include 20-30% documentation time reduction, improved charge capture, appropriate E/M level distribution in bell curve, and 30-50% denial rate reduction.',
'EHR template optimization reduces denials 30-50%: Align with E/M guidelines (capture MDM - problems, data, risk, time documentation, auto-calculate levels), include CPT-specific requirements (indication, technique, time), support medical necessity (auto-link diagnoses to procedures, ICD-10 specificity), streamline charge capture (auto-suggest codes, modifier prompts), enforce mandatory fields (diagnosis, NPI, authorization). Customize by specialty: primary care (wellness, chronic disease), surgical (pre/intra/post-op), mental health (time tracking). Features: smart text, auto-calculation, clinical decision support. Workflow integration from registration to charges. Compliance: attestation, audit trails, annual reviews. Avoid over-templating and cloning. Metrics: 20-30% time reduction, better charge capture, 30-50% fewer denials.',
477, ARRAY['optimize EHR templates', 'EHR billing accuracy', 'template design billing', 'EHR charge capture']);

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'technology', 'What is Clinical Documentation Improvement (CDI) and why does it matter?',
'Clinical Documentation Improvement (CDI) bridges clinical care and billing accuracy - increases revenue 8-15%: CDI systematically improves documentation quality to accurately reflect patient complexity, support appropriate code assignment, and ensure compliance. The process includes concurrent review during care with chart reviews and physician queries, retrospective review for pattern identification, provider education on documentation requirements, and compliant query management using open-ended non-leading questions. Key opportunities include ICD-10 specificity for diabetes type and complications, heart failure classification, CKD stages, and fractures. Capture comorbidities and complications including HCC coding for risk adjustment which affects capitation payments significantly. Ensure E/M level documentation supports codes with moderate MDM for 99214 including prescription management and chronic condition exacerbations. Document procedures separately with medical necessity clearly stated. CDI specialists typically RN or RHIT conduct chart reviews, issue physician queries, provide education, and track metrics. Coders assign codes based on documentation and provide feedback. Providers document accurately and respond to queries within 24-48 hours. Metrics include revenue increases from case mix index improvement and DRG optimization, operational efficiency with query response times under 48 hours, quality measures accuracy, and compliance with improved audit pass rates. Technology includes EHR integration with real-time review, computer-assisted coding with NLP, analytics for trending, and mobile tools for rounding. Best practices emphasize provider engagement, compliant queries only, ongoing education, metrics-driven processes, technology leverage, and multidisciplinary collaboration. Typical CDI programs cost $90-130K annually including specialist salary and software but return $500K-1.5M for hospitals and $50K-200K for practices with positive ROI within 6-12 months and ongoing 300-500% returns.',
'CDI improves documentation for 8-15% revenue increase: Systematic process improving accuracy to reflect patient complexity, support coding, ensure compliance. Process: concurrent review (daily chart review, physician queries, gap identification), retrospective review (patterns, feedback), education (requirements, specificity), compliant queries (open-ended, non-leading, 24-48hr response). Opportunities: ICD-10 specificity (diabetes type/complications, HF systolic/diastolic, CKD stage), comorbidities (HCC risk adjustment), E/M levels (99214 moderate MDM), procedures (medical necessity), capture complications. Roles: CDI specialist (RN/RHIT, chart review), coders (assign codes), providers (document, respond queries). Metrics: revenue (case mix, DRG), query response <48hrs, audit pass rate. Technology: EHR integration, NLP, analytics, mobile. ROI: 300-500% typical, positive 6-12 months.',
478, ARRAY['clinical documentation improvement', 'CDI billing', 'what is CDI', 'CDI program']);

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'technology', 'How can I automate charge capture to reduce missed charges?',
'Automated charge capture prevents 5-15% revenue leakage from missed charges: Common problems include procedures performed but not documented, documentation without charge entry, forgotten supply charges, and uncaptured time-based services costing practices $150K-500K annually. Automation strategies include EHR-integrated charge capture where template selections auto-generate charges with real-time suggestions at point of care. Mobile charge capture uses smartphone apps for rounding and procedures, voice-to-text entry, and photo documentation. Order-based charging links diagnostic tests and procedures to automatic charge generation when completed. Implant and device tracking with barcode scanning ensures 100% capture of high-value items costing $5K-50K. Time-tracking automation calculates critical care time, prolonged services alerts, and chronic care management when 20+ minutes reached. AI and machine learning use natural language processing to read notes and suggest CPT codes with pattern recognition learning from feedback. Charge reconciliation ensures completeness through schedule-to-charge daily checks, documentation-to-charge validation, order-to-charge matching, and supply-to-charge verification. Workflow best practices include provider responsibility for capturing charges at service time, billing staff secondary validation, daily charge reconciliation with no carry-over, and monthly audits. Key metrics are same-day charge entry over 95%, next day over 99%, and missed charge rate under 2%. Technology solutions include EHR platforms with integrated charging, standalone charge capture apps, AI-powered coding assistants, and revenue cycle management systems. Implementation involves current state assessment establishing baseline missed charge rate, solution selection based on compatibility and ROI, configuration with charge codes mapped and templates designed, comprehensive training, phased go-live with close monitoring, and ongoing optimization. Investment ranges $5K-100K but recovers $150K-500K+ annually with payback typically 6-12 months and ongoing 300-800% ROI.',
'Automate charge capture to prevent 5-15% revenue leakage: Strategies: (1) EHR-INTEGRATED: template selections auto-generate charges, real-time code suggestions, point-of-care capture, daily submission. (2) MOBILE: smartphone apps for rounding, voice-to-text, photo documentation. (3) ORDER-BASED: tests auto-charge when completed, procedure orders trigger charges, supply requisition creates charge. (4) IMPLANT TRACKING: barcode scanning for $5K-50K implants, RFID, supply chain integration. (5) TIME-TRACKING: critical care timer, prolonged services alert when threshold met, CCM 20+ min monitoring. (6) AI/ML: NLP reads notes suggests CPT codes, learns from coder feedback. (7) RECONCILIATION: schedule-to-charge daily, documentation-to-charge, order-to-charge. Workflow: provider captures at service time, billing validates, daily reconciliation, monthly audits. Metrics: same-day >95%, missed charges <2%. ROI: recover $150K-500K+ annually, payback 6-12 months, 300-800% ongoing.',
479, ARRAY['automate charge capture', 'missed charges', 'reduce revenue leakage', 'mobile charge capture']);

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES  
('general', 'technology', 'What EHR reports should I run regularly for billing optimization?',
'Strategic EHR reporting identifies opportunities and prevents losses: Essential reports include (1) Charge Lag Report showing delays between service and charge entry with targets of same-day over 95% and average under 0.5 days run daily for operations and monthly by provider. (2) Missing Charge Report identifying appointments without charges, documented procedures unbilled, and completed orders without billing run daily with immediate recovery action. (3) Coding Accuracy Report ensuring E/M level bell curve distribution, documentation scores supporting codes, and identifying under/overcoding run monthly per provider. (4) Denial and Rejection Report tracking denial rates under 5%, rejection rates under 3%, denial revenue amounts, and appeal success rates over 50% run weekly for operations. (5) AR Aging Report monitoring days in AR under 35 days target, AR over 90 days under 15%, prioritizing old balances for aggressive follow-up run weekly. (6) Medical Necessity Report ensuring diagnosis-procedure matching, authorizations obtained, and frequency compliance run weekly with claim holds for review. (7) Patient Balance Report tracking patient AR aging, collection rates over 70%, point-of-service collection emphasis run weekly. (8) Charge Capture Audit Report validating over 98% capture rate through monthly sample audits of 10-20 charts identifying systematic missed charges. (9) Modifier Usage Report ensuring appropriate modifier 25, 59, 50 application quarterly for compliance. (10) Payer Mix and Reimbursement Report analyzing revenue by payer, reimbursement rates, denial rates, and turnaround time quarterly for contracting decisions. Best practices include scheduled auto-generated reports distributed to stakeholders, dashboard visualization with KPI red/yellow/green indicators, actionable data driving decisions and tasks, trend analysis month-over-month, and benchmarking both internal provider comparisons and external industry standards. Implementation determines available built-in reports, identifies gaps requiring custom development, creates report schedule specifying frequency and recipients, establishes accountability for review and action, and enables continuous improvement refining metrics over time.',
'Essential EHR billing reports: (1) CHARGE LAG: same-day >95%, run daily, delays impact cash flow. (2) MISSING CHARGES: visits without charges, procedures unbilled, orders without billing - run daily for recovery. (3) CODING ACCURACY: E/M distribution bell curve, documentation score - run monthly. (4) DENIALS/REJECTIONS: <5% denial, <3% rejection, by reason - run weekly, appeal/prevent. (5) AR AGING: <35 days target, <15% over 90 days - run weekly, prioritize old AR. (6) MEDICAL NECESSITY: diagnosis-procedure match, authorization verification - run weekly, hold problematic claims. (7) PATIENT BALANCE: aging, 70% collection rate, point-of-service focus - run weekly. (8) CHARGE CAPTURE AUDIT: >98% capture, monthly sample 10-20 charts. (9) MODIFIER USAGE: 25/59/50 appropriate - quarterly review. (10) PAYER MIX: revenue by payer, reimbursement rates - quarterly for contracting. Best practices: scheduled auto-generation, dashboard KPI visualization, trend analysis, internal/external benchmarking.',
480, ARRAY['EHR billing reports', 'billing analytics', 'revenue cycle reports', 'EHR reporting']);

INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'technology', 'How do I ensure EHR interoperability for seamless claims processing?',
'EHR interoperability enables seamless data exchange critical for billing efficiency: Four levels exist - foundational for basic exchange, structural using HL7/X12/FHIR standardized formats, semantic with shared meaning via SNOMED/LOINC/RxNorm terminologies, and organizational with governance and policy. Billing-relevant interoperability includes (1) Eligibility Verification with real-time 270/271 transactions reducing denials 30-50% through instant insurance verification, accurate patient responsibility, and benefits confirmation before service. (2) Claims Submission using 837 professional/institutional HIPAA-compliant format with EHR integrated charge capture creating claims automatically, diagnosis-procedure linking, and clearinghouse scrubbing. (3) ERA/EFT Posting with 835 transactions auto-importing to match claims, post payments and adjustments automatically, and trigger secondary billing. (4) Claim Status Inquiry using 276/277 real-time tracking reducing phone calls and faster issue resolution. (5) Clinical Data Exchange via Health Information Exchange networks and FHIR patient access APIs supporting referral management, care transitions, and coordination. Standards include HL7 v2.x legacy widely used, HL7 FHIR modern API-based growing adoption, X12 EDI 5010 for HIPAA transactions, Direct Secure Messaging encrypted for clinical documents, and FHIR APIs for patient access. Implementation involves EHR selection requiring ONC Health IT certification, clearinghouse selection with robust payer connectivity and API integration, configuration of payer/provider setups and transaction enablement, comprehensive testing of claims and eligibility, and go-live monitoring with phased rollout. Troubleshooting addresses enrollment, configuration, format, and timing issues engaging clearinghouse, EHR vendor, and payer EDI support. Compliance requires HIPAA encryption in transit and at rest, business associate agreements, and patient consent per state laws. Future developments include 21st Century Cures Act prohibiting information blocking, prior authorization FHIR APIs automating processes, and predictive interoperability using AI for denial prevention. Benefits include efficiency with reduced manual tasks, accuracy with fewer errors, faster cash flow with reduced AR days, compliance with standardized processes, and improved patient satisfaction. ROI typically positive within 12 months from reduced labor, fewer denials, faster payment, and increased revenue capture.',
'EHR interoperability enables seamless billing: (1) ELIGIBILITY: real-time 270/271 instant coverage check reduces denials 30-50%. (2) CLAIMS: 837 electronic submission, auto-generation from charges, clearinghouse scrubbing, companion guide compliance. (3) ERA/EFT: 835 auto-import, claim matching, payment/adjustment posting, secondary billing triggered. (4) CLAIM STATUS: 276/277 real-time tracking reduces phone calls. (5) CLINICAL EXCHANGE: HIE, FHIR APIs, referral management, care coordination. Standards: HL7 (v2/FHIR), X12 EDI 5010, Direct messaging. Implementation: ONC-certified EHR, clearinghouse with payer connectivity, configuration (payer setup, NPI, transactions), testing, go-live monitoring. Troubleshooting: enrollment, configuration, format issues - engage clearinghouse/EHR/payer support. Compliance: HIPAA encryption, BAA, consent. Benefits: efficiency, accuracy, faster cash flow, compliance, patient satisfaction. ROI positive 12 months.',
481, ARRAY['EHR interoperability', 'electronic claims', 'HL7', 'X12 EDI', 'FHIR', 'eligibility verification', 'ERA posting']);
