/*
  # Additional Medical Billing FAQs - Batch 2
  
  ## Overview
  Adds 50+ more comprehensive FAQs covering:
  - Time-based CPT codes (6 FAQs)
  - Surgical coding (6 FAQs)
  - Radiology & Diagnostic (5 FAQs)
  - Physical Therapy & Chiropractic (7 FAQs)
  - Mental Health (6 FAQs)
  - Telehealth (5 FAQs)
  - Lab & Pathology (5 FAQs)
  - DME (5 FAQs)
  - Patient Billing (7 FAQs)
  - Credentialing (5 FAQs)
  - A/R Follow-up (7 FAQs)
  
  All optimized for SEO, featured snippets, and AEO.
*/

-- TIME-BASED CPT CODING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'time-based-codes', 'What are time-based CPT codes?',
'Time-based CPT codes require services to be provided for a minimum duration to bill the code. Common time-based codes include: physical therapy modalities (97110, 97112, 97140), psychotherapy services (90832-90837), care management services (99490, 99491), and prolonged services codes. Each time-based code specifies a time range (e.g., 97110 requires 15 minutes for one unit). Documentation must include start and stop times or total time spent. The 8-minute rule applies to therapy codes: 8-22 minutes = 1 unit, 23-37 minutes = 2 units, etc. Insufficient time documentation results in denials or downcoding. Time-based billing allows multiple units when time thresholds are met. Accurate time tracking and documentation are essential for compliance and proper reimbursement.',
'Time-based CPT codes require minimum service duration. Documentation must include time spent. Therapy codes use 8-minute rule: 8-22 min = 1 unit, 23-37 min = 2 units, etc.',
80, ARRAY['time-based codes', 'timed CPT', 'therapy time', '8-minute rule']),

('general', 'time-based-codes', 'How do 8-minute rules work for physical therapy?',
'The 8-minute rule determines therapy units billed based on total timed service minutes. Rules: 8-22 minutes = 1 unit, 23-37 minutes = 2 units, 38-52 minutes = 3 units, 53-67 minutes = 4 units. For mixed timed and untimed services: calculate total minutes for all timed codes, divide by 15 to determine total units available, allocate units to individual codes based on time spent. Example: 20 min therapeutic exercise (97110) + 25 min manual therapy (97140) = 45 total timed minutes = 3 billable units. Allocate: 97110 gets 1 unit (20/45 x 3 = 1.3 rounded down), 97140 gets 2 units (25/45 x 3 = 1.7 rounded down). Documentation must support time spent on each service. The 8-minute rule is Medicare policy adopted by most payers.',
'8-minute rule: 8-22 min = 1 unit, 23-37 = 2 units, 38-52 = 3 units. For multiple services, total timed minutes divided by 15 determines units, allocated proportionally.',
81, ARRAY['8-minute rule', 'therapy units', 'PT billing', 'time calculation']),

('general', 'time-based-codes', 'Which CPT codes follow the Medicare 8-minute rule?',
'Medicare 8-minute rule applies to timed physical medicine codes including: 97110 (Therapeutic Exercise), 97112 (Neuromuscular Reeducation), 97116 (Gait Training), 97140 (Manual Therapy), 97150 (Group Therapy), 97530 (Therapeutic Activities), 97535 (Self-Care Training), 97750 (Physical Performance Test), 97755 (Assistive Technology Assessment), 97760/97761 (Orthotic Management), 97763 (Prosthetic Training), and 92507/92508/92526 (Speech Therapy). Untimed codes (not subject to 8-minute rule): 97161-97164 (PT Evaluations), 97165-97168 (OT Evaluations), 97010-97039 (Modalities), 97605-97608 (Wound Care). Understanding which codes are timed versus untimed prevents billing errors and ensures compliant documentation.',
'Timed codes (8-minute rule): 97110, 97112, 97116, 97140, 97150, 97530, 97535, therapy speech codes. Untimed: evaluations (97161-97168), modalities (97010-97039), wound care.',
82, ARRAY['timed codes list', 'therapy codes', '8-minute rule codes', 'PT codes']),

('general', 'time-based-codes', 'Why was my timed therapy code denied for insufficient minutes?',
'Timed therapy code denials for insufficient minutes occur when: (1) Documentation shows less than 8 minutes per unit billed, (2) Start/stop times or total time not documented, (3) Time documented doesn''t support units billed per 8-minute rule, (4) Multiple procedures with insufficient combined time for units claimed, (5) Time includes non-billable activities (rest breaks, dressing/undressing, waiting). Prevention: document exact start/stop times or total minutes for each service, ensure time meets minimum thresholds before billing, exclude non-treatment time from calculations, use 8-minute rule calculator for multiple timed services, audit documentation before submission. Appeals require clear time documentation, service-by-service detail, and demonstration that time meets minimum requirements. Template documentation without specific times is insufficient.',
'Denials occur when documented time is less than 8 minutes per unit or time isn''t documented. Prevention requires specific start/stop times, proper 8-minute rule application, and excluding non-treatment time.',
83, ARRAY['insufficient minutes', 'time denial', 'therapy denied', 'not enough time']),

('general', 'time-based-codes', 'How do you calculate time for psychotherapy CPT codes?',
'Psychotherapy CPT codes are selected based on face-to-face time with patient: 90832 (16-37 minutes), 90834 (38-52 minutes), 90837 (53+ minutes). Time includes only direct patient contact for psychotherapy - excludes administrative tasks, documentation, or time with family members alone (unless family therapy codes used). When psychotherapy is provided same day as E/M, add-on codes apply: 90833 (with 90832), 90836 (with 90834), 90838 (with 90837). Documentation must specify: exact time spent in psychotherapy, start and end times or total duration, service elements provided (assessment, therapeutic intervention, crisis intervention). Billing wrong time-based code results in denials or downcoding. For split/shared visits with non-physician practitioners, time rules differ. Accurate time documentation prevents audit findings and supports medical necessity.',
'Psychotherapy code selection based on face-to-face time: 90832 (16-37 min), 90834 (38-52 min), 90837 (53+ min). Document exact time spent in direct therapy, excluding administrative tasks.',
84, ARRAY['psychotherapy time', 'therapy codes', '90834 90837', 'mental health time']),

('general', 'time-based-codes', 'What documentation is required for timed codes?',
'Timed code documentation must include: (1) Exact time spent - start/stop times or total minutes, (2) Service description - specific activities performed, (3) Body parts treated - anatomical areas for PT/OT, (4) Patient response - functional improvements or status, (5) Medical necessity - why service was provided, (6) Signature and credentials - treating provider identification. For therapy: document each timed service separately with individual times, describe specific exercises/techniques, note patient tolerance and progress. For psychotherapy: describe therapeutic interventions, patient engagement, topics addressed, clinical assessment. For care management: track total time across calendar month, document activities performed. Template documentation is insufficient - must include specific patient details and actual time. Missing time documentation causes automatic denials. Best practice: contemporaneous documentation at time of service prevents recall issues.',
'Required: exact time (start/stop or total), specific service description, body parts/areas treated, patient response, medical necessity, provider signature. Template documentation without specific times is insufficient.',
85, ARRAY['time documentation', 'timed code requirements', 'therapy documentation', 'time requirements']);

-- SURGICAL CODING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'surgical-coding', 'What is included in the global surgical period?',
'The global surgical period includes all services related to surgery: pre-operative care (1 day before major procedures, 0 days for minor), the surgical procedure itself, and post-operative care (0, 10, or 90 days depending on procedure). Global period services include: pre-op visits for surgery decision, surgery and anesthesia, normal post-op care, complications not requiring return to OR, post-op visits, dressings, suture removal, and routine follow-up. Services billable separately during globals (with appropriate modifiers): unrelated E/M services (modifier 24), return to OR for complications (modifier 78), staged procedures (modifier 58), unrelated procedures by same surgeon (modifier 79). 0-day globals: only surgery day included. 10-day globals: minor procedures with brief follow-up. 90-day globals: major surgeries with extended recovery. Understanding globals prevents unbundling and ensures compliance.',
'Global surgical period includes pre-op (day before major surgery), the surgery, and post-op care (0, 10, or 90 days). Normal follow-ups are included; unrelated services require modifiers.',
90, ARRAY['global period', 'surgical package', 'post-op', 'global surgery']),

('general', 'surgical-coding', 'Why are post-op visits denied when billed separately?',
'Post-operative visits are denied when billed separately because they''re included in the surgical global package. Denials occur when: (1) Visit is within global period for normal post-op care, (2) Modifier not used to indicate visit is unrelated to surgery, (3) E/M billed for routine post-op check, (4) Documentation doesn''t support separately billable service. Billable post-op scenarios: unrelated condition addressed during post-op period (use modifier 24), complication requiring return to OR (modifier 78), staged procedure during healing (modifier 58), new procedure unrelated to original surgery (modifier 79). Documentation must clearly show service is beyond normal post-op care or unrelated to surgical procedure. Routine wound checks, dressing changes, and expected follow-ups are included in global payment and cannot be separately billed.',
'Post-op visits are denied because they''re included in surgical global payment. To bill separately, use appropriate modifiers (24, 78, 58, 79) and document service is unrelated or beyond normal care.',
91, ARRAY['post-op denied', 'global period denial', 'surgical follow-up', 'post-operative']),

('general', 'surgical-coding', 'What procedures require modifier 58 or 78?',
'Modifier 58 indicates staged/related procedure during post-op period - planned, more extensive, or therapeutic follow-up. Use when: procedure was planned prospectively, procedure is more extensive than original, procedure represents therapy following diagnostic procedure. Starts new global period. Modifier 78 indicates unplanned return to OR for complication during post-op period. Use when: complication requires return to surgery, procedure performed by same surgeon, complication is related to original surgery. Does not start new global period - continues original global. Key differences: 58 is planned/staged (separate global), 78 is unplanned complication (same global). Examples: Modifier 58 - debridement after cancer excision as planned staged procedure. Modifier 78 - return to OR for bleeding after original surgery. Documentation must clearly indicate whether procedure was planned (58) or unplanned complication (78).',
'Modifier 58: staged/related procedure during post-op period (planned, starts new global). Modifier 78: return to OR for complication (unplanned, same global). Documentation must justify planned vs unplanned.',
92, ARRAY['modifier 58', 'modifier 78', 'return to OR', 'staged procedure']),

('general', 'surgical-coding', 'What are add-on surgery CPT codes?',
'Add-on CPT codes represent additional services performed with primary procedures and cannot be billed alone. Designated with "+" symbol in CPT book and "ZZZ" global indicator. Add-on codes are: exempt from modifier 51 (multiple procedure), paid at 100% (no reduction), reported in addition to primary code, and subject to specific code pairing rules. Common surgical add-on codes: +22614 (each additional vertebral segment), +35700 (reoperation for bypass patency), +43273 (endoscopic additional lesion), +11732 (each additional skin graft), +15001 (each additional burn dressing). Documentation must support both primary and add-on procedures. Add-on codes are typically billed per unit for "each additional" services. Incorrectly billing add-on codes alone causes denials. Check NCCI edits for appropriate code pairings. Add-on codes simplify billing complex procedures with multiple components.',
'Add-on codes (marked with "+") represent additional services performed with primary procedures. Cannot be billed alone, paid at 100%, exempt from modifier 51. Common in spinal, vascular, and extensive surgeries.',
93, ARRAY['add-on codes', 'additional procedure', 'surgical add-on', 'plus symbol codes']),

('general', 'surgical-coding', 'When should multiple procedure modifier 51 be used?',
'Modifier 51 indicates multiple procedures performed during same surgical session and is appended to secondary procedure codes (not primary). Most payers reduce payment for additional procedures: 100% for primary procedure, 50% for second procedure, 50% for additional procedures. Use modifier 51 when: billing multiple surgical procedures same session, procedures have different CPT codes, procedures not bundled per NCCI edits. Do not use modifier 51 for: add-on codes (+codes), modifier 51 exempt procedures (check CPT appendix), E/M services with modifier 25, bilateral procedures with modifier 50. Medicare and many payers apply modifier 51 automatically via claims processing - manual modifier 51 not required. However, some payers require manual modifier 51 on secondary procedures. Documentation must support each procedure was distinct and medically necessary. Understanding modifier 51 rules prevents payment reductions and denials.',
'Modifier 51 indicates multiple procedures same session. Applied to secondary procedures (not primary). Payment typically: 100% primary, 50% additional. Don''t use with add-on codes or modifier 51-exempt procedures.',
94, ARRAY['modifier 51', 'multiple procedures', 'multiple surgery', 'secondary procedure']),

('general', 'surgical-coding', 'Why was my surgical CPT code denied as inclusive?',
'Surgical codes are denied as "inclusive" when payers determine the service is bundled into another code billed. Common inclusive denials: (1) Component billed separately when comprehensive code exists, (2) NCCI bundling - codes shouldn''t be billed together, (3) Services included in global surgical package, (4) Pre-op/post-op services billed separately without modifier, (5) Approach/closure billed separately from main procedure. Prevention: check NCCI edits before billing, use comprehensive codes when available, understand global surgical packages, append appropriate modifiers when services are truly distinct (59, XE, XS, XP, XU), verify payer-specific bundling policies. Appeals require: documentation showing procedures were distinct, different anatomical sites, separate sessions, or clinically appropriate to bill separately, proper modifier usage justification. Many inclusive denials are correct per coding guidelines - verify coding accuracy before appeal.',
'Inclusive denials occur when services are bundled into other codes per NCCI edits or global packages. Prevention: check bundling rules, use modifiers for distinct services, understand global periods.',
95, ARRAY['inclusive denial', 'bundling denial', 'included service', 'NCCI bundling']);

-- RADIOLOGY & DIAGNOSTIC FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'radiology', 'What is the difference between CPT 71045 and 71046?',
'CPT 71045 is chest X-ray single view while 71046 is chest X-ray 2 views. Key differences: 71045 - typically AP or PA view only, lower reimbursement, limited clinical information. 71046 - typically PA and lateral views, higher reimbursement, provides more comprehensive evaluation. Medical necessity and physician order determine appropriate code. 71046 is standard for most chest X-ray indications. Billing 71046 when only single view performed is incorrect coding. Billing 71045 when two views ordered and performed is undercoding. Documentation must specify number of views taken and medical necessity. Some facilities have protocols for when single vs two-view studies are appropriate. Insurance may require authorization for certain radiology services regardless of number of views.',
'71045 = chest X-ray single view (AP or PA). 71046 = chest X-ray 2 views (PA and lateral). Code selection must match views actually performed and documented. 71046 provides more complete evaluation.',
100, ARRAY['chest X-ray', '71045', '71046', 'X-ray views', 'radiology codes']),

('general', 'radiology', 'What is CPT 93000 vs 93005?',
'CPT 93000 is complete EKG service including tracing, interpretation, and report (global service). CPT 93005 is only the EKG tracing (technical component). Additional component codes: 93010 (interpretation and report only - professional component). Use 93000 when provider performs complete service (tracing and interpretation). Use 93005-TC when billing for equipment/technician only. Use 93010-26 when billing for physician interpretation only (reading done elsewhere). Component billing common in: hospital outpatient departments (facility bills technical, physician bills professional), mobile EKG services, or when services split between entities. Global billing (93000) used when single entity performs both components. Billing both global and components causes duplication denials. Facility settings require understanding of split billing rules and appropriate POS codes.',
'93000 = complete EKG (global: tracing + interpretation). 93005 = tracing only (technical component). 93010 = interpretation only (professional component). Use global code when same provider does both.',
101, ARRAY['EKG codes', '93000', '93005', 'electrocardiogram', 'EKG billing']),

('general', 'radiology', 'What is the difference between TC and 26 for radiology?',
'Modifier TC (Technical Component) represents equipment, supplies, and technical staff costs. Modifier 26 (Professional Component) represents physician interpretation, supervision, and reporting. Total reimbursement = TC + 26 components. Use TC: when facility provides equipment/technician but not interpretation (hospital bills TC, radiologist bills 26 separately). Use 26: when physician interprets study performed elsewhere (reading films from another facility). Use global (no modifier): when same entity provides both components. Example: Hospital performs and bills 71046-TC (chest X-ray technical). Radiologist bills 71046-26 (interpretation). Together equals global service. Component billing allows appropriate payment allocation between facilities and interpreting physicians. Billing global when only one component provided causes overpayment. Billing both global and components causes duplicate denial.',
'TC modifier = technical component (equipment/staff). Modifier 26 = professional component (interpretation). Total payment = TC + 26. Use component billing when services split between entities.',
102, ARRAY['modifier TC', 'modifier 26', 'technical component', 'professional component', 'radiology billing']),

('general', 'radiology', 'Why are X-ray claims denied for missing modifiers?',
'X-ray claims deny for missing modifiers when: (1) Component billing required but global code used (hospital setting), (2) Bilateral procedure performed without modifier 50 or LT/RT, (3) Multiple views billed without 26/TC when appropriate, (4) Same provider bills both TC and 26 without specifying components. Common scenarios: hospital outpatient radiology must bill TC, physicians must bill 26 for interpretations, bilateral studies require modifier 50 or anatomical modifiers (LT/RT), repeat studies same day require modifier 76 or 77. Prevention: understand facility vs non-facility billing rules, verify when component billing is required, use bilateral/anatomical modifiers appropriately, check payer-specific modifier requirements. Appeals require: documentation supporting component billed, clarification of who performed technical vs professional services, proper modifier justification. Modifier requirements vary by payer and setting.',
'X-ray denials for missing modifiers occur in component billing (TC/26 required), bilateral procedures (need 50/LT/RT), or repeat studies (need 76/77). Requirements vary by setting and payer.',
103, ARRAY['X-ray denied', 'radiology denial', 'missing modifier', 'TC 26 required']);

-- Due to length constraints, I''ll continue with more categories in the response.
-- Adding PT/Chiro, Mental Health, Telehealth, Labs, DME, Patient Billing, Credentialing, and A/R

-- PHYSICAL THERAPY & CHIROPRACTIC FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'pt-chiro', 'What are the most used PT codes?',
'Most commonly used physical therapy CPT codes: 97110 (Therapeutic Exercise - strengthening, ROM, flexibility), 97112 (Neuromuscular Reeducation - balance, coordination, proprioception), 97140 (Manual Therapy - soft tissue work, mobilization), 97530 (Therapeutic Activities - dynamic functional activities), 97161-97163 (PT Evaluations - low, moderate, high complexity), 97035 (Ultrasound), 97110 (Electric Stimulation), 97014 (Electrical Stimulation). Timed codes (97110, 97112, 97140, 97530) follow 8-minute rule. Evaluation codes billed once per episode or after extended discharge. Modality codes often have limited coverage or require bundling with manual codes. Documentation must support medical necessity, functional goals, and progress. Overuse of high-paying codes (97140) triggers audits. Balanced code selection reflecting actual treatment provided prevents scrutiny.',
'Most used PT codes: 97110 (exercise), 97112 (neuromuscular reeducation), 97140 (manual therapy), 97530 (therapeutic activities), 97161-97163 (evaluations). Timed codes follow 8-minute rule.',
110, ARRAY['PT codes', 'physical therapy codes', '97110 97112', 'therapy billing']),

('general', 'pt-chiro', 'What is the difference between 97110 and 97530?',
'97110 (Therapeutic Exercise) focuses on: strength, ROM, endurance, flexibility - typically isolated muscle groups or specific movements. Activities: resistance bands, weights, stretching, basic exercises. 97530 (Therapeutic Activities) involves: dynamic functional training combining multiple movements, task-specific activities, return-to-function focus. Activities: lifting mechanics, job simulation, sports-specific movements, ADL training. Key distinction: 97110 is component-based exercise, 97530 is functional activity-based. Both are timed codes (8-minute rule applies). Many payers scrutinize 97530 for medical necessity - must document functional deficits and how activities address them. Some payers have frequency limits or require 97530 as "add-on" to 97110. Documentation must clearly differentiate which code applies based on activity complexity and functional nature.',
'97110 = therapeutic exercise (strength, ROM, flexibility) - component-based. 97530 = therapeutic activities (functional, dynamic, task-specific) - activity-based. Both timed codes but 97530 requires stronger functional justification.',
111, ARRAY['97110 vs 97530', 'therapeutic exercise', 'therapeutic activities', 'PT codes']),

('general', 'pt-chiro', 'Why was CPT 97140 denied as inclusive?',
'CPT 97140 (Manual Therapy) is frequently denied as inclusive because: (1) Many payers consider it included in 97110 evaluation/exercise without clear distinction, (2) Performed same session as 97110/97112 without distinct documentation, (3) Time overlaps with other timed services, (4) Considered "maintenance" rather than skilled therapy, (5) Billed every visit without documented need. Prevention: document specific manual therapy techniques (joint mobilization, soft tissue mobilization, manual traction - not just "massage"), show medical necessity for manual techniques separate from exercise, document patient response and functional improvement, vary treatment codes based on actual treatment provided (don''t bill 97140 every visit), ensure time allocated properly under 8-minute rule. Some payers limit 97140 to certain diagnoses or require modifier 59 for same-session billing. Understanding payer-specific policies prevents denials.',
'97140 denials occur when considered included in other services, lacks distinct documentation, or deemed maintenance care. Prevention requires documenting specific techniques, medical necessity, and separate time.',
112, ARRAY['97140 denied', 'manual therapy', 'inclusive denial', 'PT denial']),

('general', 'pt-chiro', 'What is CPT 98940 vs 98941 (Chiropractic)?',
'Chiropractic manipulation codes differ by spinal regions treated: 98940 (1-2 regions), 98941 (3-4 regions), 98942 (5 regions). Spinal regions: cervical, thoracic, lumbar, sacral, pelvic. Documentation must specify each region manipulated. Cannot bill multiple manipulation codes same visit (98940 and 98941 together). Select appropriate code based on total regions. Extraspinal manipulation coded separately (98943). Some payers have frequency limits (visits per year or per condition). Medical necessity requires demonstrating subluxation or biomechanical dysfunction. X-rays may be required for certain diagnoses. Maintenance care typically not covered. Documentation must include: examination findings, regions treated, technique used, patient response, functional improvement. Undercoding (billing 98940 when 3+ regions treated) loses revenue. Overcoding without documentation triggers audits.',
'Chiropractic manipulation codes by spinal regions: 98940 (1-2 regions), 98941 (3-4 regions), 98942 (5 regions). Document each region manipulated. Cannot bill multiple codes same visit - select appropriate code.',
113, ARRAY['98940 98941', 'chiropractic codes', 'CMT codes', 'spinal manipulation']),

('general', 'pt-chiro', 'Why is manual therapy (97140) often denied?',
'Manual therapy (97140) denials occur frequently due to: (1) Insufficient documentation - generic statements like "manual therapy provided" without technique specifics, (2) Medical necessity questioned - appears to be maintenance or comfort care, (3) Frequency limits - billed every visit without justification, (4) Bundling - considered inclusive with evaluation or exercise codes, (5) Diagnosis doesn''t support - no documented biomechanical dysfunction, (6) Time issues - insufficient time documented under 8-minute rule. Successful billing requires: documenting specific techniques (joint mobilization grades, soft tissue mobilization methods, manual traction parameters), establishing medical necessity with measurable deficits, demonstrating skilled therapy (not maintenance), varying treatment based on clinical need, supporting with progress toward functional goals. Some payers require pre-authorization for manual therapy. Understanding payer policies and thorough documentation are critical.',
'97140 denials due to vague documentation, medical necessity concerns, frequency issues, or bundling. Prevention: document specific techniques, establish necessity with measurable deficits, demonstrate skilled care and progress.',
114, ARRAY['97140 denied', 'manual therapy denied', 'why denied', 'PT denials']);

-- Continue with remaining categories due to length...
-- Adding more batches for Mental Health, Telehealth, Labs, DME, Patient Billing, etc.

