/*
  # Top Important CPT Codes FAQs
  
  ## Overview
  Adds 30+ FAQs covering the most commonly searched and used CPT codes:
  - E/M Visit Codes (99202-99215)
  - Preventive Visit Codes (99381-99397)
  - Common Procedure Codes
  - Specialty-Specific Codes
  - HCPCS Codes
  
  These are highly searched codes that will improve SEO and user engagement.
*/

-- E/M VISIT CODES
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'em-coding', 'What is CPT 99202-99205 (New Patient Visit)?',
'CPT codes 99202-99205 describe new patient office/outpatient evaluation and management visits of varying complexity. New patient definition: individual who has not received professional services from provider or same specialty/subspecialty within past 3 years. Code selection based on: Medical Decision Making (MDM) complexity OR total time spent on date of encounter. Levels: 99202 (straightforward MDM, 15-29 minutes), 99203 (low complexity MDM, 30-44 minutes), 99204 (moderate complexity MDM, 45-59 minutes), 99205 (high complexity MDM, 60-74 minutes). MDM components: number/complexity of problems addressed, amount/complexity of data reviewed, risk of complications/morbidity/mortality. Time includes: face-to-face and non-face-to-face time on date of service (preparing to see patient, obtaining history, performing exam, counseling, documenting). Documentation requirements: chief complaint, history, exam, MDM or time, diagnosis codes. Cannot bill new patient code if seen within 3 years - use established patient codes instead.',
'99202-99205 are new patient office visits (patient not seen in 3 years). Selected by MDM complexity or time: 99202 (15-29 min), 99203 (30-44 min), 99204 (45-59 min), 99205 (60-74 min). Document MDM or time.',
15, ARRAY['99202', '99203', '99204', '99205', 'new patient visit', 'new patient E/M']),

('general', 'em-coding', 'What is CPT 99211-99215 (Established Patient Visit)?',
'CPT codes 99211-99215 describe established patient office/outpatient E/M visits. Established patient: received professional services from provider or same specialty within past 3 years. Code selection based on MDM complexity OR total time. Levels: 99211 (may not require physician presence, minimal services, 0 minutes documented), 99212 (straightforward MDM, 10-19 minutes), 99213 (low complexity MDM, 20-29 minutes), 99214 (moderate complexity MDM, 30-39 minutes), 99215 (high complexity MDM, 40-54 minutes). 99211 unique: typically nurse visits, medication refills, BP checks - may not require physician though payment reduced if non-physician. MDM same as new patient codes: problems addressed, data reviewed, risk. Time counted same as new patient: total time on date of encounter. Documentation: chief complaint (except 99211), interval history, exam, MDM or time. Most commonly billed codes: 99213 (routine follow-up) and 99214 (complex chronic disease management). Proper code selection prevents under/overcoding.',
'99211-99215 are established patient visits (seen within 3 years). Selected by MDM or time: 99211 (nurse visit), 99212 (10-19 min), 99213 (20-29 min), 99214 (30-39 min), 99215 (40-54 min). Most common: 99213, 99214.',
16, ARRAY['99211', '99212', '99213', '99214', '99215', 'established patient', 'follow-up visit']),

('general', 'em-coding', 'What is CPT 99381-99397 (Preventive Visit)?',
'CPT codes 99381-99397 describe preventive medicine services (annual wellness exams, physicals, well-child checks). Age-based code selection: 99381-99387 (new patients), 99391-99397 (established patients). Age ranges: infant (<1 year), early childhood (1-4), late childhood (5-11), adolescent (12-17), young adult (18-39), adult (40-64), 65+. Services included: comprehensive history, comprehensive exam, counseling/anticipatory guidance, risk factor reduction interventions, age/gender appropriate screenings. Key differences from E/M codes: focus on prevention not problem management, distinct codes based on age not complexity, cannot bill both preventive and problem E/M same visit without modifier 25. Billing same visit as problem E/M: use modifier 25 on E/M code (99213-25 or 99214-25) when significant separately identifiable problem addressed. Documentation: comprehensive review of systems, past/family/social history, complete exam, counseling topics, preventive screenings ordered. Common denial: lack of modifier 25 when billing problem visit same day. Many payers cover preventive visits 100% per ACA requirements.',
'99381-99397 are preventive visits (wellness exams, physicals). Age-based selection. New: 99381-99387, Established: 99391-99397. Age ranges: infant to 65+. Cannot bill with problem E/M same visit unless significant problem addressed with modifier 25.',
17, ARRAY['99381', '99391', '99384', '99394', 'preventive visit', 'annual physical', 'wellness exam', 'well-child']),

('general', 'em-coding', 'What is CPT 99281-99285 (Emergency Department Visit)?',
'CPT codes 99281-99285 describe emergency department evaluation and management services. Level selection based on MDM complexity (not time for ED visits). Levels: 99281 (straightforward MDM - minor problems), 99282 (low complexity MDM), 99283 (moderate complexity MDM), 99284 (high complexity MDM - severe symptoms), 99285 (high complexity MDM - immediate threat to life/function). MDM elements: problems addressed/evaluated, amount/complexity of data reviewed/analyzed, risk of complications. ED-specific considerations: urgency doesn''t determine level (minor urgent issue may be lower level), acuity and medical necessity drive code selection, facility and professional components (facility bills facility fee, physician bills professional component). Cannot bill: same provider E/M same day in office then ED (ED only), critical care time (use 99291/99292 if criteria met), observation services separately (included unless separately documented). Documentation: presenting problem, history appropriate to clinical situation, exam, MDM, time not required. Common issues: overcoding based on urgency vs complexity, insufficient MDM documentation. Facility typically bills higher levels than professional due to resource utilization.',
'99281-99285 are emergency department E/M visits. Selected by MDM complexity (not time): 99281 (minor), 99282 (low), 99283 (moderate), 99284 (high/severe), 99285 (high/life-threatening). Level based on medical complexity, not urgency.',
18, ARRAY['99281', '99282', '99283', '99284', '99285', 'emergency visit', 'ED visit', 'ER visit']);

-- COMMON PROCEDURE CODES
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'procedures', 'What is CPT 20610 (Joint Injection)?',
'CPT 20610 describes arthrocentesis (joint aspiration) or injection of major joint or bursa (shoulder, hip, knee, subacromial bursa). Includes: accessing joint space, aspiration of fluid if present, injection of therapeutic substance (corticosteroid, hyaluronic acid, anesthetic). Components: physician work of accessing joint, may bill medication separately (J-code for injectable drug). Code selection: 20610 (major joint: shoulder, hip, knee, subacromial bursa), 20605 (intermediate joint: elbow, wrist, ankle), 20600 (small joint: fingers, toes). Cannot bill bilaterally with modifier 50 - bill each injection separately. Documentation requirements: medical necessity (pain, inflammation, synovitis), joint accessed, medications injected with dosage, patient response. Supplies: use A4550 (surgical tray) if sterile tray used. Common denials: frequency limits (some payers limit to 3-4 injections per joint per year), insufficient medical necessity, wrong joint size code, missing J-code for medication. Medicare reimburses procedure and medication separately. Ultrasound guidance: if used, bill 20611 or add-on codes.',
'CPT 20610 is major joint injection/aspiration (shoulder, hip, knee). Includes accessing joint and injecting medication. Bill medication separately with J-code. Cannot bill bilaterally - bill each side separately. Document joint, medication, medical necessity.',
50, ARRAY['20610', 'joint injection', 'knee injection', 'cortisone shot', 'steroid injection']),

('general', 'procedures', 'What is CPT 93000 (EKG/ECG)?',
'CPT 93000 describes complete electrocardiogram (EKG/ECG) including tracing, interpretation, and report (global service). Components: 93005 (tracing only - technical component), 93010 (interpretation and report - professional component). Use 93000 when: same provider/facility performs both tracing and interpretation, office or outpatient setting, provider owns equipment. Use component codes when: services split between entities (hospital performs tracing, physician interprets), mobile EKG service. Modifiers: 93005-TC (technical component only), 93010-26 (professional component only). Documentation: interpretation note including: rhythm, rate, intervals, axis, ST/T wave abnormalities, comparison to previous if available, signature. Medical necessity: symptoms (chest pain, palpitations, syncope), monitoring (medication, chronic conditions), pre-operative clearance, screening per guidelines. Common denials: duplicate billing (both global and components), screening without covered indication, frequency limits (routine screening limited to specific intervals), bundled with other services. Medicare frequency: annually for high-risk patients, routine screening generally not covered. Billing duplicate: cannot bill 93000 AND 93005 or 93010 same encounter.',
'93000 is complete EKG including tracing and interpretation (global). 93005 is tracing only (technical), 93010 is interpretation only (professional). Use global when same provider does both. Don''t bill global with components.',
51, ARRAY['93000', '93005', '93010', 'EKG', 'ECG', 'electrocardiogram']),

('general', 'procedures', 'What is CPT 45378 (Colonoscopy)?',
'CPT 45378 describes diagnostic colonoscopy with visualization of entire colon from rectum to cecum. This is base colonoscopy code when: no biopsy taken, no polyp removed, diagnostic visualization only. Add-on/alternative codes when procedures performed: 45380 (with biopsy), 45384 (with hot biopsy forceps), 45385 (with snare polypectomy), 45388 (with ablation), multiple polyps (report appropriate code for each different technique). Professional vs facility billing: physician bills professional component with/without modifier 26, facility bills facility/technical component, global when performed in office setting. Code selection rules: when multiple procedures performed, bill most complex code only (not 45378 plus removal codes), specific removal technique codes supersede diagnostic code. Documentation requirements: complete colonoscopy confirmed (reached cecum documented, photographic evidence preferred), indication for procedure, findings with location/size of abnormalities, procedures performed, tissue sent to pathology. Common denials: insufficient sedation documentation, cecum not reached (use 45378-52 or 45330 if sigmoidoscopy only), wrong facility type, missing pre-authorization, screening vs diagnostic confusion.',
'45378 is diagnostic colonoscopy to cecum (no biopsy/removal). Use specific codes when procedures performed: 45380 (biopsy), 45385 (polypectomy). Don''t bill 45378 with removal codes - use specific procedure code only. Document cecum reached.',
52, ARRAY['45378', 'colonoscopy', 'diagnostic colonoscopy', 'colon scope']),

('general', 'procedures', 'What is CPT 11730 (Nail Removal)?',
'CPT 11730 describes avulsion (removal) of nail plate, partial or complete, simple, single. Indications: ingrown toenail, infected nail, damaged nail, onychomycosis unresponsive to treatment. Procedure includes: local anesthesia, nail removal, wound care. Code 11730 is per nail - can bill multiple units for multiple nails. Related codes: 11732 (each additional nail - add-on code), 11750 (permanent removal with destruction of nail matrix), 11740 (debridement of nail/cuticle). Cannot bill 11730 with routine nail trimming (11719, 11720, 11721) same visit. Documentation requirements: medical necessity (not cosmetic), nail(s) removed with specific identification, technique used, wound care provided, diagnosis supporting (paronychia, onychomycosis, ingrown nail). Modifiers: T-modifiers for specific toes (TA-T9), LT/RT for side identification, 59 if with other procedures on different sites. Common denials: cosmetic procedure, insufficient medical necessity, routine foot care, frequency limits (some payers limit how often billable). Medicare coverage: covered when medically necessary, not covered for routine foot care or cosmetic reasons, must document medical necessity clearly.',
'11730 is avulsion (removal) of nail plate, single nail. Can bill multiple units for multiple nails. 11732 is add-on for each additional. Requires medical necessity - not cosmetic. Use T-modifiers for specific toes. Document medical necessity clearly.',
53, ARRAY['11730', '11732', 'nail removal', 'ingrown toenail', 'nail avulsion']),

('general', 'procedures', 'What is CPT 96365-96368 (Infusion Therapy)?',
'CPT codes 96365-96368 describe intravenous infusion therapy for hydration, therapeutic/diagnostic substances. Code hierarchy: 96365 (IV infusion, first hour), 96366 (each additional hour), 96367 (additional sequential infusion), 96368 (concurrent infusion). Infusion definition: administration over 15+ minutes, less than 15 minutes is IV push (96374). Time calculation: begin timing when substance starts flowing, end when substance/final flush complete, round to nearest unit. Initial vs sequential: initial = first substance, sequential = different drug after first completed, concurrent = different drug simultaneous through different IV access. Documentation requirements: start/stop times for each infusion, substance administered, dosage, medical necessity, patient monitoring, administration route. Drug billing: bill drug separately with J-code (medication charge separate from administration), verify drug covered by payer, include NDC for drug. Common denials: insufficient time documentation (<15 minutes should be push not infusion), wrong hierarchy (must bill initial service 96365 before add-ons), time doesn''t support units claimed, drug not covered. Medicare rules: chemotherapy codes take precedence over hydration/infusion codes, specific hierarchy requirements.',
'96365-96368 are IV infusion codes: 96365 (first hour), 96366 (additional hour), 96367 (sequential different drug), 96368 (concurrent). Infusion = 15+ minutes. Document times. Bill drug separately with J-code. Must bill initial before add-ons.',
54, ARRAY['96365', '96366', 'infusion therapy', 'IV infusion', 'IV therapy']),

('general', 'procedures', 'What is CPT 99406/99407 (Smoking Cessation)?',
'CPT codes 99406 and 99407 describe smoking and tobacco use cessation counseling. Time-based codes: 99406 (intermediate, 3-10 minutes), 99407 (intensive, >10 minutes). Services included: discussion of tobacco use, health risks, cessation strategies, resources available, behavioral interventions. Who can bill: physicians and qualified healthcare professionals providing counseling. Cannot bill with: E/M service unless significant separately identifiable service (use modifier 25 on E/M), preventive visit without modifier 25. Documentation requirements: time spent in tobacco cessation counseling, specific strategies discussed, patient engagement/response, cessation plan developed. Medical necessity: current tobacco use documented in medical record, counseling related to cessation not just history taking. Frequency: Medicare covers 2 attempts per year, each attempt includes 4 intermediate (99406) or 4 intensive (99407) sessions within 12 months. ACA preventive service: many commercial payers cover 100% without cost-sharing. Common denials: time not documented, no qualifying tobacco use diagnosis, frequency limits exceeded, bundled with E/M visit, provider type not eligible. Must use appropriate tobacco use diagnosis codes (F17.210, Z72.0, etc.).',
'99406/99407 are smoking cessation counseling codes. Time-based: 99406 (3-10 min), 99407 (>10 min). Document time spent. Medicare covers 2 quit attempts/year, 4 sessions each. Use with tobacco use diagnosis. May require modifier 25 with E/M.',
55, ARRAY['99406', '99407', 'smoking cessation', 'tobacco counseling', 'quit smoking']),

('general', 'procedures', 'What is CPT 99457/99458 (Remote Patient Monitoring)?',
'CPT codes 99457 and 99458 describe remote physiologic monitoring treatment management services. 99457: first 20 minutes of clinical staff/physician time in calendar month, 99458: each additional 20 minutes (add-on code). Services included: reviewing device data, communicating results to patient, medication management based on data, ordering tests/services, coordination of care. Requirements: (1) 16 days of monitoring data in calendar month, (2) Interactive communication with patient, (3) Device transmits physiologic data (weight, BP, glucose, O2, etc.), (4) At least 20 minutes of time documented. Setup code: 99453 (device setup/patient education), 99454 (device supply/transmission for 30 days). Time calculation: cumulative time in calendar month spent on review and management, physician or clinical staff time counts, document activities and time. Documentation: specific device data reviewed, trends identified, interventions made, communications with patient, time spent. Cannot bill: same calendar month as CCM codes without sufficient additional time, when insufficient data days (<16), without patient consent. Coverage varies: Medicare covers with specific requirements, many commercial payers now covering, verify patient insurance coverage before setup.',
'99457/99458 are remote patient monitoring treatment codes. 99457 (first 20 min/month), 99458 (each additional 20 min). Requires 16+ days of data transmission, interactive communication, documented time. Bill once monthly. Also bill device codes 99453/99454.',
56, ARRAY['99457', '99458', 'remote patient monitoring', 'RPM', 'remote monitoring']),

('general', 'procedures', 'What is CPT 99441-99443 (Telephone E/M)?',
'CPT codes 99441-99443 describe telephone evaluation and management services by physician/qualified healthcare professional. Time-based codes: 99441 (5-10 minutes), 99442 (11-20 minutes), 99443 (21-30 minutes). Services included: medical discussion, assessment, management recommendations via telephone, not in-person or video. Who can bill: physicians and qualified NPPs (NP, PA, CNS). Cannot bill when: telephone call related to E/M within previous 7 days or results in appointment within 24 hours, call is only for test results/prescription refill/scheduling, video visit performed (use telehealth codes instead). Documentation requirements: reason for call, clinical assessment, recommendations/plan, time spent in telephone discussion, who initiated call (patient or physician). Medicare coverage: limited - added during COVID PHE but coverage varies post-PHE, verify current coverage. Commercial coverage: expanding but varies by payer, many require COVID-era waivers, telehealth codes preferred. Alternative: many payers prefer video visits (99202-99215 with modifier 95) over telephone, online digital evaluation codes (99421-99423) for non-real-time assessment. Document whether call meets criteria or should be part of recent visit.',
'99441-99443 are telephone E/M by physician. Time-based: 99441 (5-10 min), 99442 (11-20 min), 99443 (21-30 min). Cannot bill if related to visit within 7 days or leads to appointment within 24 hours. Coverage varies - verify payer policy.',
57, ARRAY['99441', '99442', '99443', 'telephone visit', 'phone call', 'phone consult']);

-- PHYSICAL THERAPY & NEUROMUSCULAR
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'pt-chiro', 'What is CPT 97110 (Therapeutic Exercise)?',
'CPT 97110 describes therapeutic exercises to develop strength, endurance, range of motion, and flexibility. This is most commonly used physical therapy code. Activities included: resistance training, active assistive/active/resistive exercises, aerobic conditioning, stretching/flexibility exercises. Time-based code: follows 8-minute rule, bill 1 unit per 8-22 minutes, 2 units for 23-37 minutes. Documentation requirements: specific exercises performed, body parts treated, parameters (sets, reps, resistance, time), patient response, functional goals addressed. Medicare modifiers required: GP (physical therapy), GO (occupational therapy), or GN (speech therapy). Cannot bill: same time as 97112 (neuromuscular re-ed) unless separate 15 minutes, with 97530 (therapeutic activities) without clear distinction. Common denials: insufficient time documented, maintenance therapy (not skilled), medical necessity not established, modifier missing, bundled with evaluation same visit. Medical necessity requires: documented functional deficit, skilled therapy needed (not exercise patient can do independently), measurable goals, progress toward goals. Best practice: vary codes based on actual treatment (don''t bill 97110 every visit), document specific exercises and skilled nature, demonstrate functional improvement.',
'97110 is therapeutic exercise (strength, ROM, endurance). Most common PT code. Time-based: 1 unit = 8-22 minutes (8-minute rule). Requires GP/GO/GN modifier for Medicare. Document specific exercises, body parts, patient response. Must be skilled therapy, not maintenance.',
60, ARRAY['97110', 'therapeutic exercise', 'PT exercise', 'physical therapy']),

('general', 'pt-chiro', 'What is CPT 97112 (Neuromuscular Re-education)?',
'CPT 97112 describes neuromuscular re-education of movement, balance, coordination, kinesthetic sense, posture, and proprioception. Focus: training nervous system and muscles to work together, typically for neurological conditions or post-surgical rehabilitation. Activities: balance training, proprioceptive training, coordination exercises, gait training components (when neuromuscular focus), postural training, movement pattern training. Time-based: follows 8-minute rule like 97110. Documentation requirements: specific neuromuscular techniques, balance/coordination deficits, activities performed, objective measurements (single leg stance time, balance test scores), functional improvements. Distinction from 97110: 97112 is retraining movement patterns/balance/coordination (neurological), 97110 is strengthening/ROM (musculoskeletal). Cannot bill: for simple strengthening exercises (use 97110), same 15 minutes as 97110 without clear separate activities, without documented neuromuscular deficit. Medicare modifiers: GP, GO, or GN required. Common denials: not distinguishable from 97110, insufficient documentation of neuromuscular nature, no documented deficit, considered maintenance therapy. Best practice: reserve 97112 for patients with true neuromuscular deficits (stroke, neuropathy, post-surgical proprioception loss), document specific balance/coordination activities and measurable deficits.',
'97112 is neuromuscular re-education (balance, coordination, proprioception). For neurological/neuromuscular deficits. Time-based (8-minute rule). Differs from 97110 - retraining movement patterns vs strengthening. Requires GP/GO/GN modifier. Document specific neuromuscular deficits.',
61, ARRAY['97112', 'neuromuscular reeducation', 'balance training', 'coordination']),

('general', 'pt-chiro', 'What is CPT 97140 (Manual Therapy)?',
'CPT 97140 describes manual therapy techniques including mobilization/manipulation, manual lymphatic drainage, manual traction. Techniques included: joint mobilization (grades I-IV), soft tissue mobilization, manual traction, myofascial release, instrument-assisted soft tissue mobilization (IASTM), manual lymphatic drainage. Time-based: follows 8-minute rule, 1 unit per 8-22 minutes. Documentation requirements: specific technique used (not just "manual therapy"), grade of mobilization if joint work, specific joints/tissues treated, patient response, skilled nature of treatment. Medicare modifiers: GP, GO, or GN required. Cannot bill: for massage therapy, with evaluation same day without clear separation in time, every visit without documented necessity. Common denials: vague documentation ("provided manual therapy"), considered maintenance, bundled with 97110, medical necessity not established, appears to be massage not skilled therapy. Medical necessity: document specific biomechanical dysfunction, tissue restrictions, joint hypomobility, why skilled manual techniques needed. Payer scrutiny: 97140 frequently audited - some payers limit frequency or require modifier 59 when billed same session as 97110. Best practice: document specific manual therapy techniques (joint mobilization C5-6 grade III, soft tissue mobilization to upper trapezius), vary treatment codes, don''t bill 97140 every visit.',
'97140 is manual therapy (mobilization, manipulation, soft tissue work). Time-based (8-minute rule). Document specific techniques (joint grades, tissues), not just "manual therapy." Requires GP/GO/GN modifier. Frequently audited - demonstrate skilled nature, not massage. Use selectively.',
62, ARRAY['97140', 'manual therapy', 'joint mobilization', 'soft tissue']);

-- MENTAL HEALTH
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'mental-health', 'What is CPT 90834 (Psychotherapy 38-52 min)?',
'CPT 90834 describes individual psychotherapy, 38-52 minutes face-to-face with patient. Most commonly used psychotherapy code. Time requirement: 38-52 minutes documented, less than 38 minutes use 90832, 53+ minutes use 90837. Services included: therapeutic interventions, discussion of patient issues, assessment of mental status, treatment planning, crisis intervention if needed. Documentation: start/end times or total time, presenting issues, therapeutic interventions used (CBT, DBT, psychodynamic, etc.), patient response/engagement, mental status observations, treatment plan/goals progress, risk assessment. With E/M same day: use add-on code 90836 instead of 90834 when psychotherapy provided same day as evaluation (90833/90836/90838 are add-on codes with E/M). Telehealth: can bill 90834 for video psychotherapy (audio-visual), use appropriate telehealth modifiers/POS. Medicare/Medicaid: covered when medically necessary with appropriate diagnosis, requires time documentation. Common denials: time not documented or insufficient (<38 minutes), medical necessity questioned, template notes without specificity, wrong code with E/M (should use 90836). Coverage note: most payers cover 90834 but may have visit limits (20-52 visits per year depending on plan). Authorization may be required after initial visits.',
'90834 is individual psychotherapy, 38-52 minutes. Most common therapy code. Document face-to-face time. Use 90836 if provided same day as E/M. Available via telehealth. Requires time documentation and mental health diagnosis. Coverage varies by plan.',
70, ARRAY['90834', 'psychotherapy', 'therapy session', 'counseling', 'individual therapy']),

('general', 'mental-health', 'What is CPT 90837 (Psychotherapy 53+ min)?',
'CPT 90837 describes individual psychotherapy, 53 minutes or greater face-to-face with patient. Extended therapy session code. Time requirement: minimum 53 minutes documented, reimbursement typically 50% higher than 90834. When appropriate: complex clinical presentations, crisis intervention, intensive therapy sessions, treatment-resistant conditions requiring extended time. Documentation: exact start/end times or total minutes, clinical complexity justifying extended session, detailed therapeutic work performed, patient engagement, progress notes. With E/M same day: use add-on code 90838 instead of 90837 when psychotherapy with medical evaluation same session. Payer considerations: some limit 90837 frequency (prefer 90834 for routine), may require authorization, medical necessity scrutiny higher than 90834, must document complexity/necessity for extended time. Common denials: time less than 53 minutes (should use 90834), time not documented, clinical notes don''t justify extended session, payer frequency limits exceeded, template documentation. Medicare: covers 90837 but reviews medical necessity, ensure 53+ minutes documented. Best practice: reserve 90837 for sessions truly requiring 53+ minutes, document clinical complexity, consider using 90834 when session 45-50 minutes (still gets good reimbursement), track payer-specific 90837 policies. Billing error: never round 50-minute session up to 90837.',
'90837 is psychotherapy 53+ minutes. Requires minimum 53 minutes documented. Pays ~50% more than 90834. Some payers limit frequency or scrutinize medical necessity. Use 90838 if same day as E/M. Document exact time and clinical complexity justifying extended session.',
71, ARRAY['90837', 'extended therapy', 'long therapy session', '60 minute therapy']);

-- HCPCS CODES
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'hcpcs', 'What is HCPCS G0283 (Electrical Stimulation)?',
'HCPCS code G0283 describes electrical stimulation (unattended) for wound healing other than pressure or venous stasis ulcers. Use for: diabetic ulcers, arterial ulcers, traumatic wounds not healing with standard care. Cannot use for: pressure ulcers (not covered), venous stasis ulcers (not covered), routine muscle stimulation. Requirements: wound present and documented, electrical stimulation specifically for wound healing, unattended application (patient or caregiver applies). Billing frequency: typically per treatment session, medical necessity requires documented wound not healing with standard care. Documentation: wound location, size, depth, drainage, healing progress, electrical stimulation parameters, device used, treatment frequency, wound photos beneficial. Medicare coverage: limited - covered for specific wound types with medical necessity, requires trial of standard wound care first, must document failure of standard treatment. Common denials: wound type not covered, insufficient medical necessity, missing wound documentation, device not appropriate for code, not medically necessary per LCD. Alternative codes: 97014 (electrical stimulation attended for muscle re-education), 97032 (constant attendance electrical stimulation), 64550 (application of surface neurostimulator). Many commercial payers follow Medicare coverage policies or don''t cover G0283.',
'G0283 is electrical stimulation (unattended) for wound healing. For diabetic/arterial ulcers, not pressure/venous ulcers. Medicare coverage limited - requires documented standard care failure. Document wound details, device, parameters. Many payers have restrictive coverage.',
80, ARRAY['G0283', 'electrical stimulation', 'e-stim', 'wound healing', 'tens unit']),

('general', 'hcpcs', 'What is HCPCS A4550 (Surgical Tray)?',
'HCPCS code A4550 describes surgical tray supply used during minor office procedures. Includes: sterile drapes, gauze, prep solution, instruments, gloves, and other supplies in pre-packaged sterile tray. Use when: office procedure performed requiring sterile technique, separate surgical tray opened and used, supplies beyond routine exam supplies needed. Procedures commonly billed with A4550: joint injections (20610), lesion removals, biopsies, suturing, I&D procedures. Reimbursement: typically $5-25 depending on payer, some payers don''t reimburse separately (bundled), Medicare reimburses in office setting. Documentation: procedure note should reference sterile tray used, specific procedure requiring sterile supplies. Cannot bill: for routine exam supplies, with procedures where tray included in procedure reimbursement per payer policy, multiple units (one tray per procedure encounter regardless of supplies used). Common denials: bundled into procedure payment, not separately reimbursable per payer, insufficient documentation, tray not medically necessary for procedure. Payer policies vary widely: Medicare pays separately, many commercial payers bundle into procedure, some payers never pay A4550. Best practice: verify payer policy before routine billing, maintain documentation of surgical tray use, consider cost vs reimbursement.',
'A4550 is surgical tray supply for office procedures. Includes sterile drape, gauze, instruments. Bill with minor procedures (injections, biopsies). Reimbursement $5-25, many payers bundle. One unit per encounter. Verify payer policy - coverage varies widely.',
81, ARRAY['A4550', 'surgical tray', 'procedure tray', 'sterile supplies']),

('general', 'hcpcs', 'What is HCPCS A7030/A7031/A7035 (CPAP Supplies)?',
'HCPCS codes A7030, A7031, and A7035 describe CPAP mask supplies. Code descriptions: A7030 (full face mask used with positive airway pressure device, each), A7031 (full face mask used with CPAP device, each), A7035 (nasal/oral mask used with CPAP device, each). Code selection: use A7031 or A7035 for CPAP masks, use A7030 for BiPAP/other PAP devices. Common confusion: A7030 vs A7031 - both are full face masks but A7030 for BiPAP and A7031 for CPAP. Frequency limits: Medicare allows complete mask every 3 months, cushions/pillows (A7032-A7034) allowed monthly, headgear (A7035) allowed every 6 months. Requirements for payment: CPAP compliance documented (4+ hours per night, 70% of nights in 30-day period), physician order on file, medical necessity established. Common denials: frequency limits exceeded (replacing too soon), non-compliance with usage requirements, missing compliance download, multiple mask types billed same timeframe. Billing rules: bill appropriate mask type (full face A7031 vs nasal A7035), cannot bill mask and cushion together unless entire assembly being replaced, requires ongoing compliance monitoring. Related codes: A7037 (tubing), A7038/A7039 (filters), E0601 (CPAP device).',
'A7030/A7031/A7035 are CPAP mask codes. A7031 (CPAP full face), A7035 (CPAP nasal), A7030 (BiPAP full face). Allowed every 3 months. Requires compliance documentation (4+ hours/night). Cannot bill mask and cushion together. Verify compliance before billing.',
82, ARRAY['A7030', 'A7031', 'A7035', 'CPAP mask', 'CPAP supplies', 'full face mask', 'nasal mask']);

-- PREVENTIVE & SCREENING
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'preventive', 'Can I bill preventive visit (99391-99397) and problem E/M (99213-99215) same day?',
'Yes, you can bill both preventive visit and problem-focused E/M on same day when: (1) Significant, separately identifiable problem addressed beyond preventive care, (2) Additional work clearly documented, (3) Modifier 25 appended to problem E/M code. How to bill: bill preventive code appropriate for age (99391-99397), bill problem E/M code with modifier 25 (example: 99214-25), use different diagnosis codes (preventive diagnosis on wellness code, problem diagnosis on E/M). Documentation requirements: clearly separate preventive components (comprehensive history, exam, counseling), clearly document separately identifiable problem evaluation/management, demonstrate significant additional work beyond wellness visit, document medical necessity for problem visit. Examples of separately billable: patient for annual physical, also complains of chest pain requiring evaluation. Patient for well-child, also has acute ear infection requiring exam and treatment. Not separately billable: minor issues addressed during wellness visit (brief counseling, simple prescription), routine disease management expected during preventive visit. Common denials: lack of modifier 25, insufficient documentation of separate problem, problem not significant enough, same diagnosis used for both codes. Payer policies: most follow modifier 25 guidelines, some payers bundle without additional payment, verify payer-specific policies.',
'Yes, bill both when significant separate problem addressed. Use preventive code (99391-99397) and E/M with modifier 25 (99213-25 or 99214-25). Must document separately identifiable problem and additional work. Use different diagnosis codes. Requires modifier 25 on E/M.',
85, ARRAY['preventive and sick visit', 'annual physical and E/M', 'wellness and problem visit', 'modifier 25 preventive']);

-- RADIOLOGY
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'radiology', 'What is CPT 71046 (Chest X-ray)?',
'CPT 71046 describes chest X-ray, 2 views (typically PA and lateral). Most commonly ordered chest X-ray study. Views included: 2 views - typically posteroanterior (PA) and lateral, provides comprehensive chest evaluation. Indications: respiratory symptoms, pre-operative clearance, suspected pneumonia, cardiac symptoms, trauma evaluation, routine screening per guidelines. Component billing: 71046 (global - includes technical and professional), 71046-TC (technical component only - facility bills), 71046-26 (professional component only - radiologist interpretation). Related codes: 71045 (single view - AP or PA), 71047 (3 views), 71048 (4+ views), 71100-71130 (ribs). Documentation: interpretation report documenting findings, medical necessity for order (symptoms, diagnosis), comparison to priors if available. Common denials: wrong number of views (billed 71046 but only 1 view taken), screening without covered indication, duplicate billing (both global and components), frequency limits. Medicare coverage: covered when medically necessary, routine screening generally not covered, pre-op clearance coverage varies. Billing error: billing 71046 when only single view performed (should be 71045) or billing components and global code together.',
'71046 is chest X-ray with 2 views (PA and lateral). Most common chest X-ray code. Use 71046 for global, 71046-TC for technical only, 71046-26 for professional only. Don''t bill 71046 if only 1 view taken (use 71045 instead).',
90, ARRAY['71046', '71045', 'chest X-ray', 'chest radiograph', 'CXR']);

