/*
  # Comprehensive Medical Billing FAQs - Batch 6
  
  ## Overview
  Adds final batch of comprehensive FAQs covering:
  - ICD-10 Coding & Documentation (6 FAQs)
  - Claim Submission & Rejections (5 FAQs)
  - Patient Financial Responsibility (5 FAQs)
  - Technology & EHR Integration (4 FAQs)
  - Additional Common Questions (5 FAQs)
  
  Total: 25 additional FAQs bringing total to 150+
*/

-- ICD-10 CODING & DOCUMENTATION FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'icd10-coding', 'What is ICD-10 and why is it important for medical billing?',
'ICD-10 (International Classification of Diseases, 10th Revision) is the global standard diagnostic classification system for healthcare. Purpose: (1) Diagnosis coding - translates medical conditions/diagnoses into standardized alphanumeric codes, (2) Statistical tracking - enables disease tracking, epidemiology, research, (3) Medical necessity - supports why services were medically necessary, (4) Payment determination - influences reimbursement levels, (5) Public health monitoring - tracks disease prevalence, outbreaks, trends. ICD-10 structure: 3-7 characters, first character always alphabetic, characters 2-7 may be numeric or alpha, decimal after 3rd character, increased specificity compared to ICD-9 (68,000+ codes vs 13,000). Importance in billing: (1) Claim acceptance - incorrect/missing ICD-10 causes rejections, (2) Medical necessity - must support CPT codes billed, (3) Payment accuracy - some codes trigger higher/lower payments, (4) Coverage determination - diagnosis affects whether service covered, (5) Audit defense - detailed codes demonstrate medical necessity. Coding specificity requirements: code to highest level of specificity documented, use appropriate laterality (right, left, bilateral), include extensions for encounters (initial, subsequent, sequela), use combination codes when available, follow official coding guidelines. Common errors: unspecified codes when specificity documented, missing laterality, incorrect sequencing (primary vs secondary), using outdated codes. Annual updates: ICD-10 codes updated October 1st each year, new codes added, some deleted, descriptions revised.',
'ICD-10 is diagnosis coding system with 68,000+ codes (3-7 characters). Critical for: claim acceptance, medical necessity support, accurate payment, coverage determination, audit defense. Must code to highest specificity, include laterality, use current codes. Updated annually October 1.',
350, ARRAY['ICD-10', 'diagnosis codes', 'ICD-10 coding', 'diagnosis coding', 'what is ICD-10']),

('general', 'icd10-coding', 'What is the difference between primary and secondary diagnoses?',
'Primary vs secondary diagnosis distinction: PRIMARY DIAGNOSIS (principal diagnosis) - main condition treated/evaluated during encounter, reason for visit from patient perspective or chief complaint, drives medical necessity for services provided, coded first/listed in position 1, most significant condition affecting patient care that encounter. SECONDARY DIAGNOSES - additional conditions affecting patient care, chronic conditions managed during visit, comorbidities relevant to treatment, complications, history affecting care. Sequencing rules: (1) Outpatient coding - reason for encounter is primary (symptom or definite diagnosis), chronic condition being monitored is secondary, (2) Inpatient coding - condition after study chiefly responsible for admission, (3) E/M visits - presenting problem or most significant issue, (4) Surgical procedures - condition necessitating surgery. Impact on billing: primary diagnosis establishes medical necessity for visit, influences coverage determination (covered vs non-covered), affects quality measures and risk adjustment, determines DRG for inpatient (payment group). Examples: Patient presents for chest pain (primary) with history of hypertension (secondary). Patient for diabetes management (primary) also has obesity (secondary). Post-op follow-up, surgical condition is primary even if healed. Common errors: sequencing chronic conditions before acute presenting problem, using symptom as primary when definitive diagnosis established, not including relevant secondary conditions affecting care. Best practice: primary diagnosis reflects reason for encounter/most resource-intensive condition, include all secondary conditions affecting treatment decisions or resource use, proper sequencing affects medical necessity demonstration.',
'Primary diagnosis = main reason for visit, listed first, establishes medical necessity. Secondary diagnoses = additional conditions affecting care, chronic conditions, comorbidities. Sequencing: outpatient (reason for encounter first), inpatient (condition after study). Impacts coverage, payment, quality measures. Include all relevant conditions.',
351, ARRAY['primary diagnosis', 'secondary diagnosis', 'diagnosis sequencing', 'ICD-10 order']),

('general', 'icd10-coding', 'Why do claims get denied for unspecified diagnosis codes?',
'Unspecified diagnosis code denials occur because: (1) Insufficient medical necessity - unspecified codes don''t demonstrate clinical specificity needed, payers question whether service was truly necessary, lack of detail suggests incomplete evaluation, (2) Documentation available - when documentation contains specificity but unspecified code used, considered coding error, payer expects highest specificity coded, (3) LCD/NCD requirements - many Local/National Coverage Determinations require specific diagnosis codes, unspecified codes often excluded from covered diagnosis lists, (4) Quality metrics - unspecified codes negatively impact quality measures, payers incentivize specific coding, (5) Payer policies - many payers automatically deny unspecified codes for certain services, require more detailed diagnosis information. Common unspecified code endings: .9 (unspecified), .90 (unspecified), without further specification. Services frequently denied: advanced imaging with unspecified codes (MRI, CT, PET), surgical procedures lacking specificity, DME with vague diagnoses, therapy services without specific deficits identified. Prevention: (1) Query provider - when documentation lacks specificity, ask for clarification before coding, (2) Review documentation - ensure all documented details coded, look for laterality, encounter type, severity, (3) Code to highest specificity - use all documented information, don''t default to unspecified, (4) Provider education - teach clinicians documentation needs, explain coding specificity requirements. Appeals: if unspecified code used but documentation supports specificity, submit corrected claim with specific code, provide documentation excerpt showing specificity, explain coding error.',
'Unspecified code denials because: insufficient medical necessity, specificity available in documentation but not coded, LCD/NCD requirements, quality metrics, payer policies. Common endings: .9, .90. Frequently denied for imaging, surgery, DME, therapy. Prevention: query providers, review documentation fully, code to highest specificity, educate providers.',
352, ARRAY['unspecified diagnosis', 'diagnosis denied', 'ICD-10.9', 'unspecified code denial']),

('general', 'icd10-coding', 'What is medical necessity and how is it documented?',
'Medical necessity means healthcare services/supplies are appropriate for symptoms/diagnosis, meet accepted medical standards, not primarily for convenience, and are cost-effective. Payer determination: service must be: (1) Appropriate for diagnosis - logical relationship between diagnosis and service, (2) Not experimental - accepted standard of care, (3) Not primarily for convenience - medical need present, (4) Necessary for diagnosis/treatment - couldn''t be omitted without adverse effect on condition. Documentation requirements: (1) Clear diagnosis - specific diagnosis supporting service need, (2) Clinical findings - symptoms, exam findings, test results supporting diagnosis, (3) Failed conservative treatment - when applicable, document tried less aggressive approaches, (4) Clinical rationale - explain why service necessary for this patient, (5) Risk vs benefit - consideration of patient-specific factors, (6) Treatment plan - how service fits into overall care plan. Examples of medical necessity documentation: "Patient with 6-month history of knee pain unresponsive to NSAids, physical therapy (8 weeks), and activity modification. Exam reveals effusion, limited ROM, positive McMurray sign. MRI ordered to evaluate suspected meniscal tear prior to determining if surgery indicated." Coverage tools: (1) Local Coverage Determinations (LCD) - MAC-specific coverage policies with covered diagnosis lists, (2) National Coverage Determinations (NCD) - Medicare-wide policies, (3) Clinical Policy Bulletins - commercial payer medical policies, (4) Coverage articles - specific guidance on covered services. Insufficient medical necessity: vague documentation, symptoms not matching service ordered, no documented failed conservative care when expected, routine screening without qualifying symptoms.',
'Medical necessity = service appropriate for diagnosis, meets standards, medically needed, cost-effective. Document: specific diagnosis, clinical findings supporting diagnosis, failed conservative treatment, clinical rationale, risk/benefit considerations. Reference LCD/NCD for coverage requirements. Insufficient: vague documentation, mismatch symptoms/service.',
353, ARRAY['medical necessity', 'medical necessity documentation', 'LCD', 'NCD', 'coverage determination']);

-- CLAIM SUBMISSION & REJECTIONS FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'claims', 'What is the difference between claim rejection and denial?',
'Rejection vs denial - critical distinction: REJECTION - claim not accepted by payer for processing, occurs at clearinghouse or payer system front-end before adjudication, caught by electronic edits/validations, claim never enters payer system, not considered filed for timely filing purposes, can be corrected and resubmitted within timely filing. Rejection reasons: invalid insurance ID number, patient not in payer system, non-covered provider/NPI, missing required fields, invalid CPT/ICD-10 codes, date format errors. DENIAL - claim processed and adjudicated by payer, received, reviewed, payment denied, appears on remittance advice (EOB/ERA), considered filed for timely filing, may have appeal rights, appears in payer system as processed. Denial reasons: medical necessity, authorization missing, timely filing violation, duplicate claim, non-covered services, coordination of benefits issues. Key differences: rejections never enter payer system and can be resubmitted (denials processed and may require appeals), rejections don''t count toward timely filing (denials do), rejections usually administrative errors (denials often policy/coverage issues), rejections fixable quickly (denials may need appeals/documentation). Response: rejections - correct error and resubmit promptly within timely filing, denials - determine if corrected claim or appeal appropriate, review denial reason carefully. Some "rejections" are actually denials returned as unprocessable - read reason codes carefully.',
'Rejection = claim not accepted into payer system, caught by edits before processing, can resubmit within timely filing (admin errors, invalid data). Denial = claim processed and payment denied, received/adjudicated, may require appeal (medical necessity, auth missing). Rejections fixable quickly, denials need appeals/documentation.',
360, ARRAY['rejection vs denial', 'claim rejection', 'claim denial', 'difference rejection denial']),

('general', 'claims', 'What is timely filing and what happens if the deadline is missed?',
'Timely filing is payer deadline for claim submission after date of service. Deadlines vary: Commercial payers (90-365 days typical, often 90-120 days, check contract/payer policy), Medicare (12 months/1 year from date of service, appeals have separate timeframes), Medicaid (varies by state, typically 90-180 days, some states 1 year), Workers compensation (varies by state, often 1 year, some require immediate reporting). Calculating timeframe: starts date of service (or discharge for inpatient), ends on deadline date (some payers deadline is by claim received, others by postmark/submission date). What happens when missed: claim denied with timely filing code (typically CO-29 or CO-50), provider cannot bill patient (contractual write-off), payment forfeited, very limited appeal rights. Exceptions allowing late filing: (1) Claims pending coordination of benefits - delayed while waiting for primary payer, file secondary within timeframe from primary payment, document primary payment date, (2) Retroactive coverage - patient coverage established retroactively, some payers extend filing deadline, (3) Payer error - payer misinformed about filing deadline, documented proof required, (4) Delay caused by payer - missing information requested by payer caused delay, document all payer interactions. Prevention: submit claims within 30 days of service ideally, track submission dates systematically, don''t wait until deadline approaches, resolve issues promptly, maintain claim status tracking system. Appeals: if denied for timely filing, determine if exception applies, gather documentation of exception circumstances, appeal with supporting evidence, success rate low without valid exception.',
'Timely filing = claim submission deadline (commercial 90-120 days, Medicare 1 year, Medicaid 90-180 days, varies by payer). Missed deadline = denied CO-29, cannot bill patient, payment lost. Exceptions: COB delays, retroactive coverage, payer error. Prevention: submit within 30 days, track systematically. Appeals require valid exception.',
361, ARRAY['timely filing', 'filing deadline', 'CO-29', 'late filing', 'claim deadline']),

('general', 'claims', 'Why was my claim rejected for invalid provider NPI?',
'Invalid provider NPI rejections occur when: (1) NPI not enrolled with payer - provider has NPI but not credentialed/enrolled with payer receiving claim, must complete credentialing before billing, (2) Wrong NPI used - billed under incorrect provider NPI, used individual NPI when group required (or vice versa), rendering vs billing provider confusion, (3) NPI deactivated - provider let NPI lapse, not maintained active status, (4) Taxonomy code mismatch - NPI taxonomy doesn''t match service billed, payer expects specific specialty taxonomy, (5) Rendering provider missing - rendering provider NPI not included when required, supervising physician not referenced, (6) Type 1 vs Type 2 - billed under Type 1 (individual) when Type 2 (organization) required, payer-specific requirements vary. Resolution steps: (1) Verify NPI active - check NPPES registry (npiregistry.cms.hhs.gov), confirm NPI active and information current, (2) Confirm credentialing - verify provider enrolled with payer for this NPI, check enrollment status in payer portal, (3) Correct NPI - determine correct NPI for service billed (individual vs group), verify payer requirements, (4) Update claim - resubmit with correct NPI information, include all required provider fields, (5) Complete enrollment - if not enrolled, complete credentialing application, wait for approval before resubmitting claims. Prevention: maintain NPI database with payer enrollment status, verify credentialing before seeing patients, update taxonomy codes when needed, use correct NPI per payer requirements (individual vs group), maintain active NPI registration.',
'Invalid NPI rejections: NPI not enrolled with payer, wrong NPI used (individual vs group), deactivated NPI, taxonomy mismatch, missing rendering provider, Type 1 vs Type 2 issues. Resolution: verify NPI active in NPPES, confirm enrollment with payer, correct NPI on claim, complete credentialing if needed. Prevent: track enrollment status, verify before billing.',
362, ARRAY['invalid NPI', 'NPI rejection', 'provider not enrolled', 'NPI not found']);

-- PATIENT FINANCIAL RESPONSIBILITY FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'patient-billing', 'How do you calculate patient responsibility?',
'Patient responsibility calculation process: (1) Determine contracted rate - insurance contract rate for services (not billed charges), allowed amount/approved amount from insurance. (2) Apply to deductible if not met - patient pays amount toward annual deductible, insurance pays nothing until deductible met, track deductible remaining. (3) Calculate coinsurance - once deductible met, patient pays percentage (typically 10-40%), insurance pays remainder (60-90%), based on allowed amount not billed charges. (4) Add copay if applicable - fixed amount per visit ($10-75 typical), due regardless of deductible status, visit copay vs specialist copay, preventive services often no copay. (5) Apply to out-of-pocket maximum - all deductible, coinsurance, copays count toward annual max, once reached insurance pays 100%, typically $3,000-$8,000 individual. Example calculation: Service allowed amount $500, patient has $1,000 deductible ($500 remaining), 20% coinsurance, $3,000 OOP max ($1,000 used). Patient responsibility: $500 to deductible (now met) + $0 coinsurance (deductible not met on this claim). If deductible already met: $100 coinsurance (20% of $500). Coordination of benefits: when secondary insurance exists, calculate primary responsibility first, secondary insurance may cover patient portion. Tools: insurance EOB shows allowed amount and patient responsibility, eligibility inquiry shows deductible/OOP amounts, patient estimates based on benefits verification. Collection timing: copays at service time, deductible/coinsurance after insurance processes (patient statement).',
'Calculate patient responsibility: (1) Determine contracted allowed amount, (2) Apply to deductible if not met, (3) Calculate coinsurance % after deductible met, (4) Add copay if applicable, (5) Track toward out-of-pocket maximum. Use EOB allowed amount (not billed charges). Collect copays at service, statement for deductible/coinsurance.',
370, ARRAY['patient responsibility', 'calculate patient balance', 'deductible coinsurance', 'patient portion']),

('general', 'patient-billing', 'What is an Advance Beneficiary Notice (ABN) and when is it required?',
'Advance Beneficiary Notice (ABN) is Medicare form (CMS-R-131) notifying beneficiaries that Medicare may deny payment and patient may be financially responsible. When required: (1) Service likely to be denied - provider believes Medicare won''t cover service, medical necessity questionable, frequency limits may be exceeded, LCD indicates non-coverage, (2) Before service provided - must obtain signature before rendering service, retroactive ABN invalid, (3) Elective services - patient chooses to receive potentially non-covered service, routine screening without qualifying symptoms. ABN components: reason for potential denial (specific explanation required), estimated cost of service (good faith estimate), patient choice options (Option 1: receive service and bill Medicare, may be financially responsible; Option 2: receive service, don''t bill Medicare, patient pays; Option 3: decline service). Not required for: never-covered services (cosmetic procedures), beneficiary requested upgrades, routine screenings known to be non-covered, when provider accepts financial responsibility. Proper completion: notifier section with provider information, reason for ABN clearly explained, estimated cost range provided, patient selects option and signs, provider retains signed copy. Result: with valid ABN, can bill patient if Medicare denies, without ABN, provider responsible for denied amount (cannot bill patient). Common services requiring ABN: frequency-exceeded services (EKGs, screenings), routine foot care, vitamin injections, services without medical necessity. Invalid ABN: not specific about reason, obtained after service, no cost estimate, not signed.',
'ABN (Advance Beneficiary Notice) = Medicare form (CMS-R-131) notifying patient Medicare may deny and patient may pay. Required when: service likely denied, before service provided, medical necessity questionable, frequency limits exceeded. Must include reason, cost estimate, patient option selection. With valid ABN, can bill patient. Without ABN, provider responsible.',
371, ARRAY['ABN', 'Advance Beneficiary Notice', 'CMS-R-131', 'Medicare ABN']),

('general', 'patient-billing', 'Can providers offer cash discounts or payment plans?',
'Yes, providers can offer cash discounts and payment plans with important considerations: CASH DISCOUNTS - Legal and acceptable: discounts for immediate payment, available to all patients (not selective), clearly communicated discount policy, apply consistently. Concerns to avoid: discriminatory pricing (violating anti-discrimination laws), insurance fraud (routine waiver of copays/deductibles to induce business is illegal), contractual violations (some payer contracts restrict discounting). Best practices: document discount policy in writing, apply equally to all cash-pay patients, don''t advertise as "insurance negotiated rate," ensure discount doesn''t violate payer contracts. PAYMENT PLANS - Permissible arrangements: extended payment plans without interest (no regulatory issues), structured monthly payments, written payment agreements, reasonable timeframes. Requirements: HIPAA compliance for payment plan communications, written agreement specifying terms, consistent application of payment plan policies, don''t discriminate based on protected characteristics. Considerations: charging interest may require compliance with Truth in Lending Act (Regulation Z), discounts for upfront payment acceptable, can use third-party financing companies, may offer financial hardship policies. What NOT to do: routinely waive copays/deductibles (inducement/fraud), selective discounting based on insurance (contractual violation), advertise discounts that violate payer contracts, discriminatory pricing practices. Medicare-specific: cannot routinely waive Medicare copays/deductibles without financial hardship determination, systematically waiving cost-sharing is federal fraud.',
'Yes to cash discounts: must apply consistently to all patients, documented policy, don''t violate payer contracts, not routine copay waiver (fraud). Yes to payment plans: written agreements, interest-free or comply with Truth in Lending Act, consistent policies, HIPAA compliance. Don''t: routinely waive copays/deductibles (fraud), discriminatory pricing, selective discounting.',
372, ARRAY['cash discount', 'payment plan', 'financial policy', 'patient payment options']);

-- TECHNOLOGY & EHR INTEGRATION FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'technology', 'What is the difference between Practice Management and EHR systems?',
'Practice Management (PM) and Electronic Health Record (EHR) systems serve different functions: PRACTICE MANAGEMENT (PM) - Administrative/business functions: scheduling/appointments, patient demographics, insurance information, charge capture, claim submission, payment posting, accounts receivable, reporting. Revenue cycle focus: billing operations, financial management, claims processing, patient statements, collection activities. ELECTRONIC HEALTH RECORD (EHR) - Clinical documentation: patient medical history, clinical notes, medications, problem lists, lab/imaging results, clinical decision support. Healthcare delivery focus: charting, e-prescribing, clinical workflows, CPOE (computerized physician order entry), meaningful use/promoting interoperability. Integration: (1) Standalone systems - separate PM and EHR from different vendors, interface required for data exchange, demographic/insurance data flow from PM to EHR, clinical documentation may not flow to billing. (2) Integrated systems - single platform combining PM and EHR (examples: Epic, Cerner, athenahealth, eClinicalWorks), seamless data flow, documentation automatically available for coding/billing, reduced duplicate entry. Benefits of integration: clinical data accessible for coding, charges captured from documentation, reduced errors from manual transfer, more efficient workflows, better reporting combining clinical and financial data. Challenges with separate systems: maintaining demographic data in two systems, manual charge entry from clinical notes, reconciling disconnected information.',
'PM (Practice Management) = administrative/billing (scheduling, insurance, claims, payments, A/R, financial). EHR (Electronic Health Record) = clinical documentation (medical history, notes, meds, labs, e-prescribing). Can be standalone (separate systems) or integrated (single platform). Integration benefits: seamless data flow, reduced errors, efficient workflows.',
380, ARRAY['PM vs EHR', 'Practice Management', 'EHR system', 'EMR vs PM']),

('general', 'technology', 'What is a clearinghouse and why is it used?',
'Medical clearinghouse is intermediary between healthcare providers and insurance payers that processes and transmits claims electronically. Functions: (1) Claim scrubbing - checks claims for errors before payer submission, validates CPT/ICD-10 codes, verifies required fields present, checks NCCI edits, identifies potential denials. (2) Format conversion - translates claim data to payer-specific format, converts to HIPAA-compliant 837 transaction, adapts to payer requirements. (3) Transmission - securely transmits claims to payers, provides confirmation of receipt, tracks submission status. (4) Eligibility verification - real-time insurance verification (270/271 transactions), batch eligibility checking. (5) Electronic remittance - receives ERA (835 transactions) from payers, delivers to provider systems. (6) Reporting - submission reports, acceptance/rejection reports, transmission tracking, error analysis. Benefits: faster claim processing (electronic vs paper), reduced rejections (scrubbing catches errors), single connection to multiple payers (vs individual payer connections), cost-effective compared to direct payer connections, centralized submission tracking. How it works: provider submits claims to clearinghouse, clearinghouse scrubs for errors, rejects returned to provider for correction, clean claims formatted and transmitted to payers, confirmation returned to provider. Major clearinghouses: Change Healthcare, Waystar (Zirmed), Availity, Office Ally, Trizetto. Costs: typically per-claim fee ($0.10-$1.00), some offer unlimited for monthly fee, cost vs benefit of rejection prevention. Direct submission alternative: some large providers connect directly to major payers, requires technical infrastructure, payer-by-payer integration.',
'Clearinghouse = intermediary processing claims electronically between providers and payers. Functions: claim scrubbing (catches errors), format conversion (payer-specific), secure transmission, eligibility verification, ERA receipt. Benefits: faster processing, reduced rejections, single connection to multiple payers. Typical cost $0.10-$1 per claim.',
381, ARRAY['clearinghouse', 'what is clearinghouse', 'claim clearinghouse', 'electronic claims']),

('general', 'technology', 'What are 837 and 835 transactions?',
'837 and 835 are HIPAA standard electronic transaction formats: 837 TRANSACTION (Claim submission) - Electronic claim format providers submit to payers, HIPAA-mandated format for electronic claims, versions: 837P (professional/physician claims - CMS-1500 equivalent), 837I (institutional claims - UB-04 equivalent), 837D (dental claims). Contains: patient demographics, provider information, insurance details, diagnosis codes, procedure codes, charges, service dates. Process: provider system generates 837, clearinghouse receives and validates, transmitted to payers electronically, replaces paper claim submission. 835 TRANSACTION (Electronic Remittance Advice/ERA) - Electronic payment/explanation from payer to provider, replaces paper EOB/remittance, HIPAA standard format, automatic posting capability. Contains: payment amounts, adjustment reasons (denial codes, contractual adjustments), patient responsibility, claim status, check/EFT information. Process: payer adjudicates claim, generates 835, transmits to provider (via clearinghouse or direct), provider PM system automatically posts payments. Benefits of 835: automatic payment posting (reduces manual entry), faster posting (real-time with EFT), improved accuracy (eliminates manual entry errors), better reporting (electronic data analysis), denial management (reason codes easily tracked). Other HIPAA transactions: 270/271 (eligibility inquiry/response), 276/277 (claim status inquiry/response), 278 (authorization/referral). Implementation: PM system must support 837/835 formats, clearinghouse facilitates transmission, electronic enrollment with payers required, EFT enrollment for electronic payment.',
'837 = electronic claim submission to payers (HIPAA format). Versions: 837P (professional), 837I (institutional), 837D (dental). Contains patient/provider info, diagnoses, procedures, charges. 835 = electronic remittance advice (ERA) from payers. Contains payments, adjustments, denials, patient responsibility. Enables automatic posting. Both required for electronic transactions.',
382, ARRAY['837 transaction', '835 transaction', 'ERA', 'electronic claims', 'EDI transactions']);

-- ADDITIONAL COMMON QUESTIONS
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'general', 'What is the difference between in-network and out-of-network?',
'In-network vs out-of-network distinction: IN-NETWORK (participating providers) - provider has contract with insurance company, agreed to accept negotiated rates (typically 30-60% less than charges), provider cannot balance bill patient beyond allowed amount, benefits: lower patient costs (copays/coinsurance), predictable payments, higher insurance coverage percentage (80-100%), generally no claim forms for patient. OUT-OF-NETWORK (non-participating providers) - no contract with insurance company, can charge full fees, may balance bill patient, consequences: higher patient costs (deductibles/coinsurance), lower insurance coverage (often 50-70% or none), patient may need to file claims, might not count toward out-of-pocket maximum. Patient cost differences: In-network office visit: $150 allowed, patient $30 copay, insurance pays $120. Out-of-network office visit: $200 charged, patient pays $100 (50% coinsurance) + potential balance billing up to $200 if provider balance bills. Balance billing: out-of-network provider bills patient for difference between charges and insurance payment (billed $200, insurance paid $100, patient billed additional $100), not allowed for in-network providers (accept allowed amount as payment in full), some states restrict balance billing. Surprise billing protections: federal No Surprises Act protects patients from unexpected out-of-network bills in certain situations (emergency care, out-of-network providers at in-network facility). Verification: always verify provider in-network status before appointment, network participation can change, specialist networks may differ from PCP networks.',
'In-network = provider has payer contract, accepts negotiated rates (30-60% discount), cannot balance bill, lower patient costs (copays). Out-of-network = no contract, full fees, can balance bill, higher patient costs (coinsurance 50-70%), less insurance coverage. Verify network status before appointments. Federal protections for surprise billing.',
390, ARRAY['in-network', 'out-of-network', 'participating provider', 'balance billing']),

('general', 'general', 'What is coordination of benefits (COB)?',
'Coordination of Benefits (COB) is process determining which insurance pays first when patient has multiple insurance policies. Purpose: prevents duplicate payment, ensures claims paid correctly by appropriate payer, establishes primary/secondary payer order. Common dual coverage scenarios: (1) Patient has employer plan + spouse employer plan, (2) Medicare + secondary insurance (Medigap, employer), (3) Medicare + Medicaid, (4) Child covered by both parents'' insurance, (5) Motor vehicle accident with auto insurance + health insurance. Determining primary payer: Birthday rule (children with two parent plans) - parent whose birthday comes first in calendar year is primary (not older parent, just earlier birthday), if same day, plan covering parent longer is primary. Active employee rule - active employee coverage is primary over retiree coverage, employer plan for working aged (65+) with 20+ employee group is primary over Medicare. Medicare secondary payer rules - identify when Medicare is secondary (working aged, disability with large group, ESRD first 30 months). Billing process: (1) Bill primary insurance first, (2) Wait for primary payment/denial, (3) Bill secondary insurance with primary EOB, (4) Secondary pays remaining allowed amount or portion thereof, (5) Patient responsible for remaining balance. COB information collection: verify all insurance at each visit, obtain COB questionnaire responses, update when coverage changes, document primary/secondary designation. Incorrect COB consequences: claims denied pending COB information, requests for refund when paid incorrectly, payment delays while resolving.',
'COB (Coordination of Benefits) = determining which insurance pays first with multiple coverage. Common: dual employer plans, Medicare + secondary, both parents cover child. Rules: Birthday rule (children - parent with earlier birthday primary), Active employee primary over retiree, Medicare secondary payer rules. Process: bill primary first, then secondary with EOB.',
391, ARRAY['COB', 'coordination of benefits', 'primary secondary insurance', 'dual coverage', 'birthday rule']),

('general', 'general', 'How long should medical billing records be retained?',
'Medical billing record retention requirements: Federal requirements: (1) Medicare - 5 years from date of service or date claim was paid (whichever is later), longer if matter under investigation/litigation, MAC audits may request records 7+ years old. (2) Medicaid - varies by state, typically 5-7 years, some states require 10 years, check state-specific requirements. (3) HIPAA - 6 years from creation or last use of record. (4) Federal False Claims Act - potential liability for 10 years. State requirements: vary significantly by state (3-10 years common), medical records often longer than billing records, check state medical board requirements, some states specify different periods for different record types. Best practice recommendation: Minimum 7 years for all billing documentation (claims, EOBs, payments, denials, appeals, medical records supporting billing), Permanent retention for significant litigation/audit issues, immunization records, minors until age of majority + statute of limitations. What to retain: patient demographics, insurance information, signed ABNs, medical records supporting codes, encounter forms/charge tickets, itemized bills, EOBs/ERAs, payment records, correspondence with payers, authorization documentation, denial and appeal records. Retention format: paper or electronic acceptable, ensure records remain accessible and legible, maintain security and HIPAA compliance, have retrieval system for audits. Destruction: use secure destruction methods (shredding paper, secure electronic deletion), document destruction dates and scope, don''t destroy during audit/investigation, maintain destruction logs.',
'Retention requirements: Medicare 5 years minimum (longer if under investigation), Medicaid 5-7 years (varies by state), HIPAA 6 years, False Claims Act 10 years. Best practice: 7 years minimum for all billing documents. Retain: demographics, insurance, ABNs, medical records, claims, EOBs, payments, authorizations, appeals. Secure destruction after retention period.',
392, ARRAY['record retention', 'how long keep records', 'document retention', 'billing records retention']),

('general', 'general', 'What is upcoding and why is it illegal?',
'Upcoding is billing higher-level service codes than justified by documentation or services actually provided. Forms of upcoding: (1) E/M upcoding - billing 99214 when 99213 appropriate, level 5 when level 4 documentation, insufficient MDM for level claimed. (2) Procedure upcoding - billing complex procedure code for simple procedure, comprehensive code when limited performed, surgical approach not actually used. (3) Unbundling - billing multiple component codes when comprehensive code exists, separating inclusive services to increase payment, violating NCCI bundling edits. (4) Modifier misuse - inappropriate use of modifier 59 to bypass edits, modifier 25 without separately identifiable service, modifiers to artificially increase payment. Why illegal: (1) False Claims Act violation - submitting false/fraudulent claims to federal programs, knowingly requesting payment for services not provided as billed, civil penalties $11,665-$23,331 per false claim plus treble damages. (2) Healthcare fraud - intent to defraud payers, criminal prosecution possible, fines and imprisonment. (3) Contractual violation - violates participation agreements with payers, breach of contract, can lead to termination. Detection methods: payer data analysis (statistical outliers, peer comparison, coding patterns), audits (prepayment, postpayment, focused), whistleblower reports, data mining. Red flags: predominantly high-level codes, inconsistent with specialty norms, significant increase in coding levels, minimal documentation supporting high codes. Defense: code accurately per documentation, ensure documentation supports codes, regular compliance audits, staff training on appropriate coding, respond promptly to audit requests.',
'Upcoding = billing higher codes than documented/performed. Forms: E/M upcoding, procedure upcoding, unbundling, modifier misuse. Illegal: False Claims Act violation ($11K-$23K per claim + treble damages), healthcare fraud (criminal), contract breach. Detected via data analysis, audits, peer comparison. Prevention: accurate coding, documentation supporting codes, compliance audits, training.',
393, ARRAY['upcoding', 'fraud', 'unbundling', 'False Claims Act', 'coding fraud']);

