/*
  # Additional Medical Billing FAQs - Batch 3
  
  ## Overview
  Adds remaining high-value FAQ categories:
  - Mental Health (6 FAQs)
  - Telehealth (5 FAQs)
  - Patient Billing (7 FAQs)
  - Credentialing (5 FAQs)
  - Accounts Receivable (7 FAQs)
  - Payer-Specific (5 FAQs)
  
  Total: 35+ additional FAQs
*/

-- MENTAL HEALTH FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'mental-health', 'What is CPT 90834 vs 90837?',
'CPT 90834 is psychotherapy 38-52 minutes while 90837 is psychotherapy 53+ minutes. Key differences: Time requirement - 90834 requires 38-52 minutes face-to-face, 90837 requires 53+ minutes. Reimbursement - 90837 pays approximately 50% more than 90834. Documentation - both require time documentation, therapeutic interventions, and clinical assessment. Common error: billing 90837 when session was only 45-50 minutes (should be 90834). Best practice: document exact start and end times. For sessions with E/M services same day, use add-on codes: 90836 (with 90834) or 90838 (with 90837). Time includes only face-to-face psychotherapy with patient, not documentation or administrative time. Under-documenting time results in downcoding. Over-reporting time triggers audits. Telehealth psychotherapy uses same codes with modifier 95 or appropriate telehealth POS.',
'90834 = psychotherapy 38-52 minutes. 90837 = psychotherapy 53+ minutes (pays ~50% more). Document exact face-to-face time. Use add-on codes (90836/90838) when billed with E/M same day.',
120, ARRAY['90834 90837', 'psychotherapy codes', 'therapy time', 'mental health']),

('general', 'mental-health', 'Why is CPT 90837 denied frequently?',
'CPT 90837 denials occur due to: (1) Insufficient time - documented time less than 53 minutes, (2) No time documentation - start/end times or total time missing, (3) Payer policies - some limit 90837 frequency or require authorization, (4) Medical necessity - clinical notes don''t support need for extended session, (5) Incorrect modifier - telehealth or crisis modifiers missing when required. Prevention: document exact session time (start/end or total), ensure minimum 53 minutes face-to-face, include detailed clinical note supporting extended session necessity, verify payer policies on 90837 limitations, use appropriate modifiers for telehealth or crisis. Appeals require: time documentation proof, clinical justification for extended session length, demonstration of medical complexity requiring extended time. Some payers prefer 90834 and limit 90837 to specific clinical scenarios. Understanding payer-specific policies prevents unnecessary denials.',
'90837 denials: insufficient documented time (<53 min), missing time documentation, payer frequency limits, or lack of medical necessity. Prevention requires exact time documentation and clinical justification.',
121, ARRAY['90837 denied', 'psychotherapy denial', 'mental health denial', 'therapy denied']),

('general', 'mental-health', 'What documentation is required for psychotherapy?',
'Psychotherapy documentation requirements include: (1) Date and time - session date with start/end times or total duration, (2) Clinical assessment - presenting problems, mental status, symptoms, (3) Therapeutic interventions - specific techniques used (CBT, DBT, psychodynamic, etc.), (4) Patient response - engagement level, insights gained, progress or challenges, (5) Treatment plan - goals addressed, progress toward goals, plan for future sessions, (6) Medical necessity - why psychotherapy is clinically appropriate, (7) Risk assessment - suicide/homicide risk when applicable, (8) Diagnosis codes - supporting DSM-5 diagnoses, (9) Provider signature - credentials and date. Insufficient documentation causes denials for: lack of medical necessity, time not documented, template notes without specificity, missing clinical assessment. HIPAA requires maintaining psychotherapy notes separately from medical record, but billing requires complete medical record documentation.',
'Required: session date/time, clinical assessment, specific therapeutic interventions, patient response, treatment plan/goals, medical necessity justification, risk assessment when applicable, DSM-5 diagnoses, provider signature.',
122, ARRAY['psychotherapy documentation', 'therapy notes', 'mental health documentation', 'progress notes']),

('general', 'mental-health', 'What is CPT 90791 vs 90792?',
'CPT 90791 is psychiatric diagnostic evaluation without medical services. CPT 90792 is psychiatric diagnostic evaluation with medical services (medication management). Use 90791 for: initial diagnostic assessment, therapy-only providers (non-prescribing), comprehensive evaluation without prescribing. Use 90792 for: initial evaluation by prescriber, assessment including medication review/management, when medical factors are evaluated for prescribing. Key difference: medical services component. Documentation for both includes: comprehensive psychiatric history, mental status examination, diagnostic formulation, treatment recommendations. 90792 additionally documents: medical review of systems, medication review, prescribing considerations. Billing 90792 when provider isn''t prescribing is incorrect. Using 90791 when medications are managed undercodes. Cannot bill initial evaluation codes (90791/90792) for established patients - use E/M codes instead. One initial evaluation per episode of care.',
'90791 = psychiatric evaluation without medical services (non-prescribing provider). 90792 = psychiatric evaluation with medical services (prescribing provider). Use appropriate code based on prescribing authority.',
123, ARRAY['90791 90792', 'psychiatric evaluation', 'initial assessment', 'mental health eval']),

('general', 'mental-health', 'What CPT codes are allowed for tele-therapy?',
'Telehealth psychotherapy uses same CPT codes as in-person with modifier 95 or appropriate POS code: 90832-90834-90837 (individual psychotherapy), 90846-90847 (family therapy), 90853 (group therapy), 90791-90792 (diagnostic evaluation). Requirements: audio and visual two-way communication (phone-only typically not covered except during PHE waivers), patient consent for telehealth, state licensure in patient''s location, HIPAA-compliant platform. Telephone-only codes (99441-99443) have limited coverage and aren''t considered psychotherapy. Some states have parity laws requiring telehealth reimbursement equal to in-person. Medicare relaxed telehealth restrictions during COVID PHE but some restrictions returned post-PHE. Documentation must indicate telehealth modality and confirm audio-visual connection. Verify payer-specific telehealth policies as coverage varies widely.',
'Use same psychotherapy codes (90834, 90837, etc.) with modifier 95 or telehealth POS. Requires audio-visual two-way communication, patient consent, proper licensure. Coverage varies by payer and state.',
124, ARRAY['telehealth therapy', 'teletherapy', 'online therapy billing', 'virtual therapy']);

-- TELEHEALTH FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'telehealth', 'What are the most used telehealth CPT codes?',
'Most common telehealth CPT codes: 99202-99215 (office visits - new and established), 99421-99423 (online digital E/M services), 90832-90837 (psychotherapy), 99441-99443 (telephone E/M - limited coverage), 99421-99423 (online assessments), 99491-99492 (chronic care management), G2012 (virtual check-in), G2010 (remote evaluation), 98970-98972 (non-physician digital services). Modifier requirements: modifier 95 (synchronous telemedicine) or appropriate POS code (02 or 10). Coverage expanded during COVID but some services reverted to pre-pandemic policies. Requirements: real-time audio-visual communication (phone-only limited), HIPAA-compliant platform, patient consent, provider licensed in patient location. Documentation must indicate telehealth modality. Payer policies vary significantly - verify before providing telehealth services.',
'Common telehealth codes: 99202-99215 (office visits), 90832-90837 (psychotherapy), 99421-99423 (online E/M), care management codes. Use modifier 95 or POS 02/10. Requires audio-visual communication.',
130, ARRAY['telehealth codes', 'telemedicine codes', 'virtual visit codes', '99214 telehealth']),

('general', 'telehealth', 'What modifiers are required for telehealth billing?',
'Telehealth modifier requirements vary by payer: Medicare: modifier 95 (synchronous telemedicine) or appropriate place of service (POS 02 for telehealth, POS 10 for home). Some codes don''t require modifiers (inherently telehealth codes). Commercial payers: many accept modifier 95, some require GT or specific POS codes, policies vary by state and payer. Medicaid: state-specific requirements - some require GT, others 95, some POS codes. During COVID PHE, many modifiers were waived but post-PHE requirements returned. Additional modifiers: 93 (audio-only during PHE), GQ (asynchronous store-and-forward). Documentation must specify telehealth method, location, and technology used. Verify current payer-specific requirements as telehealth policies frequently change. Incorrect modifiers cause denials or payment delays.',
'Common modifiers: 95 (synchronous telemedicine), GT (interactive telehealth), POS 02 (telehealth) or 10 (home). Requirements vary by payer - Medicare uses 95 or POS codes, commercial/Medicaid policies vary by state.',
131, ARRAY['telehealth modifiers', 'modifier 95', 'modifier GT', 'telehealth billing']),

('general', 'telehealth', 'Why was my telehealth claim denied for POS issues?',
'Telehealth POS denials occur when: (1) Wrong POS code - used office (11) instead of telehealth (02) or home (10), (2) POS not allowed for code - some codes require specific POS, (3) Payer doesn''t recognize telehealth POS - some payers don''t accept POS 02, (4) Missing modifier - POS 11 requires modifier 95 for telehealth, (5) State restrictions - telehealth not covered or limited in patient''s state. Medicare requirements: POS 02 (telehealth) when patient at telehealth site, POS 10 (home) when patient at home, modifier 95 with POS 11 if billed as office visit. Commercial payers vary: some accept POS 02, others require POS 11 with modifier 95, some have specific telehealth POS requirements. Prevention: verify payer-specific POS requirements, use consistent POS/modifier combination, check state telehealth regulations, document patient and provider locations.',
'POS denials occur with wrong location codes (office 11 vs telehealth 02 or home 10), missing modifiers, or payer doesn''t accept telehealth POS. Requirements vary by payer - verify before billing.',
132, ARRAY['POS denial', 'telehealth denied', 'place of service', 'wrong POS']),

('general', 'telehealth', 'What is the difference between modifier 95 and GT?',
'Modifier 95 and GT both indicate telehealth services but differ: Modifier 95 (Synchronous Telemedicine): Medicare-preferred modifier, indicates real-time interactive audio-visual communication, used with most telehealth CPT codes, required by many commercial payers. Modifier GT (Interactive Telehealth): older modifier, some Medicaid programs require, indicates interactive audio-visual telecommunication, declining use as 95 becomes standard. Current trends: Medicare and most commercial payers prefer 95, some state Medicaid still require GT, cannot use both modifiers simultaneously. Some payers accept either. Best practice: verify payer-specific requirements, use consistent modifier per payer policy, document telehealth technology used. During COVID PHE, additional modifiers were introduced (93 for audio-only) but many expired post-PHE. Incorrect modifier selection causes denials or processing delays.',
'Modifier 95 = synchronous telemedicine (Medicare-preferred, most commercial payers). Modifier GT = interactive telehealth (some Medicaid, older modifier). Use payer-required modifier - most prefer 95 currently.',
133, ARRAY['modifier 95 vs GT', 'telehealth modifiers', '95 GT difference', 'telemedicine modifiers']);

-- PATIENT BILLING FAQs  
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'patient-billing', 'Why am I receiving a medical bill?',
'Medical bills are sent when: (1) Insurance didn''t cover full amount - deductible, coinsurance, or copay owed, (2) Service not covered by insurance - non-covered benefit or medical necessity denial, (3) Insurance paid but patient responsibility remains, (4) Claim still processing - statement sent before insurance payment posted, (5) Secondary insurance balance - primary paid but patient owes remaining amount. Your bill shows: service dates, charges, insurance payments, adjustments, your remaining balance. Review your Explanation of Benefits (EOB) from insurance to understand coverage determination. If you believe insurance should have paid more, contact your insurance company first. If you have secondary insurance, provide information to billing office. Payment plans are often available. Contact billing office with questions before the due date to discuss options or clarify charges.',
'Bills are sent for patient responsibility after insurance: deductible, coinsurance, copay, or non-covered services. Review your EOB to understand insurance payment. Contact billing office with questions or for payment plans.',
140, ARRAY['why bill', 'medical bill', 'patient bill', 'balance owed']),

('general', 'patient-billing', 'What is an Explanation of Benefits (EOB)?',
'An Explanation of Benefits (EOB) is a statement from your insurance explaining how they processed your medical claim. EOBs show: service date and description, provider charges, allowed amount (contracted rate), insurance payment, patient responsibility (deductible, coinsurance, copay), denial reasons if applicable. Key points: EOB is NOT a bill - it''s an explanation of coverage, sent after insurance processes claim, helps you understand what you owe, includes claim/reference numbers. How to read your EOB: "Amount Billed" = provider''s charge, "Amount Allowed" = insurance-approved amount, "Amount Paid" = insurance payment, "Your Responsibility" = what you owe. If your EOB shows services denied or you disagree with coverage determination, contact your insurance company to discuss or appeal. Keep EOBs for your records and compare with provider bills.',
'An EOB explains how insurance processed your claim - not a bill. Shows: services, charges, allowed amounts, insurance payment, your responsibility (deductible/coinsurance/copay). Compare EOB with provider bill.',
141, ARRAY['EOB', 'explanation of benefits', 'insurance statement', 'what is EOB']),

('general', 'patient-billing', 'What is a patient responsibility?',
'Patient responsibility is the portion of medical costs you must pay, including: (1) Deductible - amount you pay before insurance begins paying (resets annually), (2) Copay - fixed amount per visit/service specified in your plan, (3) Coinsurance - percentage of costs you pay after deductible (e.g., 20% with 80/20 plan), (4) Non-covered services - services insurance doesn''t cover, (5) Out-of-network costs - additional amounts for non-participating providers. Your insurance card shows: copay amounts, deductible amount, coinsurance percentage, out-of-pocket maximum. Maximum out-of-pocket: once reached, insurance pays 100% of covered services. Understanding your benefits helps anticipate costs. Get cost estimates before procedures. Verify coverage for services. Ask about payment plans if unable to pay full balance. Patient responsibility amounts vary significantly by insurance plan.',
'Patient responsibility includes: deductible (annual amount before insurance pays), copay (fixed per visit), coinsurance (percentage after deductible), and non-covered services. Amounts vary by insurance plan.',
142, ARRAY['patient responsibility', 'what I owe', 'out of pocket', 'deductible copay']),

('general', 'patient-billing', 'How do I set up a payment plan?',
'Payment plan process: (1) Contact billing office - call number on statement before due date, (2) Discuss balance - explain financial situation and request payment plan, (3) Provide financial information - may need to complete financial assistance application, (4) Agree on terms - monthly payment amount and duration, (5) Make consistent payments - set up automatic payments if available. Payment plan options vary: interest-free plans (typically 6-12 months), longer plans may have interest, low monthly payments based on ability to pay, some require down payment. Financial assistance may be available for qualifying patients based on income. Benefits of payment plans: avoid collections, maintain good credit, budget manageable amounts, prevent late fees. Setup before due date prevents collection action. Most providers prefer working with patients proactively versus collections.',
'Contact billing office before due date to request payment plan. Discuss your situation and ability to pay. Most providers offer interest-free plans (6-12 months). Financial assistance may be available. Setup prevents collections.',
143, ARRAY['payment plan', 'payment arrangements', 'pay bill', 'financial assistance']);

-- CREDENTIALING FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'credentialing', 'What is provider credentialing?',
'Provider credentialing is the process of verifying healthcare provider qualifications and enrolling them with insurance networks. Process includes: (1) Application submission - demographic, education, training, licenses, (2) Primary source verification - contacting schools, boards, hospitals directly, (3) Background checks - OIG exclusion list, sanctions, malpractice claims, (4) Committee review - credentials committee approves/denies, (5) Network enrollment - provider added to participating network. Timeline: typically 90-180 days (can be longer). Required for: Medicare/Medicaid enrollment, commercial insurance participation, hospital privileges. Documents needed: CV, licenses, DEA, board certifications, malpractice insurance, education/training verification, work history, references. Re-credentialing required every 2-3 years. CAQH ProView centralizes credentialing information for efficiency. Incomplete credentialing prevents in-network billing and delays revenue.',
'Credentialing verifies provider qualifications and enrolls with insurance networks. Takes 90-180 days. Requires licenses, education, training verification, malpractice insurance. Re-credentialing every 2-3 years. Essential for in-network billing.',
150, ARRAY['credentialing', 'provider enrollment', 'insurance credentialing', 'CAQH']),

('general', 'credentialing', 'How long does credentialing take?',
'Credentialing timeline varies: Standard process: 90-120 days minimum, Complex applications: 120-180+ days (multiple locations, specialties, or incomplete information), Expedited: 60-90 days possible with complete applications and follow-up. Factors affecting timeline: (1) Application completeness - missing documents cause delays, (2) Primary source response times - schools/boards take weeks to respond, (3) Committee meeting schedules - may meet monthly, (4) Payer processing times - varies by organization, (5) Application volume - high volumes slow processing. Delay prevention: submit complete applications, respond immediately to requests, maintain current CAQH profile, follow up regularly, hire credentialing specialist. Start credentialing 6+ months before provider start date. Delays mean providers cannot bill in-network, creating cash-flow issues. Medtransic manages credentialing timelines and follow-up to minimize delays.',
'Standard credentialing: 90-120 days. Can extend to 180+ days if incomplete or complex. Start 6+ months before provider start date. Delays prevent in-network billing and create revenue issues.',
151, ARRAY['credentialing time', 'how long', 'credentialing timeline', 'enrollment time']),

('general', 'credentialing', 'What happens if I bill without credentialing?',
'Billing without credentialing results in: (1) Claim denials - "provider not found" or "not participating", (2) Out-of-network rates - lower payment than in-network contracted rates, (3) Patient balance billing issues - patients expect in-network costs, (4) Contract violations - billing as in-network without enrollment, (5) Revenue delays - credentialing takes months to complete. Consequences: significant revenue loss (out-of-network pays 40-60% less), patient dissatisfaction and complaints, potential refunds to patients if incorrectly billed as in-network, compliance concerns if misrepresenting network status. Prevention: complete credentialing before seeing patients, verify enrollment status before billing, use correct provider numbers on claims, maintain current credentials and re-credentialing. Emergency situations may have retroactive enrollment options. Medtransic ensures providers are properly credentialed before billing to prevent revenue loss.',
'Billing without credentialing causes claim denials or out-of-network payment (40-60% less than in-network). Creates patient balance issues and compliance concerns. Complete credentialing before seeing patients to prevent revenue loss.',
152, ARRAY['billing without credentialing', 'not credentialed', 'provider not found', 'credentialing required']);

-- ACCOUNTS RECEIVABLE FAQs
INSERT INTO specialty_faqs (specialty_slug, category, question, answer, short_answer, priority, search_keywords) VALUES
('general', 'ar-followup', 'What is A/R follow-up in medical billing?',
'A/R (Accounts Receivable) follow-up is the systematic process of tracking unpaid claims and taking action to secure payment. Process includes: (1) Monitoring claim status - checking submission confirmation and processing, (2) Identifying issues - denials, pending claims, no response, (3) Taking corrective action - appeals, resubmissions, payer contact, (4) Documentation - tracking follow-up actions and outcomes, (5) Reporting - aging analysis and collection metrics. Follow-up frequency: 0-30 days: monitor for payment, 31-60 days: initial follow-up contact, 61-90 days: aggressive follow-up, 90+ days: escalated action or collections. Goals: reduce days in A/R (target <40 days), maximize collection rates (target >95%), minimize write-offs, identify systemic issues. Effective A/R management requires dedicated staff, systematic processes, technology tools, and persistence. Medtransic provides comprehensive A/R follow-up ensuring maximum revenue collection.',
'A/R follow-up tracks unpaid claims and takes action to secure payment. Includes monitoring status, identifying issues, corrective action, and reporting. Goal: reduce days in A/R below 40 and maximize collections over 95%.',
160, ARRAY['A/R follow-up', 'accounts receivable', 'claim follow-up', 'AR management']),

('general', 'ar-followup', 'How can Medtransic help reduce aged A/R?',
'Medtransic reduces aged A/R through: (1) Systematic follow-up - regular contact on all unpaid claims over 30 days, (2) Denial management - rapid identification and resolution of denials, (3) Root cause analysis - identifying and fixing systemic issues causing delays, (4) Payer relationships - established contacts for faster resolution, (5) Technology - automated tracking and alerts for follow-up, (6) Expertise - experienced staff understanding payer-specific processes, (7) Appeals - filing timely appeals with strong documentation. Typical results: reduce >90 day A/R by 40-60%, decrease overall days in A/R by 10-15 days, improve collection rates 3-5%, recover previously written-off balances. Process: comprehensive A/R audit, prioritized work lists, daily follow-up activities, weekly status reporting, continuous monitoring. Old A/R cleanup available for practices with significant aged balances. Improved A/R directly increases practice cash flow and profitability.',
'Medtransic reduces aged A/R through systematic follow-up, rapid denial resolution, root cause fixes, payer expertise, and technology. Typical results: 40-60% reduction in >90-day A/R, 10-15 day reduction in total A/R days.',
161, ARRAY['reduce A/R', 'aged A/R', 'old A/R', 'improve collections', 'Medtransic services']);

